
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Correlative` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Correlative
 * 
 */
export type CorrelativeModel = runtime.Types.Result.DefaultSelection<Prisma.$CorrelativePayload>

export type AggregateCorrelative = {
  _count: CorrelativeCountAggregateOutputType | null
  _min: CorrelativeMinAggregateOutputType | null
  _max: CorrelativeMaxAggregateOutputType | null
}

export type CorrelativeMinAggregateOutputType = {
  idCourse: string | null
  idCorrelativeCourse: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CorrelativeMaxAggregateOutputType = {
  idCourse: string | null
  idCorrelativeCourse: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CorrelativeCountAggregateOutputType = {
  idCourse: number
  idCorrelativeCourse: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CorrelativeMinAggregateInputType = {
  idCourse?: true
  idCorrelativeCourse?: true
  createdAt?: true
  updatedAt?: true
}

export type CorrelativeMaxAggregateInputType = {
  idCourse?: true
  idCorrelativeCourse?: true
  createdAt?: true
  updatedAt?: true
}

export type CorrelativeCountAggregateInputType = {
  idCourse?: true
  idCorrelativeCourse?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CorrelativeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Correlative to aggregate.
   */
  where?: Prisma.CorrelativeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Correlatives to fetch.
   */
  orderBy?: Prisma.CorrelativeOrderByWithRelationInput | Prisma.CorrelativeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CorrelativeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Correlatives from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Correlatives.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Correlatives
  **/
  _count?: true | CorrelativeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CorrelativeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CorrelativeMaxAggregateInputType
}

export type GetCorrelativeAggregateType<T extends CorrelativeAggregateArgs> = {
      [P in keyof T & keyof AggregateCorrelative]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCorrelative[P]>
    : Prisma.GetScalarType<T[P], AggregateCorrelative[P]>
}




export type CorrelativeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CorrelativeWhereInput
  orderBy?: Prisma.CorrelativeOrderByWithAggregationInput | Prisma.CorrelativeOrderByWithAggregationInput[]
  by: Prisma.CorrelativeScalarFieldEnum[] | Prisma.CorrelativeScalarFieldEnum
  having?: Prisma.CorrelativeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CorrelativeCountAggregateInputType | true
  _min?: CorrelativeMinAggregateInputType
  _max?: CorrelativeMaxAggregateInputType
}

export type CorrelativeGroupByOutputType = {
  idCourse: string
  idCorrelativeCourse: string
  createdAt: Date
  updatedAt: Date
  _count: CorrelativeCountAggregateOutputType | null
  _min: CorrelativeMinAggregateOutputType | null
  _max: CorrelativeMaxAggregateOutputType | null
}

type GetCorrelativeGroupByPayload<T extends CorrelativeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CorrelativeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CorrelativeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CorrelativeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CorrelativeGroupByOutputType[P]>
      }
    >
  >



export type CorrelativeWhereInput = {
  AND?: Prisma.CorrelativeWhereInput | Prisma.CorrelativeWhereInput[]
  OR?: Prisma.CorrelativeWhereInput[]
  NOT?: Prisma.CorrelativeWhereInput | Prisma.CorrelativeWhereInput[]
  idCourse?: Prisma.StringFilter<"Correlative"> | string
  idCorrelativeCourse?: Prisma.StringFilter<"Correlative"> | string
  createdAt?: Prisma.DateTimeFilter<"Correlative"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Correlative"> | Date | string
  courses_correlatives_id_correlativeTocourses?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
  courses_correlatives_idTocourses?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
}

export type CorrelativeOrderByWithRelationInput = {
  idCourse?: Prisma.SortOrder
  idCorrelativeCourse?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  courses_correlatives_id_correlativeTocourses?: Prisma.CourseOrderByWithRelationInput
  courses_correlatives_idTocourses?: Prisma.CourseOrderByWithRelationInput
}

export type CorrelativeWhereUniqueInput = Prisma.AtLeast<{
  idCourse_idCorrelativeCourse?: Prisma.CorrelativeIdCourseIdCorrelativeCourseCompoundUniqueInput
  AND?: Prisma.CorrelativeWhereInput | Prisma.CorrelativeWhereInput[]
  OR?: Prisma.CorrelativeWhereInput[]
  NOT?: Prisma.CorrelativeWhereInput | Prisma.CorrelativeWhereInput[]
  idCourse?: Prisma.StringFilter<"Correlative"> | string
  idCorrelativeCourse?: Prisma.StringFilter<"Correlative"> | string
  createdAt?: Prisma.DateTimeFilter<"Correlative"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Correlative"> | Date | string
  courses_correlatives_id_correlativeTocourses?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
  courses_correlatives_idTocourses?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
}, "idCourse_idCorrelativeCourse">

export type CorrelativeOrderByWithAggregationInput = {
  idCourse?: Prisma.SortOrder
  idCorrelativeCourse?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CorrelativeCountOrderByAggregateInput
  _max?: Prisma.CorrelativeMaxOrderByAggregateInput
  _min?: Prisma.CorrelativeMinOrderByAggregateInput
}

export type CorrelativeScalarWhereWithAggregatesInput = {
  AND?: Prisma.CorrelativeScalarWhereWithAggregatesInput | Prisma.CorrelativeScalarWhereWithAggregatesInput[]
  OR?: Prisma.CorrelativeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CorrelativeScalarWhereWithAggregatesInput | Prisma.CorrelativeScalarWhereWithAggregatesInput[]
  idCourse?: Prisma.StringWithAggregatesFilter<"Correlative"> | string
  idCorrelativeCourse?: Prisma.StringWithAggregatesFilter<"Correlative"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Correlative"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Correlative"> | Date | string
}

export type CorrelativeCreateInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  courses_correlatives_id_correlativeTocourses: Prisma.CourseCreateNestedOneWithoutCorrelatives_correlatives_id_correlativeTocoursesInput
  courses_correlatives_idTocourses: Prisma.CourseCreateNestedOneWithoutCorrelatives_correlatives_idTocoursesInput
}

export type CorrelativeUncheckedCreateInput = {
  idCourse: string
  idCorrelativeCourse: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CorrelativeUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courses_correlatives_id_correlativeTocourses?: Prisma.CourseUpdateOneRequiredWithoutCorrelatives_correlatives_id_correlativeTocoursesNestedInput
  courses_correlatives_idTocourses?: Prisma.CourseUpdateOneRequiredWithoutCorrelatives_correlatives_idTocoursesNestedInput
}

export type CorrelativeUncheckedUpdateInput = {
  idCourse?: Prisma.StringFieldUpdateOperationsInput | string
  idCorrelativeCourse?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CorrelativeCreateManyInput = {
  idCourse: string
  idCorrelativeCourse: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CorrelativeUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CorrelativeUncheckedUpdateManyInput = {
  idCourse?: Prisma.StringFieldUpdateOperationsInput | string
  idCorrelativeCourse?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CorrelativeIdCourseIdCorrelativeCourseCompoundUniqueInput = {
  idCourse: string
  idCorrelativeCourse: string
}

export type CorrelativeCountOrderByAggregateInput = {
  idCourse?: Prisma.SortOrder
  idCorrelativeCourse?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CorrelativeMaxOrderByAggregateInput = {
  idCourse?: Prisma.SortOrder
  idCorrelativeCourse?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CorrelativeMinOrderByAggregateInput = {
  idCourse?: Prisma.SortOrder
  idCorrelativeCourse?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CorrelativeListRelationFilter = {
  every?: Prisma.CorrelativeWhereInput
  some?: Prisma.CorrelativeWhereInput
  none?: Prisma.CorrelativeWhereInput
}

export type CorrelativeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type CorrelativeCreateNestedManyWithoutCourses_correlatives_id_correlativeTocoursesInput = {
  create?: Prisma.XOR<Prisma.CorrelativeCreateWithoutCourses_correlatives_id_correlativeTocoursesInput, Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_id_correlativeTocoursesInput> | Prisma.CorrelativeCreateWithoutCourses_correlatives_id_correlativeTocoursesInput[] | Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_id_correlativeTocoursesInput[]
  connectOrCreate?: Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_id_correlativeTocoursesInput | Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_id_correlativeTocoursesInput[]
  createMany?: Prisma.CorrelativeCreateManyCourses_correlatives_id_correlativeTocoursesInputEnvelope
  connect?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
}

export type CorrelativeCreateNestedManyWithoutCourses_correlatives_idTocoursesInput = {
  create?: Prisma.XOR<Prisma.CorrelativeCreateWithoutCourses_correlatives_idTocoursesInput, Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_idTocoursesInput> | Prisma.CorrelativeCreateWithoutCourses_correlatives_idTocoursesInput[] | Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_idTocoursesInput[]
  connectOrCreate?: Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_idTocoursesInput | Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_idTocoursesInput[]
  createMany?: Prisma.CorrelativeCreateManyCourses_correlatives_idTocoursesInputEnvelope
  connect?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
}

export type CorrelativeUncheckedCreateNestedManyWithoutCourses_correlatives_id_correlativeTocoursesInput = {
  create?: Prisma.XOR<Prisma.CorrelativeCreateWithoutCourses_correlatives_id_correlativeTocoursesInput, Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_id_correlativeTocoursesInput> | Prisma.CorrelativeCreateWithoutCourses_correlatives_id_correlativeTocoursesInput[] | Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_id_correlativeTocoursesInput[]
  connectOrCreate?: Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_id_correlativeTocoursesInput | Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_id_correlativeTocoursesInput[]
  createMany?: Prisma.CorrelativeCreateManyCourses_correlatives_id_correlativeTocoursesInputEnvelope
  connect?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
}

export type CorrelativeUncheckedCreateNestedManyWithoutCourses_correlatives_idTocoursesInput = {
  create?: Prisma.XOR<Prisma.CorrelativeCreateWithoutCourses_correlatives_idTocoursesInput, Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_idTocoursesInput> | Prisma.CorrelativeCreateWithoutCourses_correlatives_idTocoursesInput[] | Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_idTocoursesInput[]
  connectOrCreate?: Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_idTocoursesInput | Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_idTocoursesInput[]
  createMany?: Prisma.CorrelativeCreateManyCourses_correlatives_idTocoursesInputEnvelope
  connect?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
}

export type CorrelativeUpdateManyWithoutCourses_correlatives_id_correlativeTocoursesNestedInput = {
  create?: Prisma.XOR<Prisma.CorrelativeCreateWithoutCourses_correlatives_id_correlativeTocoursesInput, Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_id_correlativeTocoursesInput> | Prisma.CorrelativeCreateWithoutCourses_correlatives_id_correlativeTocoursesInput[] | Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_id_correlativeTocoursesInput[]
  connectOrCreate?: Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_id_correlativeTocoursesInput | Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_id_correlativeTocoursesInput[]
  upsert?: Prisma.CorrelativeUpsertWithWhereUniqueWithoutCourses_correlatives_id_correlativeTocoursesInput | Prisma.CorrelativeUpsertWithWhereUniqueWithoutCourses_correlatives_id_correlativeTocoursesInput[]
  createMany?: Prisma.CorrelativeCreateManyCourses_correlatives_id_correlativeTocoursesInputEnvelope
  set?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  disconnect?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  delete?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  connect?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  update?: Prisma.CorrelativeUpdateWithWhereUniqueWithoutCourses_correlatives_id_correlativeTocoursesInput | Prisma.CorrelativeUpdateWithWhereUniqueWithoutCourses_correlatives_id_correlativeTocoursesInput[]
  updateMany?: Prisma.CorrelativeUpdateManyWithWhereWithoutCourses_correlatives_id_correlativeTocoursesInput | Prisma.CorrelativeUpdateManyWithWhereWithoutCourses_correlatives_id_correlativeTocoursesInput[]
  deleteMany?: Prisma.CorrelativeScalarWhereInput | Prisma.CorrelativeScalarWhereInput[]
}

export type CorrelativeUpdateManyWithoutCourses_correlatives_idTocoursesNestedInput = {
  create?: Prisma.XOR<Prisma.CorrelativeCreateWithoutCourses_correlatives_idTocoursesInput, Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_idTocoursesInput> | Prisma.CorrelativeCreateWithoutCourses_correlatives_idTocoursesInput[] | Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_idTocoursesInput[]
  connectOrCreate?: Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_idTocoursesInput | Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_idTocoursesInput[]
  upsert?: Prisma.CorrelativeUpsertWithWhereUniqueWithoutCourses_correlatives_idTocoursesInput | Prisma.CorrelativeUpsertWithWhereUniqueWithoutCourses_correlatives_idTocoursesInput[]
  createMany?: Prisma.CorrelativeCreateManyCourses_correlatives_idTocoursesInputEnvelope
  set?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  disconnect?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  delete?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  connect?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  update?: Prisma.CorrelativeUpdateWithWhereUniqueWithoutCourses_correlatives_idTocoursesInput | Prisma.CorrelativeUpdateWithWhereUniqueWithoutCourses_correlatives_idTocoursesInput[]
  updateMany?: Prisma.CorrelativeUpdateManyWithWhereWithoutCourses_correlatives_idTocoursesInput | Prisma.CorrelativeUpdateManyWithWhereWithoutCourses_correlatives_idTocoursesInput[]
  deleteMany?: Prisma.CorrelativeScalarWhereInput | Prisma.CorrelativeScalarWhereInput[]
}

export type CorrelativeUncheckedUpdateManyWithoutCourses_correlatives_id_correlativeTocoursesNestedInput = {
  create?: Prisma.XOR<Prisma.CorrelativeCreateWithoutCourses_correlatives_id_correlativeTocoursesInput, Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_id_correlativeTocoursesInput> | Prisma.CorrelativeCreateWithoutCourses_correlatives_id_correlativeTocoursesInput[] | Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_id_correlativeTocoursesInput[]
  connectOrCreate?: Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_id_correlativeTocoursesInput | Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_id_correlativeTocoursesInput[]
  upsert?: Prisma.CorrelativeUpsertWithWhereUniqueWithoutCourses_correlatives_id_correlativeTocoursesInput | Prisma.CorrelativeUpsertWithWhereUniqueWithoutCourses_correlatives_id_correlativeTocoursesInput[]
  createMany?: Prisma.CorrelativeCreateManyCourses_correlatives_id_correlativeTocoursesInputEnvelope
  set?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  disconnect?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  delete?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  connect?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  update?: Prisma.CorrelativeUpdateWithWhereUniqueWithoutCourses_correlatives_id_correlativeTocoursesInput | Prisma.CorrelativeUpdateWithWhereUniqueWithoutCourses_correlatives_id_correlativeTocoursesInput[]
  updateMany?: Prisma.CorrelativeUpdateManyWithWhereWithoutCourses_correlatives_id_correlativeTocoursesInput | Prisma.CorrelativeUpdateManyWithWhereWithoutCourses_correlatives_id_correlativeTocoursesInput[]
  deleteMany?: Prisma.CorrelativeScalarWhereInput | Prisma.CorrelativeScalarWhereInput[]
}

export type CorrelativeUncheckedUpdateManyWithoutCourses_correlatives_idTocoursesNestedInput = {
  create?: Prisma.XOR<Prisma.CorrelativeCreateWithoutCourses_correlatives_idTocoursesInput, Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_idTocoursesInput> | Prisma.CorrelativeCreateWithoutCourses_correlatives_idTocoursesInput[] | Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_idTocoursesInput[]
  connectOrCreate?: Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_idTocoursesInput | Prisma.CorrelativeCreateOrConnectWithoutCourses_correlatives_idTocoursesInput[]
  upsert?: Prisma.CorrelativeUpsertWithWhereUniqueWithoutCourses_correlatives_idTocoursesInput | Prisma.CorrelativeUpsertWithWhereUniqueWithoutCourses_correlatives_idTocoursesInput[]
  createMany?: Prisma.CorrelativeCreateManyCourses_correlatives_idTocoursesInputEnvelope
  set?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  disconnect?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  delete?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  connect?: Prisma.CorrelativeWhereUniqueInput | Prisma.CorrelativeWhereUniqueInput[]
  update?: Prisma.CorrelativeUpdateWithWhereUniqueWithoutCourses_correlatives_idTocoursesInput | Prisma.CorrelativeUpdateWithWhereUniqueWithoutCourses_correlatives_idTocoursesInput[]
  updateMany?: Prisma.CorrelativeUpdateManyWithWhereWithoutCourses_correlatives_idTocoursesInput | Prisma.CorrelativeUpdateManyWithWhereWithoutCourses_correlatives_idTocoursesInput[]
  deleteMany?: Prisma.CorrelativeScalarWhereInput | Prisma.CorrelativeScalarWhereInput[]
}

export type CorrelativeCreateWithoutCourses_correlatives_id_correlativeTocoursesInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  courses_correlatives_idTocourses: Prisma.CourseCreateNestedOneWithoutCorrelatives_correlatives_idTocoursesInput
}

export type CorrelativeUncheckedCreateWithoutCourses_correlatives_id_correlativeTocoursesInput = {
  idCourse: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CorrelativeCreateOrConnectWithoutCourses_correlatives_id_correlativeTocoursesInput = {
  where: Prisma.CorrelativeWhereUniqueInput
  create: Prisma.XOR<Prisma.CorrelativeCreateWithoutCourses_correlatives_id_correlativeTocoursesInput, Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_id_correlativeTocoursesInput>
}

export type CorrelativeCreateManyCourses_correlatives_id_correlativeTocoursesInputEnvelope = {
  data: Prisma.CorrelativeCreateManyCourses_correlatives_id_correlativeTocoursesInput | Prisma.CorrelativeCreateManyCourses_correlatives_id_correlativeTocoursesInput[]
  skipDuplicates?: boolean
}

export type CorrelativeCreateWithoutCourses_correlatives_idTocoursesInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  courses_correlatives_id_correlativeTocourses: Prisma.CourseCreateNestedOneWithoutCorrelatives_correlatives_id_correlativeTocoursesInput
}

export type CorrelativeUncheckedCreateWithoutCourses_correlatives_idTocoursesInput = {
  idCorrelativeCourse: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CorrelativeCreateOrConnectWithoutCourses_correlatives_idTocoursesInput = {
  where: Prisma.CorrelativeWhereUniqueInput
  create: Prisma.XOR<Prisma.CorrelativeCreateWithoutCourses_correlatives_idTocoursesInput, Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_idTocoursesInput>
}

export type CorrelativeCreateManyCourses_correlatives_idTocoursesInputEnvelope = {
  data: Prisma.CorrelativeCreateManyCourses_correlatives_idTocoursesInput | Prisma.CorrelativeCreateManyCourses_correlatives_idTocoursesInput[]
  skipDuplicates?: boolean
}

export type CorrelativeUpsertWithWhereUniqueWithoutCourses_correlatives_id_correlativeTocoursesInput = {
  where: Prisma.CorrelativeWhereUniqueInput
  update: Prisma.XOR<Prisma.CorrelativeUpdateWithoutCourses_correlatives_id_correlativeTocoursesInput, Prisma.CorrelativeUncheckedUpdateWithoutCourses_correlatives_id_correlativeTocoursesInput>
  create: Prisma.XOR<Prisma.CorrelativeCreateWithoutCourses_correlatives_id_correlativeTocoursesInput, Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_id_correlativeTocoursesInput>
}

export type CorrelativeUpdateWithWhereUniqueWithoutCourses_correlatives_id_correlativeTocoursesInput = {
  where: Prisma.CorrelativeWhereUniqueInput
  data: Prisma.XOR<Prisma.CorrelativeUpdateWithoutCourses_correlatives_id_correlativeTocoursesInput, Prisma.CorrelativeUncheckedUpdateWithoutCourses_correlatives_id_correlativeTocoursesInput>
}

export type CorrelativeUpdateManyWithWhereWithoutCourses_correlatives_id_correlativeTocoursesInput = {
  where: Prisma.CorrelativeScalarWhereInput
  data: Prisma.XOR<Prisma.CorrelativeUpdateManyMutationInput, Prisma.CorrelativeUncheckedUpdateManyWithoutCourses_correlatives_id_correlativeTocoursesInput>
}

export type CorrelativeScalarWhereInput = {
  AND?: Prisma.CorrelativeScalarWhereInput | Prisma.CorrelativeScalarWhereInput[]
  OR?: Prisma.CorrelativeScalarWhereInput[]
  NOT?: Prisma.CorrelativeScalarWhereInput | Prisma.CorrelativeScalarWhereInput[]
  idCourse?: Prisma.StringFilter<"Correlative"> | string
  idCorrelativeCourse?: Prisma.StringFilter<"Correlative"> | string
  createdAt?: Prisma.DateTimeFilter<"Correlative"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Correlative"> | Date | string
}

export type CorrelativeUpsertWithWhereUniqueWithoutCourses_correlatives_idTocoursesInput = {
  where: Prisma.CorrelativeWhereUniqueInput
  update: Prisma.XOR<Prisma.CorrelativeUpdateWithoutCourses_correlatives_idTocoursesInput, Prisma.CorrelativeUncheckedUpdateWithoutCourses_correlatives_idTocoursesInput>
  create: Prisma.XOR<Prisma.CorrelativeCreateWithoutCourses_correlatives_idTocoursesInput, Prisma.CorrelativeUncheckedCreateWithoutCourses_correlatives_idTocoursesInput>
}

export type CorrelativeUpdateWithWhereUniqueWithoutCourses_correlatives_idTocoursesInput = {
  where: Prisma.CorrelativeWhereUniqueInput
  data: Prisma.XOR<Prisma.CorrelativeUpdateWithoutCourses_correlatives_idTocoursesInput, Prisma.CorrelativeUncheckedUpdateWithoutCourses_correlatives_idTocoursesInput>
}

export type CorrelativeUpdateManyWithWhereWithoutCourses_correlatives_idTocoursesInput = {
  where: Prisma.CorrelativeScalarWhereInput
  data: Prisma.XOR<Prisma.CorrelativeUpdateManyMutationInput, Prisma.CorrelativeUncheckedUpdateManyWithoutCourses_correlatives_idTocoursesInput>
}

export type CorrelativeCreateManyCourses_correlatives_id_correlativeTocoursesInput = {
  idCourse: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CorrelativeCreateManyCourses_correlatives_idTocoursesInput = {
  idCorrelativeCourse: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CorrelativeUpdateWithoutCourses_correlatives_id_correlativeTocoursesInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courses_correlatives_idTocourses?: Prisma.CourseUpdateOneRequiredWithoutCorrelatives_correlatives_idTocoursesNestedInput
}

export type CorrelativeUncheckedUpdateWithoutCourses_correlatives_id_correlativeTocoursesInput = {
  idCourse?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CorrelativeUncheckedUpdateManyWithoutCourses_correlatives_id_correlativeTocoursesInput = {
  idCourse?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CorrelativeUpdateWithoutCourses_correlatives_idTocoursesInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courses_correlatives_id_correlativeTocourses?: Prisma.CourseUpdateOneRequiredWithoutCorrelatives_correlatives_id_correlativeTocoursesNestedInput
}

export type CorrelativeUncheckedUpdateWithoutCourses_correlatives_idTocoursesInput = {
  idCorrelativeCourse?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CorrelativeUncheckedUpdateManyWithoutCourses_correlatives_idTocoursesInput = {
  idCorrelativeCourse?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CorrelativeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idCourse?: boolean
  idCorrelativeCourse?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  courses_correlatives_id_correlativeTocourses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  courses_correlatives_idTocourses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["correlative"]>

export type CorrelativeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idCourse?: boolean
  idCorrelativeCourse?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  courses_correlatives_id_correlativeTocourses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  courses_correlatives_idTocourses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["correlative"]>

export type CorrelativeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idCourse?: boolean
  idCorrelativeCourse?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  courses_correlatives_id_correlativeTocourses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  courses_correlatives_idTocourses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["correlative"]>

export type CorrelativeSelectScalar = {
  idCourse?: boolean
  idCorrelativeCourse?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CorrelativeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"idCourse" | "idCorrelativeCourse" | "createdAt" | "updatedAt", ExtArgs["result"]["correlative"]>
export type CorrelativeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  courses_correlatives_id_correlativeTocourses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  courses_correlatives_idTocourses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}
export type CorrelativeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  courses_correlatives_id_correlativeTocourses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  courses_correlatives_idTocourses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}
export type CorrelativeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  courses_correlatives_id_correlativeTocourses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  courses_correlatives_idTocourses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
}

export type $CorrelativePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Correlative"
  objects: {
    courses_correlatives_id_correlativeTocourses: Prisma.$CoursePayload<ExtArgs>
    courses_correlatives_idTocourses: Prisma.$CoursePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    idCourse: string
    idCorrelativeCourse: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["correlative"]>
  composites: {}
}

export type CorrelativeGetPayload<S extends boolean | null | undefined | CorrelativeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CorrelativePayload, S>

export type CorrelativeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CorrelativeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CorrelativeCountAggregateInputType | true
  }

export interface CorrelativeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Correlative'], meta: { name: 'Correlative' } }
  /**
   * Find zero or one Correlative that matches the filter.
   * @param {CorrelativeFindUniqueArgs} args - Arguments to find a Correlative
   * @example
   * // Get one Correlative
   * const correlative = await prisma.correlative.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CorrelativeFindUniqueArgs>(args: Prisma.SelectSubset<T, CorrelativeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CorrelativeClient<runtime.Types.Result.GetResult<Prisma.$CorrelativePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Correlative that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CorrelativeFindUniqueOrThrowArgs} args - Arguments to find a Correlative
   * @example
   * // Get one Correlative
   * const correlative = await prisma.correlative.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CorrelativeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CorrelativeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CorrelativeClient<runtime.Types.Result.GetResult<Prisma.$CorrelativePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Correlative that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CorrelativeFindFirstArgs} args - Arguments to find a Correlative
   * @example
   * // Get one Correlative
   * const correlative = await prisma.correlative.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CorrelativeFindFirstArgs>(args?: Prisma.SelectSubset<T, CorrelativeFindFirstArgs<ExtArgs>>): Prisma.Prisma__CorrelativeClient<runtime.Types.Result.GetResult<Prisma.$CorrelativePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Correlative that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CorrelativeFindFirstOrThrowArgs} args - Arguments to find a Correlative
   * @example
   * // Get one Correlative
   * const correlative = await prisma.correlative.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CorrelativeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CorrelativeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CorrelativeClient<runtime.Types.Result.GetResult<Prisma.$CorrelativePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Correlatives that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CorrelativeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Correlatives
   * const correlatives = await prisma.correlative.findMany()
   * 
   * // Get first 10 Correlatives
   * const correlatives = await prisma.correlative.findMany({ take: 10 })
   * 
   * // Only select the `idCourse`
   * const correlativeWithIdCourseOnly = await prisma.correlative.findMany({ select: { idCourse: true } })
   * 
   */
  findMany<T extends CorrelativeFindManyArgs>(args?: Prisma.SelectSubset<T, CorrelativeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CorrelativePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Correlative.
   * @param {CorrelativeCreateArgs} args - Arguments to create a Correlative.
   * @example
   * // Create one Correlative
   * const Correlative = await prisma.correlative.create({
   *   data: {
   *     // ... data to create a Correlative
   *   }
   * })
   * 
   */
  create<T extends CorrelativeCreateArgs>(args: Prisma.SelectSubset<T, CorrelativeCreateArgs<ExtArgs>>): Prisma.Prisma__CorrelativeClient<runtime.Types.Result.GetResult<Prisma.$CorrelativePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Correlatives.
   * @param {CorrelativeCreateManyArgs} args - Arguments to create many Correlatives.
   * @example
   * // Create many Correlatives
   * const correlative = await prisma.correlative.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CorrelativeCreateManyArgs>(args?: Prisma.SelectSubset<T, CorrelativeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Correlatives and returns the data saved in the database.
   * @param {CorrelativeCreateManyAndReturnArgs} args - Arguments to create many Correlatives.
   * @example
   * // Create many Correlatives
   * const correlative = await prisma.correlative.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Correlatives and only return the `idCourse`
   * const correlativeWithIdCourseOnly = await prisma.correlative.createManyAndReturn({
   *   select: { idCourse: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CorrelativeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CorrelativeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CorrelativePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Correlative.
   * @param {CorrelativeDeleteArgs} args - Arguments to delete one Correlative.
   * @example
   * // Delete one Correlative
   * const Correlative = await prisma.correlative.delete({
   *   where: {
   *     // ... filter to delete one Correlative
   *   }
   * })
   * 
   */
  delete<T extends CorrelativeDeleteArgs>(args: Prisma.SelectSubset<T, CorrelativeDeleteArgs<ExtArgs>>): Prisma.Prisma__CorrelativeClient<runtime.Types.Result.GetResult<Prisma.$CorrelativePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Correlative.
   * @param {CorrelativeUpdateArgs} args - Arguments to update one Correlative.
   * @example
   * // Update one Correlative
   * const correlative = await prisma.correlative.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CorrelativeUpdateArgs>(args: Prisma.SelectSubset<T, CorrelativeUpdateArgs<ExtArgs>>): Prisma.Prisma__CorrelativeClient<runtime.Types.Result.GetResult<Prisma.$CorrelativePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Correlatives.
   * @param {CorrelativeDeleteManyArgs} args - Arguments to filter Correlatives to delete.
   * @example
   * // Delete a few Correlatives
   * const { count } = await prisma.correlative.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CorrelativeDeleteManyArgs>(args?: Prisma.SelectSubset<T, CorrelativeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Correlatives.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CorrelativeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Correlatives
   * const correlative = await prisma.correlative.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CorrelativeUpdateManyArgs>(args: Prisma.SelectSubset<T, CorrelativeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Correlatives and returns the data updated in the database.
   * @param {CorrelativeUpdateManyAndReturnArgs} args - Arguments to update many Correlatives.
   * @example
   * // Update many Correlatives
   * const correlative = await prisma.correlative.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Correlatives and only return the `idCourse`
   * const correlativeWithIdCourseOnly = await prisma.correlative.updateManyAndReturn({
   *   select: { idCourse: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CorrelativeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CorrelativeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CorrelativePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Correlative.
   * @param {CorrelativeUpsertArgs} args - Arguments to update or create a Correlative.
   * @example
   * // Update or create a Correlative
   * const correlative = await prisma.correlative.upsert({
   *   create: {
   *     // ... data to create a Correlative
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Correlative we want to update
   *   }
   * })
   */
  upsert<T extends CorrelativeUpsertArgs>(args: Prisma.SelectSubset<T, CorrelativeUpsertArgs<ExtArgs>>): Prisma.Prisma__CorrelativeClient<runtime.Types.Result.GetResult<Prisma.$CorrelativePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Correlatives.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CorrelativeCountArgs} args - Arguments to filter Correlatives to count.
   * @example
   * // Count the number of Correlatives
   * const count = await prisma.correlative.count({
   *   where: {
   *     // ... the filter for the Correlatives we want to count
   *   }
   * })
  **/
  count<T extends CorrelativeCountArgs>(
    args?: Prisma.Subset<T, CorrelativeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CorrelativeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Correlative.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CorrelativeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CorrelativeAggregateArgs>(args: Prisma.Subset<T, CorrelativeAggregateArgs>): Prisma.PrismaPromise<GetCorrelativeAggregateType<T>>

  /**
   * Group by Correlative.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CorrelativeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CorrelativeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CorrelativeGroupByArgs['orderBy'] }
      : { orderBy?: CorrelativeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CorrelativeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCorrelativeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Correlative model
 */
readonly fields: CorrelativeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Correlative.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CorrelativeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  courses_correlatives_id_correlativeTocourses<T extends Prisma.CourseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CourseDefaultArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  courses_correlatives_idTocourses<T extends Prisma.CourseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CourseDefaultArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Correlative model
 */
export interface CorrelativeFieldRefs {
  readonly idCourse: Prisma.FieldRef<"Correlative", 'String'>
  readonly idCorrelativeCourse: Prisma.FieldRef<"Correlative", 'String'>
  readonly createdAt: Prisma.FieldRef<"Correlative", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Correlative", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Correlative findUnique
 */
export type CorrelativeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Correlative
   */
  select?: Prisma.CorrelativeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Correlative
   */
  omit?: Prisma.CorrelativeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CorrelativeInclude<ExtArgs> | null
  /**
   * Filter, which Correlative to fetch.
   */
  where: Prisma.CorrelativeWhereUniqueInput
}

/**
 * Correlative findUniqueOrThrow
 */
export type CorrelativeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Correlative
   */
  select?: Prisma.CorrelativeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Correlative
   */
  omit?: Prisma.CorrelativeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CorrelativeInclude<ExtArgs> | null
  /**
   * Filter, which Correlative to fetch.
   */
  where: Prisma.CorrelativeWhereUniqueInput
}

/**
 * Correlative findFirst
 */
export type CorrelativeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Correlative
   */
  select?: Prisma.CorrelativeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Correlative
   */
  omit?: Prisma.CorrelativeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CorrelativeInclude<ExtArgs> | null
  /**
   * Filter, which Correlative to fetch.
   */
  where?: Prisma.CorrelativeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Correlatives to fetch.
   */
  orderBy?: Prisma.CorrelativeOrderByWithRelationInput | Prisma.CorrelativeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Correlatives.
   */
  cursor?: Prisma.CorrelativeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Correlatives from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Correlatives.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Correlatives.
   */
  distinct?: Prisma.CorrelativeScalarFieldEnum | Prisma.CorrelativeScalarFieldEnum[]
}

/**
 * Correlative findFirstOrThrow
 */
export type CorrelativeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Correlative
   */
  select?: Prisma.CorrelativeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Correlative
   */
  omit?: Prisma.CorrelativeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CorrelativeInclude<ExtArgs> | null
  /**
   * Filter, which Correlative to fetch.
   */
  where?: Prisma.CorrelativeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Correlatives to fetch.
   */
  orderBy?: Prisma.CorrelativeOrderByWithRelationInput | Prisma.CorrelativeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Correlatives.
   */
  cursor?: Prisma.CorrelativeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Correlatives from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Correlatives.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Correlatives.
   */
  distinct?: Prisma.CorrelativeScalarFieldEnum | Prisma.CorrelativeScalarFieldEnum[]
}

/**
 * Correlative findMany
 */
export type CorrelativeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Correlative
   */
  select?: Prisma.CorrelativeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Correlative
   */
  omit?: Prisma.CorrelativeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CorrelativeInclude<ExtArgs> | null
  /**
   * Filter, which Correlatives to fetch.
   */
  where?: Prisma.CorrelativeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Correlatives to fetch.
   */
  orderBy?: Prisma.CorrelativeOrderByWithRelationInput | Prisma.CorrelativeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Correlatives.
   */
  cursor?: Prisma.CorrelativeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Correlatives from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Correlatives.
   */
  skip?: number
  distinct?: Prisma.CorrelativeScalarFieldEnum | Prisma.CorrelativeScalarFieldEnum[]
}

/**
 * Correlative create
 */
export type CorrelativeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Correlative
   */
  select?: Prisma.CorrelativeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Correlative
   */
  omit?: Prisma.CorrelativeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CorrelativeInclude<ExtArgs> | null
  /**
   * The data needed to create a Correlative.
   */
  data: Prisma.XOR<Prisma.CorrelativeCreateInput, Prisma.CorrelativeUncheckedCreateInput>
}

/**
 * Correlative createMany
 */
export type CorrelativeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Correlatives.
   */
  data: Prisma.CorrelativeCreateManyInput | Prisma.CorrelativeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Correlative createManyAndReturn
 */
export type CorrelativeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Correlative
   */
  select?: Prisma.CorrelativeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Correlative
   */
  omit?: Prisma.CorrelativeOmit<ExtArgs> | null
  /**
   * The data used to create many Correlatives.
   */
  data: Prisma.CorrelativeCreateManyInput | Prisma.CorrelativeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CorrelativeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Correlative update
 */
export type CorrelativeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Correlative
   */
  select?: Prisma.CorrelativeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Correlative
   */
  omit?: Prisma.CorrelativeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CorrelativeInclude<ExtArgs> | null
  /**
   * The data needed to update a Correlative.
   */
  data: Prisma.XOR<Prisma.CorrelativeUpdateInput, Prisma.CorrelativeUncheckedUpdateInput>
  /**
   * Choose, which Correlative to update.
   */
  where: Prisma.CorrelativeWhereUniqueInput
}

/**
 * Correlative updateMany
 */
export type CorrelativeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Correlatives.
   */
  data: Prisma.XOR<Prisma.CorrelativeUpdateManyMutationInput, Prisma.CorrelativeUncheckedUpdateManyInput>
  /**
   * Filter which Correlatives to update
   */
  where?: Prisma.CorrelativeWhereInput
  /**
   * Limit how many Correlatives to update.
   */
  limit?: number
}

/**
 * Correlative updateManyAndReturn
 */
export type CorrelativeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Correlative
   */
  select?: Prisma.CorrelativeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Correlative
   */
  omit?: Prisma.CorrelativeOmit<ExtArgs> | null
  /**
   * The data used to update Correlatives.
   */
  data: Prisma.XOR<Prisma.CorrelativeUpdateManyMutationInput, Prisma.CorrelativeUncheckedUpdateManyInput>
  /**
   * Filter which Correlatives to update
   */
  where?: Prisma.CorrelativeWhereInput
  /**
   * Limit how many Correlatives to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CorrelativeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Correlative upsert
 */
export type CorrelativeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Correlative
   */
  select?: Prisma.CorrelativeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Correlative
   */
  omit?: Prisma.CorrelativeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CorrelativeInclude<ExtArgs> | null
  /**
   * The filter to search for the Correlative to update in case it exists.
   */
  where: Prisma.CorrelativeWhereUniqueInput
  /**
   * In case the Correlative found by the `where` argument doesn't exist, create a new Correlative with this data.
   */
  create: Prisma.XOR<Prisma.CorrelativeCreateInput, Prisma.CorrelativeUncheckedCreateInput>
  /**
   * In case the Correlative was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CorrelativeUpdateInput, Prisma.CorrelativeUncheckedUpdateInput>
}

/**
 * Correlative delete
 */
export type CorrelativeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Correlative
   */
  select?: Prisma.CorrelativeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Correlative
   */
  omit?: Prisma.CorrelativeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CorrelativeInclude<ExtArgs> | null
  /**
   * Filter which Correlative to delete.
   */
  where: Prisma.CorrelativeWhereUniqueInput
}

/**
 * Correlative deleteMany
 */
export type CorrelativeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Correlatives to delete
   */
  where?: Prisma.CorrelativeWhereInput
  /**
   * Limit how many Correlatives to delete.
   */
  limit?: number
}

/**
 * Correlative without action
 */
export type CorrelativeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Correlative
   */
  select?: Prisma.CorrelativeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Correlative
   */
  omit?: Prisma.CorrelativeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CorrelativeInclude<ExtArgs> | null
}
