
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DegreePlan` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DegreePlan
 * 
 */
export type DegreePlanModel = runtime.Types.Result.DefaultSelection<Prisma.$DegreePlanPayload>

export type AggregateDegreePlan = {
  _count: DegreePlanCountAggregateOutputType | null
  _min: DegreePlanMinAggregateOutputType | null
  _max: DegreePlanMaxAggregateOutputType | null
}

export type DegreePlanMinAggregateOutputType = {
  idDegree: string | null
  idPlan: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DegreePlanMaxAggregateOutputType = {
  idDegree: string | null
  idPlan: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DegreePlanCountAggregateOutputType = {
  idDegree: number
  idPlan: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DegreePlanMinAggregateInputType = {
  idDegree?: true
  idPlan?: true
  createdAt?: true
  updatedAt?: true
}

export type DegreePlanMaxAggregateInputType = {
  idDegree?: true
  idPlan?: true
  createdAt?: true
  updatedAt?: true
}

export type DegreePlanCountAggregateInputType = {
  idDegree?: true
  idPlan?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DegreePlanAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DegreePlan to aggregate.
   */
  where?: Prisma.DegreePlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DegreePlans to fetch.
   */
  orderBy?: Prisma.DegreePlanOrderByWithRelationInput | Prisma.DegreePlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DegreePlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DegreePlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DegreePlans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DegreePlans
  **/
  _count?: true | DegreePlanCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DegreePlanMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DegreePlanMaxAggregateInputType
}

export type GetDegreePlanAggregateType<T extends DegreePlanAggregateArgs> = {
      [P in keyof T & keyof AggregateDegreePlan]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDegreePlan[P]>
    : Prisma.GetScalarType<T[P], AggregateDegreePlan[P]>
}




export type DegreePlanGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DegreePlanWhereInput
  orderBy?: Prisma.DegreePlanOrderByWithAggregationInput | Prisma.DegreePlanOrderByWithAggregationInput[]
  by: Prisma.DegreePlanScalarFieldEnum[] | Prisma.DegreePlanScalarFieldEnum
  having?: Prisma.DegreePlanScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DegreePlanCountAggregateInputType | true
  _min?: DegreePlanMinAggregateInputType
  _max?: DegreePlanMaxAggregateInputType
}

export type DegreePlanGroupByOutputType = {
  idDegree: string
  idPlan: string
  createdAt: Date
  updatedAt: Date
  _count: DegreePlanCountAggregateOutputType | null
  _min: DegreePlanMinAggregateOutputType | null
  _max: DegreePlanMaxAggregateOutputType | null
}

type GetDegreePlanGroupByPayload<T extends DegreePlanGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DegreePlanGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DegreePlanGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DegreePlanGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DegreePlanGroupByOutputType[P]>
      }
    >
  >



export type DegreePlanWhereInput = {
  AND?: Prisma.DegreePlanWhereInput | Prisma.DegreePlanWhereInput[]
  OR?: Prisma.DegreePlanWhereInput[]
  NOT?: Prisma.DegreePlanWhereInput | Prisma.DegreePlanWhereInput[]
  idDegree?: Prisma.StringFilter<"DegreePlan"> | string
  idPlan?: Prisma.StringFilter<"DegreePlan"> | string
  createdAt?: Prisma.DateTimeFilter<"DegreePlan"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DegreePlan"> | Date | string
  degrees?: Prisma.XOR<Prisma.DegreeScalarRelationFilter, Prisma.DegreeWhereInput>
  plans?: Prisma.XOR<Prisma.PlanScalarRelationFilter, Prisma.PlanWhereInput>
}

export type DegreePlanOrderByWithRelationInput = {
  idDegree?: Prisma.SortOrder
  idPlan?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  degrees?: Prisma.DegreeOrderByWithRelationInput
  plans?: Prisma.PlanOrderByWithRelationInput
}

export type DegreePlanWhereUniqueInput = Prisma.AtLeast<{
  idDegree_idPlan?: Prisma.DegreePlanIdDegreeIdPlanCompoundUniqueInput
  AND?: Prisma.DegreePlanWhereInput | Prisma.DegreePlanWhereInput[]
  OR?: Prisma.DegreePlanWhereInput[]
  NOT?: Prisma.DegreePlanWhereInput | Prisma.DegreePlanWhereInput[]
  idDegree?: Prisma.StringFilter<"DegreePlan"> | string
  idPlan?: Prisma.StringFilter<"DegreePlan"> | string
  createdAt?: Prisma.DateTimeFilter<"DegreePlan"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DegreePlan"> | Date | string
  degrees?: Prisma.XOR<Prisma.DegreeScalarRelationFilter, Prisma.DegreeWhereInput>
  plans?: Prisma.XOR<Prisma.PlanScalarRelationFilter, Prisma.PlanWhereInput>
}, "idDegree_idPlan">

export type DegreePlanOrderByWithAggregationInput = {
  idDegree?: Prisma.SortOrder
  idPlan?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DegreePlanCountOrderByAggregateInput
  _max?: Prisma.DegreePlanMaxOrderByAggregateInput
  _min?: Prisma.DegreePlanMinOrderByAggregateInput
}

export type DegreePlanScalarWhereWithAggregatesInput = {
  AND?: Prisma.DegreePlanScalarWhereWithAggregatesInput | Prisma.DegreePlanScalarWhereWithAggregatesInput[]
  OR?: Prisma.DegreePlanScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DegreePlanScalarWhereWithAggregatesInput | Prisma.DegreePlanScalarWhereWithAggregatesInput[]
  idDegree?: Prisma.StringWithAggregatesFilter<"DegreePlan"> | string
  idPlan?: Prisma.StringWithAggregatesFilter<"DegreePlan"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DegreePlan"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DegreePlan"> | Date | string
}

export type DegreePlanCreateInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  degrees: Prisma.DegreeCreateNestedOneWithoutDegrees_plansInput
  plans: Prisma.PlanCreateNestedOneWithoutDegrees_plansInput
}

export type DegreePlanUncheckedCreateInput = {
  idDegree: string
  idPlan: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DegreePlanUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  degrees?: Prisma.DegreeUpdateOneRequiredWithoutDegrees_plansNestedInput
  plans?: Prisma.PlanUpdateOneRequiredWithoutDegrees_plansNestedInput
}

export type DegreePlanUncheckedUpdateInput = {
  idDegree?: Prisma.StringFieldUpdateOperationsInput | string
  idPlan?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DegreePlanCreateManyInput = {
  idDegree: string
  idPlan: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DegreePlanUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DegreePlanUncheckedUpdateManyInput = {
  idDegree?: Prisma.StringFieldUpdateOperationsInput | string
  idPlan?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DegreePlanListRelationFilter = {
  every?: Prisma.DegreePlanWhereInput
  some?: Prisma.DegreePlanWhereInput
  none?: Prisma.DegreePlanWhereInput
}

export type DegreePlanOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DegreePlanIdDegreeIdPlanCompoundUniqueInput = {
  idDegree: string
  idPlan: string
}

export type DegreePlanCountOrderByAggregateInput = {
  idDegree?: Prisma.SortOrder
  idPlan?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DegreePlanMaxOrderByAggregateInput = {
  idDegree?: Prisma.SortOrder
  idPlan?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DegreePlanMinOrderByAggregateInput = {
  idDegree?: Prisma.SortOrder
  idPlan?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DegreePlanCreateNestedManyWithoutDegreesInput = {
  create?: Prisma.XOR<Prisma.DegreePlanCreateWithoutDegreesInput, Prisma.DegreePlanUncheckedCreateWithoutDegreesInput> | Prisma.DegreePlanCreateWithoutDegreesInput[] | Prisma.DegreePlanUncheckedCreateWithoutDegreesInput[]
  connectOrCreate?: Prisma.DegreePlanCreateOrConnectWithoutDegreesInput | Prisma.DegreePlanCreateOrConnectWithoutDegreesInput[]
  createMany?: Prisma.DegreePlanCreateManyDegreesInputEnvelope
  connect?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
}

export type DegreePlanUncheckedCreateNestedManyWithoutDegreesInput = {
  create?: Prisma.XOR<Prisma.DegreePlanCreateWithoutDegreesInput, Prisma.DegreePlanUncheckedCreateWithoutDegreesInput> | Prisma.DegreePlanCreateWithoutDegreesInput[] | Prisma.DegreePlanUncheckedCreateWithoutDegreesInput[]
  connectOrCreate?: Prisma.DegreePlanCreateOrConnectWithoutDegreesInput | Prisma.DegreePlanCreateOrConnectWithoutDegreesInput[]
  createMany?: Prisma.DegreePlanCreateManyDegreesInputEnvelope
  connect?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
}

export type DegreePlanUpdateManyWithoutDegreesNestedInput = {
  create?: Prisma.XOR<Prisma.DegreePlanCreateWithoutDegreesInput, Prisma.DegreePlanUncheckedCreateWithoutDegreesInput> | Prisma.DegreePlanCreateWithoutDegreesInput[] | Prisma.DegreePlanUncheckedCreateWithoutDegreesInput[]
  connectOrCreate?: Prisma.DegreePlanCreateOrConnectWithoutDegreesInput | Prisma.DegreePlanCreateOrConnectWithoutDegreesInput[]
  upsert?: Prisma.DegreePlanUpsertWithWhereUniqueWithoutDegreesInput | Prisma.DegreePlanUpsertWithWhereUniqueWithoutDegreesInput[]
  createMany?: Prisma.DegreePlanCreateManyDegreesInputEnvelope
  set?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  disconnect?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  delete?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  connect?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  update?: Prisma.DegreePlanUpdateWithWhereUniqueWithoutDegreesInput | Prisma.DegreePlanUpdateWithWhereUniqueWithoutDegreesInput[]
  updateMany?: Prisma.DegreePlanUpdateManyWithWhereWithoutDegreesInput | Prisma.DegreePlanUpdateManyWithWhereWithoutDegreesInput[]
  deleteMany?: Prisma.DegreePlanScalarWhereInput | Prisma.DegreePlanScalarWhereInput[]
}

export type DegreePlanUncheckedUpdateManyWithoutDegreesNestedInput = {
  create?: Prisma.XOR<Prisma.DegreePlanCreateWithoutDegreesInput, Prisma.DegreePlanUncheckedCreateWithoutDegreesInput> | Prisma.DegreePlanCreateWithoutDegreesInput[] | Prisma.DegreePlanUncheckedCreateWithoutDegreesInput[]
  connectOrCreate?: Prisma.DegreePlanCreateOrConnectWithoutDegreesInput | Prisma.DegreePlanCreateOrConnectWithoutDegreesInput[]
  upsert?: Prisma.DegreePlanUpsertWithWhereUniqueWithoutDegreesInput | Prisma.DegreePlanUpsertWithWhereUniqueWithoutDegreesInput[]
  createMany?: Prisma.DegreePlanCreateManyDegreesInputEnvelope
  set?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  disconnect?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  delete?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  connect?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  update?: Prisma.DegreePlanUpdateWithWhereUniqueWithoutDegreesInput | Prisma.DegreePlanUpdateWithWhereUniqueWithoutDegreesInput[]
  updateMany?: Prisma.DegreePlanUpdateManyWithWhereWithoutDegreesInput | Prisma.DegreePlanUpdateManyWithWhereWithoutDegreesInput[]
  deleteMany?: Prisma.DegreePlanScalarWhereInput | Prisma.DegreePlanScalarWhereInput[]
}

export type DegreePlanCreateNestedManyWithoutPlansInput = {
  create?: Prisma.XOR<Prisma.DegreePlanCreateWithoutPlansInput, Prisma.DegreePlanUncheckedCreateWithoutPlansInput> | Prisma.DegreePlanCreateWithoutPlansInput[] | Prisma.DegreePlanUncheckedCreateWithoutPlansInput[]
  connectOrCreate?: Prisma.DegreePlanCreateOrConnectWithoutPlansInput | Prisma.DegreePlanCreateOrConnectWithoutPlansInput[]
  createMany?: Prisma.DegreePlanCreateManyPlansInputEnvelope
  connect?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
}

export type DegreePlanUncheckedCreateNestedManyWithoutPlansInput = {
  create?: Prisma.XOR<Prisma.DegreePlanCreateWithoutPlansInput, Prisma.DegreePlanUncheckedCreateWithoutPlansInput> | Prisma.DegreePlanCreateWithoutPlansInput[] | Prisma.DegreePlanUncheckedCreateWithoutPlansInput[]
  connectOrCreate?: Prisma.DegreePlanCreateOrConnectWithoutPlansInput | Prisma.DegreePlanCreateOrConnectWithoutPlansInput[]
  createMany?: Prisma.DegreePlanCreateManyPlansInputEnvelope
  connect?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
}

export type DegreePlanUpdateManyWithoutPlansNestedInput = {
  create?: Prisma.XOR<Prisma.DegreePlanCreateWithoutPlansInput, Prisma.DegreePlanUncheckedCreateWithoutPlansInput> | Prisma.DegreePlanCreateWithoutPlansInput[] | Prisma.DegreePlanUncheckedCreateWithoutPlansInput[]
  connectOrCreate?: Prisma.DegreePlanCreateOrConnectWithoutPlansInput | Prisma.DegreePlanCreateOrConnectWithoutPlansInput[]
  upsert?: Prisma.DegreePlanUpsertWithWhereUniqueWithoutPlansInput | Prisma.DegreePlanUpsertWithWhereUniqueWithoutPlansInput[]
  createMany?: Prisma.DegreePlanCreateManyPlansInputEnvelope
  set?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  disconnect?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  delete?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  connect?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  update?: Prisma.DegreePlanUpdateWithWhereUniqueWithoutPlansInput | Prisma.DegreePlanUpdateWithWhereUniqueWithoutPlansInput[]
  updateMany?: Prisma.DegreePlanUpdateManyWithWhereWithoutPlansInput | Prisma.DegreePlanUpdateManyWithWhereWithoutPlansInput[]
  deleteMany?: Prisma.DegreePlanScalarWhereInput | Prisma.DegreePlanScalarWhereInput[]
}

export type DegreePlanUncheckedUpdateManyWithoutPlansNestedInput = {
  create?: Prisma.XOR<Prisma.DegreePlanCreateWithoutPlansInput, Prisma.DegreePlanUncheckedCreateWithoutPlansInput> | Prisma.DegreePlanCreateWithoutPlansInput[] | Prisma.DegreePlanUncheckedCreateWithoutPlansInput[]
  connectOrCreate?: Prisma.DegreePlanCreateOrConnectWithoutPlansInput | Prisma.DegreePlanCreateOrConnectWithoutPlansInput[]
  upsert?: Prisma.DegreePlanUpsertWithWhereUniqueWithoutPlansInput | Prisma.DegreePlanUpsertWithWhereUniqueWithoutPlansInput[]
  createMany?: Prisma.DegreePlanCreateManyPlansInputEnvelope
  set?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  disconnect?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  delete?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  connect?: Prisma.DegreePlanWhereUniqueInput | Prisma.DegreePlanWhereUniqueInput[]
  update?: Prisma.DegreePlanUpdateWithWhereUniqueWithoutPlansInput | Prisma.DegreePlanUpdateWithWhereUniqueWithoutPlansInput[]
  updateMany?: Prisma.DegreePlanUpdateManyWithWhereWithoutPlansInput | Prisma.DegreePlanUpdateManyWithWhereWithoutPlansInput[]
  deleteMany?: Prisma.DegreePlanScalarWhereInput | Prisma.DegreePlanScalarWhereInput[]
}

export type DegreePlanCreateWithoutDegreesInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  plans: Prisma.PlanCreateNestedOneWithoutDegrees_plansInput
}

export type DegreePlanUncheckedCreateWithoutDegreesInput = {
  idPlan: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DegreePlanCreateOrConnectWithoutDegreesInput = {
  where: Prisma.DegreePlanWhereUniqueInput
  create: Prisma.XOR<Prisma.DegreePlanCreateWithoutDegreesInput, Prisma.DegreePlanUncheckedCreateWithoutDegreesInput>
}

export type DegreePlanCreateManyDegreesInputEnvelope = {
  data: Prisma.DegreePlanCreateManyDegreesInput | Prisma.DegreePlanCreateManyDegreesInput[]
  skipDuplicates?: boolean
}

export type DegreePlanUpsertWithWhereUniqueWithoutDegreesInput = {
  where: Prisma.DegreePlanWhereUniqueInput
  update: Prisma.XOR<Prisma.DegreePlanUpdateWithoutDegreesInput, Prisma.DegreePlanUncheckedUpdateWithoutDegreesInput>
  create: Prisma.XOR<Prisma.DegreePlanCreateWithoutDegreesInput, Prisma.DegreePlanUncheckedCreateWithoutDegreesInput>
}

export type DegreePlanUpdateWithWhereUniqueWithoutDegreesInput = {
  where: Prisma.DegreePlanWhereUniqueInput
  data: Prisma.XOR<Prisma.DegreePlanUpdateWithoutDegreesInput, Prisma.DegreePlanUncheckedUpdateWithoutDegreesInput>
}

export type DegreePlanUpdateManyWithWhereWithoutDegreesInput = {
  where: Prisma.DegreePlanScalarWhereInput
  data: Prisma.XOR<Prisma.DegreePlanUpdateManyMutationInput, Prisma.DegreePlanUncheckedUpdateManyWithoutDegreesInput>
}

export type DegreePlanScalarWhereInput = {
  AND?: Prisma.DegreePlanScalarWhereInput | Prisma.DegreePlanScalarWhereInput[]
  OR?: Prisma.DegreePlanScalarWhereInput[]
  NOT?: Prisma.DegreePlanScalarWhereInput | Prisma.DegreePlanScalarWhereInput[]
  idDegree?: Prisma.StringFilter<"DegreePlan"> | string
  idPlan?: Prisma.StringFilter<"DegreePlan"> | string
  createdAt?: Prisma.DateTimeFilter<"DegreePlan"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DegreePlan"> | Date | string
}

export type DegreePlanCreateWithoutPlansInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  degrees: Prisma.DegreeCreateNestedOneWithoutDegrees_plansInput
}

export type DegreePlanUncheckedCreateWithoutPlansInput = {
  idDegree: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DegreePlanCreateOrConnectWithoutPlansInput = {
  where: Prisma.DegreePlanWhereUniqueInput
  create: Prisma.XOR<Prisma.DegreePlanCreateWithoutPlansInput, Prisma.DegreePlanUncheckedCreateWithoutPlansInput>
}

export type DegreePlanCreateManyPlansInputEnvelope = {
  data: Prisma.DegreePlanCreateManyPlansInput | Prisma.DegreePlanCreateManyPlansInput[]
  skipDuplicates?: boolean
}

export type DegreePlanUpsertWithWhereUniqueWithoutPlansInput = {
  where: Prisma.DegreePlanWhereUniqueInput
  update: Prisma.XOR<Prisma.DegreePlanUpdateWithoutPlansInput, Prisma.DegreePlanUncheckedUpdateWithoutPlansInput>
  create: Prisma.XOR<Prisma.DegreePlanCreateWithoutPlansInput, Prisma.DegreePlanUncheckedCreateWithoutPlansInput>
}

export type DegreePlanUpdateWithWhereUniqueWithoutPlansInput = {
  where: Prisma.DegreePlanWhereUniqueInput
  data: Prisma.XOR<Prisma.DegreePlanUpdateWithoutPlansInput, Prisma.DegreePlanUncheckedUpdateWithoutPlansInput>
}

export type DegreePlanUpdateManyWithWhereWithoutPlansInput = {
  where: Prisma.DegreePlanScalarWhereInput
  data: Prisma.XOR<Prisma.DegreePlanUpdateManyMutationInput, Prisma.DegreePlanUncheckedUpdateManyWithoutPlansInput>
}

export type DegreePlanCreateManyDegreesInput = {
  idPlan: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DegreePlanUpdateWithoutDegreesInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  plans?: Prisma.PlanUpdateOneRequiredWithoutDegrees_plansNestedInput
}

export type DegreePlanUncheckedUpdateWithoutDegreesInput = {
  idPlan?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DegreePlanUncheckedUpdateManyWithoutDegreesInput = {
  idPlan?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DegreePlanCreateManyPlansInput = {
  idDegree: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DegreePlanUpdateWithoutPlansInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  degrees?: Prisma.DegreeUpdateOneRequiredWithoutDegrees_plansNestedInput
}

export type DegreePlanUncheckedUpdateWithoutPlansInput = {
  idDegree?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DegreePlanUncheckedUpdateManyWithoutPlansInput = {
  idDegree?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type DegreePlanSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idDegree?: boolean
  idPlan?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  degrees?: boolean | Prisma.DegreeDefaultArgs<ExtArgs>
  plans?: boolean | Prisma.PlanDefaultArgs<ExtArgs>
}, ExtArgs["result"]["degreePlan"]>

export type DegreePlanSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idDegree?: boolean
  idPlan?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  degrees?: boolean | Prisma.DegreeDefaultArgs<ExtArgs>
  plans?: boolean | Prisma.PlanDefaultArgs<ExtArgs>
}, ExtArgs["result"]["degreePlan"]>

export type DegreePlanSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idDegree?: boolean
  idPlan?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  degrees?: boolean | Prisma.DegreeDefaultArgs<ExtArgs>
  plans?: boolean | Prisma.PlanDefaultArgs<ExtArgs>
}, ExtArgs["result"]["degreePlan"]>

export type DegreePlanSelectScalar = {
  idDegree?: boolean
  idPlan?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DegreePlanOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"idDegree" | "idPlan" | "createdAt" | "updatedAt", ExtArgs["result"]["degreePlan"]>
export type DegreePlanInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  degrees?: boolean | Prisma.DegreeDefaultArgs<ExtArgs>
  plans?: boolean | Prisma.PlanDefaultArgs<ExtArgs>
}
export type DegreePlanIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  degrees?: boolean | Prisma.DegreeDefaultArgs<ExtArgs>
  plans?: boolean | Prisma.PlanDefaultArgs<ExtArgs>
}
export type DegreePlanIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  degrees?: boolean | Prisma.DegreeDefaultArgs<ExtArgs>
  plans?: boolean | Prisma.PlanDefaultArgs<ExtArgs>
}

export type $DegreePlanPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DegreePlan"
  objects: {
    degrees: Prisma.$DegreePayload<ExtArgs>
    plans: Prisma.$PlanPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    idDegree: string
    idPlan: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["degreePlan"]>
  composites: {}
}

export type DegreePlanGetPayload<S extends boolean | null | undefined | DegreePlanDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DegreePlanPayload, S>

export type DegreePlanCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DegreePlanFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DegreePlanCountAggregateInputType | true
  }

export interface DegreePlanDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DegreePlan'], meta: { name: 'DegreePlan' } }
  /**
   * Find zero or one DegreePlan that matches the filter.
   * @param {DegreePlanFindUniqueArgs} args - Arguments to find a DegreePlan
   * @example
   * // Get one DegreePlan
   * const degreePlan = await prisma.degreePlan.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DegreePlanFindUniqueArgs>(args: Prisma.SelectSubset<T, DegreePlanFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DegreePlanClient<runtime.Types.Result.GetResult<Prisma.$DegreePlanPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DegreePlan that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DegreePlanFindUniqueOrThrowArgs} args - Arguments to find a DegreePlan
   * @example
   * // Get one DegreePlan
   * const degreePlan = await prisma.degreePlan.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DegreePlanFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DegreePlanFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DegreePlanClient<runtime.Types.Result.GetResult<Prisma.$DegreePlanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DegreePlan that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DegreePlanFindFirstArgs} args - Arguments to find a DegreePlan
   * @example
   * // Get one DegreePlan
   * const degreePlan = await prisma.degreePlan.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DegreePlanFindFirstArgs>(args?: Prisma.SelectSubset<T, DegreePlanFindFirstArgs<ExtArgs>>): Prisma.Prisma__DegreePlanClient<runtime.Types.Result.GetResult<Prisma.$DegreePlanPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DegreePlan that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DegreePlanFindFirstOrThrowArgs} args - Arguments to find a DegreePlan
   * @example
   * // Get one DegreePlan
   * const degreePlan = await prisma.degreePlan.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DegreePlanFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DegreePlanFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DegreePlanClient<runtime.Types.Result.GetResult<Prisma.$DegreePlanPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DegreePlans that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DegreePlanFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DegreePlans
   * const degreePlans = await prisma.degreePlan.findMany()
   * 
   * // Get first 10 DegreePlans
   * const degreePlans = await prisma.degreePlan.findMany({ take: 10 })
   * 
   * // Only select the `idDegree`
   * const degreePlanWithIdDegreeOnly = await prisma.degreePlan.findMany({ select: { idDegree: true } })
   * 
   */
  findMany<T extends DegreePlanFindManyArgs>(args?: Prisma.SelectSubset<T, DegreePlanFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DegreePlanPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DegreePlan.
   * @param {DegreePlanCreateArgs} args - Arguments to create a DegreePlan.
   * @example
   * // Create one DegreePlan
   * const DegreePlan = await prisma.degreePlan.create({
   *   data: {
   *     // ... data to create a DegreePlan
   *   }
   * })
   * 
   */
  create<T extends DegreePlanCreateArgs>(args: Prisma.SelectSubset<T, DegreePlanCreateArgs<ExtArgs>>): Prisma.Prisma__DegreePlanClient<runtime.Types.Result.GetResult<Prisma.$DegreePlanPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DegreePlans.
   * @param {DegreePlanCreateManyArgs} args - Arguments to create many DegreePlans.
   * @example
   * // Create many DegreePlans
   * const degreePlan = await prisma.degreePlan.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DegreePlanCreateManyArgs>(args?: Prisma.SelectSubset<T, DegreePlanCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DegreePlans and returns the data saved in the database.
   * @param {DegreePlanCreateManyAndReturnArgs} args - Arguments to create many DegreePlans.
   * @example
   * // Create many DegreePlans
   * const degreePlan = await prisma.degreePlan.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DegreePlans and only return the `idDegree`
   * const degreePlanWithIdDegreeOnly = await prisma.degreePlan.createManyAndReturn({
   *   select: { idDegree: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DegreePlanCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DegreePlanCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DegreePlanPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DegreePlan.
   * @param {DegreePlanDeleteArgs} args - Arguments to delete one DegreePlan.
   * @example
   * // Delete one DegreePlan
   * const DegreePlan = await prisma.degreePlan.delete({
   *   where: {
   *     // ... filter to delete one DegreePlan
   *   }
   * })
   * 
   */
  delete<T extends DegreePlanDeleteArgs>(args: Prisma.SelectSubset<T, DegreePlanDeleteArgs<ExtArgs>>): Prisma.Prisma__DegreePlanClient<runtime.Types.Result.GetResult<Prisma.$DegreePlanPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DegreePlan.
   * @param {DegreePlanUpdateArgs} args - Arguments to update one DegreePlan.
   * @example
   * // Update one DegreePlan
   * const degreePlan = await prisma.degreePlan.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DegreePlanUpdateArgs>(args: Prisma.SelectSubset<T, DegreePlanUpdateArgs<ExtArgs>>): Prisma.Prisma__DegreePlanClient<runtime.Types.Result.GetResult<Prisma.$DegreePlanPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DegreePlans.
   * @param {DegreePlanDeleteManyArgs} args - Arguments to filter DegreePlans to delete.
   * @example
   * // Delete a few DegreePlans
   * const { count } = await prisma.degreePlan.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DegreePlanDeleteManyArgs>(args?: Prisma.SelectSubset<T, DegreePlanDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DegreePlans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DegreePlanUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DegreePlans
   * const degreePlan = await prisma.degreePlan.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DegreePlanUpdateManyArgs>(args: Prisma.SelectSubset<T, DegreePlanUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DegreePlans and returns the data updated in the database.
   * @param {DegreePlanUpdateManyAndReturnArgs} args - Arguments to update many DegreePlans.
   * @example
   * // Update many DegreePlans
   * const degreePlan = await prisma.degreePlan.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DegreePlans and only return the `idDegree`
   * const degreePlanWithIdDegreeOnly = await prisma.degreePlan.updateManyAndReturn({
   *   select: { idDegree: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DegreePlanUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DegreePlanUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DegreePlanPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DegreePlan.
   * @param {DegreePlanUpsertArgs} args - Arguments to update or create a DegreePlan.
   * @example
   * // Update or create a DegreePlan
   * const degreePlan = await prisma.degreePlan.upsert({
   *   create: {
   *     // ... data to create a DegreePlan
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DegreePlan we want to update
   *   }
   * })
   */
  upsert<T extends DegreePlanUpsertArgs>(args: Prisma.SelectSubset<T, DegreePlanUpsertArgs<ExtArgs>>): Prisma.Prisma__DegreePlanClient<runtime.Types.Result.GetResult<Prisma.$DegreePlanPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DegreePlans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DegreePlanCountArgs} args - Arguments to filter DegreePlans to count.
   * @example
   * // Count the number of DegreePlans
   * const count = await prisma.degreePlan.count({
   *   where: {
   *     // ... the filter for the DegreePlans we want to count
   *   }
   * })
  **/
  count<T extends DegreePlanCountArgs>(
    args?: Prisma.Subset<T, DegreePlanCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DegreePlanCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DegreePlan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DegreePlanAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DegreePlanAggregateArgs>(args: Prisma.Subset<T, DegreePlanAggregateArgs>): Prisma.PrismaPromise<GetDegreePlanAggregateType<T>>

  /**
   * Group by DegreePlan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DegreePlanGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DegreePlanGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DegreePlanGroupByArgs['orderBy'] }
      : { orderBy?: DegreePlanGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DegreePlanGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDegreePlanGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DegreePlan model
 */
readonly fields: DegreePlanFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DegreePlan.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DegreePlanClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  degrees<T extends Prisma.DegreeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DegreeDefaultArgs<ExtArgs>>): Prisma.Prisma__DegreeClient<runtime.Types.Result.GetResult<Prisma.$DegreePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  plans<T extends Prisma.PlanDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PlanDefaultArgs<ExtArgs>>): Prisma.Prisma__PlanClient<runtime.Types.Result.GetResult<Prisma.$PlanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DegreePlan model
 */
export interface DegreePlanFieldRefs {
  readonly idDegree: Prisma.FieldRef<"DegreePlan", 'String'>
  readonly idPlan: Prisma.FieldRef<"DegreePlan", 'String'>
  readonly createdAt: Prisma.FieldRef<"DegreePlan", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DegreePlan", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DegreePlan findUnique
 */
export type DegreePlanFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DegreePlan
   */
  select?: Prisma.DegreePlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DegreePlan
   */
  omit?: Prisma.DegreePlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DegreePlanInclude<ExtArgs> | null
  /**
   * Filter, which DegreePlan to fetch.
   */
  where: Prisma.DegreePlanWhereUniqueInput
}

/**
 * DegreePlan findUniqueOrThrow
 */
export type DegreePlanFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DegreePlan
   */
  select?: Prisma.DegreePlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DegreePlan
   */
  omit?: Prisma.DegreePlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DegreePlanInclude<ExtArgs> | null
  /**
   * Filter, which DegreePlan to fetch.
   */
  where: Prisma.DegreePlanWhereUniqueInput
}

/**
 * DegreePlan findFirst
 */
export type DegreePlanFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DegreePlan
   */
  select?: Prisma.DegreePlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DegreePlan
   */
  omit?: Prisma.DegreePlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DegreePlanInclude<ExtArgs> | null
  /**
   * Filter, which DegreePlan to fetch.
   */
  where?: Prisma.DegreePlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DegreePlans to fetch.
   */
  orderBy?: Prisma.DegreePlanOrderByWithRelationInput | Prisma.DegreePlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DegreePlans.
   */
  cursor?: Prisma.DegreePlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DegreePlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DegreePlans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DegreePlans.
   */
  distinct?: Prisma.DegreePlanScalarFieldEnum | Prisma.DegreePlanScalarFieldEnum[]
}

/**
 * DegreePlan findFirstOrThrow
 */
export type DegreePlanFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DegreePlan
   */
  select?: Prisma.DegreePlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DegreePlan
   */
  omit?: Prisma.DegreePlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DegreePlanInclude<ExtArgs> | null
  /**
   * Filter, which DegreePlan to fetch.
   */
  where?: Prisma.DegreePlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DegreePlans to fetch.
   */
  orderBy?: Prisma.DegreePlanOrderByWithRelationInput | Prisma.DegreePlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DegreePlans.
   */
  cursor?: Prisma.DegreePlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DegreePlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DegreePlans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DegreePlans.
   */
  distinct?: Prisma.DegreePlanScalarFieldEnum | Prisma.DegreePlanScalarFieldEnum[]
}

/**
 * DegreePlan findMany
 */
export type DegreePlanFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DegreePlan
   */
  select?: Prisma.DegreePlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DegreePlan
   */
  omit?: Prisma.DegreePlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DegreePlanInclude<ExtArgs> | null
  /**
   * Filter, which DegreePlans to fetch.
   */
  where?: Prisma.DegreePlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DegreePlans to fetch.
   */
  orderBy?: Prisma.DegreePlanOrderByWithRelationInput | Prisma.DegreePlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DegreePlans.
   */
  cursor?: Prisma.DegreePlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DegreePlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DegreePlans.
   */
  skip?: number
  distinct?: Prisma.DegreePlanScalarFieldEnum | Prisma.DegreePlanScalarFieldEnum[]
}

/**
 * DegreePlan create
 */
export type DegreePlanCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DegreePlan
   */
  select?: Prisma.DegreePlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DegreePlan
   */
  omit?: Prisma.DegreePlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DegreePlanInclude<ExtArgs> | null
  /**
   * The data needed to create a DegreePlan.
   */
  data: Prisma.XOR<Prisma.DegreePlanCreateInput, Prisma.DegreePlanUncheckedCreateInput>
}

/**
 * DegreePlan createMany
 */
export type DegreePlanCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DegreePlans.
   */
  data: Prisma.DegreePlanCreateManyInput | Prisma.DegreePlanCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DegreePlan createManyAndReturn
 */
export type DegreePlanCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DegreePlan
   */
  select?: Prisma.DegreePlanSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DegreePlan
   */
  omit?: Prisma.DegreePlanOmit<ExtArgs> | null
  /**
   * The data used to create many DegreePlans.
   */
  data: Prisma.DegreePlanCreateManyInput | Prisma.DegreePlanCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DegreePlanIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DegreePlan update
 */
export type DegreePlanUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DegreePlan
   */
  select?: Prisma.DegreePlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DegreePlan
   */
  omit?: Prisma.DegreePlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DegreePlanInclude<ExtArgs> | null
  /**
   * The data needed to update a DegreePlan.
   */
  data: Prisma.XOR<Prisma.DegreePlanUpdateInput, Prisma.DegreePlanUncheckedUpdateInput>
  /**
   * Choose, which DegreePlan to update.
   */
  where: Prisma.DegreePlanWhereUniqueInput
}

/**
 * DegreePlan updateMany
 */
export type DegreePlanUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DegreePlans.
   */
  data: Prisma.XOR<Prisma.DegreePlanUpdateManyMutationInput, Prisma.DegreePlanUncheckedUpdateManyInput>
  /**
   * Filter which DegreePlans to update
   */
  where?: Prisma.DegreePlanWhereInput
  /**
   * Limit how many DegreePlans to update.
   */
  limit?: number
}

/**
 * DegreePlan updateManyAndReturn
 */
export type DegreePlanUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DegreePlan
   */
  select?: Prisma.DegreePlanSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DegreePlan
   */
  omit?: Prisma.DegreePlanOmit<ExtArgs> | null
  /**
   * The data used to update DegreePlans.
   */
  data: Prisma.XOR<Prisma.DegreePlanUpdateManyMutationInput, Prisma.DegreePlanUncheckedUpdateManyInput>
  /**
   * Filter which DegreePlans to update
   */
  where?: Prisma.DegreePlanWhereInput
  /**
   * Limit how many DegreePlans to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DegreePlanIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DegreePlan upsert
 */
export type DegreePlanUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DegreePlan
   */
  select?: Prisma.DegreePlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DegreePlan
   */
  omit?: Prisma.DegreePlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DegreePlanInclude<ExtArgs> | null
  /**
   * The filter to search for the DegreePlan to update in case it exists.
   */
  where: Prisma.DegreePlanWhereUniqueInput
  /**
   * In case the DegreePlan found by the `where` argument doesn't exist, create a new DegreePlan with this data.
   */
  create: Prisma.XOR<Prisma.DegreePlanCreateInput, Prisma.DegreePlanUncheckedCreateInput>
  /**
   * In case the DegreePlan was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DegreePlanUpdateInput, Prisma.DegreePlanUncheckedUpdateInput>
}

/**
 * DegreePlan delete
 */
export type DegreePlanDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DegreePlan
   */
  select?: Prisma.DegreePlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DegreePlan
   */
  omit?: Prisma.DegreePlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DegreePlanInclude<ExtArgs> | null
  /**
   * Filter which DegreePlan to delete.
   */
  where: Prisma.DegreePlanWhereUniqueInput
}

/**
 * DegreePlan deleteMany
 */
export type DegreePlanDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DegreePlans to delete
   */
  where?: Prisma.DegreePlanWhereInput
  /**
   * Limit how many DegreePlans to delete.
   */
  limit?: number
}

/**
 * DegreePlan without action
 */
export type DegreePlanDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DegreePlan
   */
  select?: Prisma.DegreePlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DegreePlan
   */
  omit?: Prisma.DegreePlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DegreePlanInclude<ExtArgs> | null
}
