
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Midterm` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Midterm
 * 
 */
export type MidtermModel = runtime.Types.Result.DefaultSelection<Prisma.$MidtermPayload>

export type AggregateMidterm = {
  _count: MidtermCountAggregateOutputType | null
  _min: MidtermMinAggregateOutputType | null
  _max: MidtermMaxAggregateOutputType | null
}

export type MidtermMinAggregateOutputType = {
  id: string | null
  idCourse: string | null
  idUser: string | null
  name: string | null
  date: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MidtermMaxAggregateOutputType = {
  id: string | null
  idCourse: string | null
  idUser: string | null
  name: string | null
  date: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MidtermCountAggregateOutputType = {
  id: number
  idCourse: number
  idUser: number
  name: number
  date: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MidtermMinAggregateInputType = {
  id?: true
  idCourse?: true
  idUser?: true
  name?: true
  date?: true
  createdAt?: true
  updatedAt?: true
}

export type MidtermMaxAggregateInputType = {
  id?: true
  idCourse?: true
  idUser?: true
  name?: true
  date?: true
  createdAt?: true
  updatedAt?: true
}

export type MidtermCountAggregateInputType = {
  id?: true
  idCourse?: true
  idUser?: true
  name?: true
  date?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MidtermAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Midterm to aggregate.
   */
  where?: Prisma.MidtermWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Midterms to fetch.
   */
  orderBy?: Prisma.MidtermOrderByWithRelationInput | Prisma.MidtermOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MidtermWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Midterms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Midterms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Midterms
  **/
  _count?: true | MidtermCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MidtermMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MidtermMaxAggregateInputType
}

export type GetMidtermAggregateType<T extends MidtermAggregateArgs> = {
      [P in keyof T & keyof AggregateMidterm]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMidterm[P]>
    : Prisma.GetScalarType<T[P], AggregateMidterm[P]>
}




export type MidtermGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MidtermWhereInput
  orderBy?: Prisma.MidtermOrderByWithAggregationInput | Prisma.MidtermOrderByWithAggregationInput[]
  by: Prisma.MidtermScalarFieldEnum[] | Prisma.MidtermScalarFieldEnum
  having?: Prisma.MidtermScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MidtermCountAggregateInputType | true
  _min?: MidtermMinAggregateInputType
  _max?: MidtermMaxAggregateInputType
}

export type MidtermGroupByOutputType = {
  id: string
  idCourse: string
  idUser: string
  name: string
  date: Date
  createdAt: Date
  updatedAt: Date
  _count: MidtermCountAggregateOutputType | null
  _min: MidtermMinAggregateOutputType | null
  _max: MidtermMaxAggregateOutputType | null
}

type GetMidtermGroupByPayload<T extends MidtermGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MidtermGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MidtermGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MidtermGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MidtermGroupByOutputType[P]>
      }
    >
  >



export type MidtermWhereInput = {
  AND?: Prisma.MidtermWhereInput | Prisma.MidtermWhereInput[]
  OR?: Prisma.MidtermWhereInput[]
  NOT?: Prisma.MidtermWhereInput | Prisma.MidtermWhereInput[]
  id?: Prisma.StringFilter<"Midterm"> | string
  idCourse?: Prisma.StringFilter<"Midterm"> | string
  idUser?: Prisma.StringFilter<"Midterm"> | string
  name?: Prisma.StringFilter<"Midterm"> | string
  date?: Prisma.DateTimeFilter<"Midterm"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Midterm"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Midterm"> | Date | string
  responses?: Prisma.ResponseListRelationFilter
  courses?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
  users?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type MidtermOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  idCourse?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  name?: Prisma.SortOrder
  date?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  responses?: Prisma.ResponseOrderByRelationAggregateInput
  courses?: Prisma.CourseOrderByWithRelationInput
  users?: Prisma.UserOrderByWithRelationInput
}

export type MidtermWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MidtermWhereInput | Prisma.MidtermWhereInput[]
  OR?: Prisma.MidtermWhereInput[]
  NOT?: Prisma.MidtermWhereInput | Prisma.MidtermWhereInput[]
  idCourse?: Prisma.StringFilter<"Midterm"> | string
  idUser?: Prisma.StringFilter<"Midterm"> | string
  name?: Prisma.StringFilter<"Midterm"> | string
  date?: Prisma.DateTimeFilter<"Midterm"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Midterm"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Midterm"> | Date | string
  responses?: Prisma.ResponseListRelationFilter
  courses?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
  users?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type MidtermOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  idCourse?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  name?: Prisma.SortOrder
  date?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MidtermCountOrderByAggregateInput
  _max?: Prisma.MidtermMaxOrderByAggregateInput
  _min?: Prisma.MidtermMinOrderByAggregateInput
}

export type MidtermScalarWhereWithAggregatesInput = {
  AND?: Prisma.MidtermScalarWhereWithAggregatesInput | Prisma.MidtermScalarWhereWithAggregatesInput[]
  OR?: Prisma.MidtermScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MidtermScalarWhereWithAggregatesInput | Prisma.MidtermScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Midterm"> | string
  idCourse?: Prisma.StringWithAggregatesFilter<"Midterm"> | string
  idUser?: Prisma.StringWithAggregatesFilter<"Midterm"> | string
  name?: Prisma.StringWithAggregatesFilter<"Midterm"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"Midterm"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Midterm"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Midterm"> | Date | string
}

export type MidtermCreateInput = {
  id?: string
  name: string
  date: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.ResponseCreateNestedManyWithoutMidtermInput
  courses: Prisma.CourseCreateNestedOneWithoutMidtermsInput
  users: Prisma.UserCreateNestedOneWithoutMidtermsInput
}

export type MidtermUncheckedCreateInput = {
  id?: string
  idCourse: string
  idUser: string
  name: string
  date: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.ResponseUncheckedCreateNestedManyWithoutMidtermInput
}

export type MidtermUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.ResponseUpdateManyWithoutMidtermNestedInput
  courses?: Prisma.CourseUpdateOneRequiredWithoutMidtermsNestedInput
  users?: Prisma.UserUpdateOneRequiredWithoutMidtermsNestedInput
}

export type MidtermUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idCourse?: Prisma.StringFieldUpdateOperationsInput | string
  idUser?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.ResponseUncheckedUpdateManyWithoutMidtermNestedInput
}

export type MidtermCreateManyInput = {
  id?: string
  idCourse: string
  idUser: string
  name: string
  date: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MidtermUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MidtermUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idCourse?: Prisma.StringFieldUpdateOperationsInput | string
  idUser?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MidtermListRelationFilter = {
  every?: Prisma.MidtermWhereInput
  some?: Prisma.MidtermWhereInput
  none?: Prisma.MidtermWhereInput
}

export type MidtermOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MidtermCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  idCourse?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  name?: Prisma.SortOrder
  date?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MidtermMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  idCourse?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  name?: Prisma.SortOrder
  date?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MidtermMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  idCourse?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  name?: Prisma.SortOrder
  date?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MidtermNullableScalarRelationFilter = {
  is?: Prisma.MidtermWhereInput | null
  isNot?: Prisma.MidtermWhereInput | null
}

export type MidtermCreateNestedManyWithoutCoursesInput = {
  create?: Prisma.XOR<Prisma.MidtermCreateWithoutCoursesInput, Prisma.MidtermUncheckedCreateWithoutCoursesInput> | Prisma.MidtermCreateWithoutCoursesInput[] | Prisma.MidtermUncheckedCreateWithoutCoursesInput[]
  connectOrCreate?: Prisma.MidtermCreateOrConnectWithoutCoursesInput | Prisma.MidtermCreateOrConnectWithoutCoursesInput[]
  createMany?: Prisma.MidtermCreateManyCoursesInputEnvelope
  connect?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
}

export type MidtermUncheckedCreateNestedManyWithoutCoursesInput = {
  create?: Prisma.XOR<Prisma.MidtermCreateWithoutCoursesInput, Prisma.MidtermUncheckedCreateWithoutCoursesInput> | Prisma.MidtermCreateWithoutCoursesInput[] | Prisma.MidtermUncheckedCreateWithoutCoursesInput[]
  connectOrCreate?: Prisma.MidtermCreateOrConnectWithoutCoursesInput | Prisma.MidtermCreateOrConnectWithoutCoursesInput[]
  createMany?: Prisma.MidtermCreateManyCoursesInputEnvelope
  connect?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
}

export type MidtermUpdateManyWithoutCoursesNestedInput = {
  create?: Prisma.XOR<Prisma.MidtermCreateWithoutCoursesInput, Prisma.MidtermUncheckedCreateWithoutCoursesInput> | Prisma.MidtermCreateWithoutCoursesInput[] | Prisma.MidtermUncheckedCreateWithoutCoursesInput[]
  connectOrCreate?: Prisma.MidtermCreateOrConnectWithoutCoursesInput | Prisma.MidtermCreateOrConnectWithoutCoursesInput[]
  upsert?: Prisma.MidtermUpsertWithWhereUniqueWithoutCoursesInput | Prisma.MidtermUpsertWithWhereUniqueWithoutCoursesInput[]
  createMany?: Prisma.MidtermCreateManyCoursesInputEnvelope
  set?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  disconnect?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  delete?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  connect?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  update?: Prisma.MidtermUpdateWithWhereUniqueWithoutCoursesInput | Prisma.MidtermUpdateWithWhereUniqueWithoutCoursesInput[]
  updateMany?: Prisma.MidtermUpdateManyWithWhereWithoutCoursesInput | Prisma.MidtermUpdateManyWithWhereWithoutCoursesInput[]
  deleteMany?: Prisma.MidtermScalarWhereInput | Prisma.MidtermScalarWhereInput[]
}

export type MidtermUncheckedUpdateManyWithoutCoursesNestedInput = {
  create?: Prisma.XOR<Prisma.MidtermCreateWithoutCoursesInput, Prisma.MidtermUncheckedCreateWithoutCoursesInput> | Prisma.MidtermCreateWithoutCoursesInput[] | Prisma.MidtermUncheckedCreateWithoutCoursesInput[]
  connectOrCreate?: Prisma.MidtermCreateOrConnectWithoutCoursesInput | Prisma.MidtermCreateOrConnectWithoutCoursesInput[]
  upsert?: Prisma.MidtermUpsertWithWhereUniqueWithoutCoursesInput | Prisma.MidtermUpsertWithWhereUniqueWithoutCoursesInput[]
  createMany?: Prisma.MidtermCreateManyCoursesInputEnvelope
  set?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  disconnect?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  delete?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  connect?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  update?: Prisma.MidtermUpdateWithWhereUniqueWithoutCoursesInput | Prisma.MidtermUpdateWithWhereUniqueWithoutCoursesInput[]
  updateMany?: Prisma.MidtermUpdateManyWithWhereWithoutCoursesInput | Prisma.MidtermUpdateManyWithWhereWithoutCoursesInput[]
  deleteMany?: Prisma.MidtermScalarWhereInput | Prisma.MidtermScalarWhereInput[]
}

export type MidtermCreateNestedOneWithoutResponsesInput = {
  create?: Prisma.XOR<Prisma.MidtermCreateWithoutResponsesInput, Prisma.MidtermUncheckedCreateWithoutResponsesInput>
  connectOrCreate?: Prisma.MidtermCreateOrConnectWithoutResponsesInput
  connect?: Prisma.MidtermWhereUniqueInput
}

export type MidtermUpdateOneWithoutResponsesNestedInput = {
  create?: Prisma.XOR<Prisma.MidtermCreateWithoutResponsesInput, Prisma.MidtermUncheckedCreateWithoutResponsesInput>
  connectOrCreate?: Prisma.MidtermCreateOrConnectWithoutResponsesInput
  upsert?: Prisma.MidtermUpsertWithoutResponsesInput
  disconnect?: Prisma.MidtermWhereInput | boolean
  delete?: Prisma.MidtermWhereInput | boolean
  connect?: Prisma.MidtermWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MidtermUpdateToOneWithWhereWithoutResponsesInput, Prisma.MidtermUpdateWithoutResponsesInput>, Prisma.MidtermUncheckedUpdateWithoutResponsesInput>
}

export type MidtermCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.MidtermCreateWithoutUsersInput, Prisma.MidtermUncheckedCreateWithoutUsersInput> | Prisma.MidtermCreateWithoutUsersInput[] | Prisma.MidtermUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.MidtermCreateOrConnectWithoutUsersInput | Prisma.MidtermCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.MidtermCreateManyUsersInputEnvelope
  connect?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
}

export type MidtermUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.MidtermCreateWithoutUsersInput, Prisma.MidtermUncheckedCreateWithoutUsersInput> | Prisma.MidtermCreateWithoutUsersInput[] | Prisma.MidtermUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.MidtermCreateOrConnectWithoutUsersInput | Prisma.MidtermCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.MidtermCreateManyUsersInputEnvelope
  connect?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
}

export type MidtermUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.MidtermCreateWithoutUsersInput, Prisma.MidtermUncheckedCreateWithoutUsersInput> | Prisma.MidtermCreateWithoutUsersInput[] | Prisma.MidtermUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.MidtermCreateOrConnectWithoutUsersInput | Prisma.MidtermCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.MidtermUpsertWithWhereUniqueWithoutUsersInput | Prisma.MidtermUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.MidtermCreateManyUsersInputEnvelope
  set?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  disconnect?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  delete?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  connect?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  update?: Prisma.MidtermUpdateWithWhereUniqueWithoutUsersInput | Prisma.MidtermUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.MidtermUpdateManyWithWhereWithoutUsersInput | Prisma.MidtermUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.MidtermScalarWhereInput | Prisma.MidtermScalarWhereInput[]
}

export type MidtermUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.MidtermCreateWithoutUsersInput, Prisma.MidtermUncheckedCreateWithoutUsersInput> | Prisma.MidtermCreateWithoutUsersInput[] | Prisma.MidtermUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.MidtermCreateOrConnectWithoutUsersInput | Prisma.MidtermCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.MidtermUpsertWithWhereUniqueWithoutUsersInput | Prisma.MidtermUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.MidtermCreateManyUsersInputEnvelope
  set?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  disconnect?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  delete?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  connect?: Prisma.MidtermWhereUniqueInput | Prisma.MidtermWhereUniqueInput[]
  update?: Prisma.MidtermUpdateWithWhereUniqueWithoutUsersInput | Prisma.MidtermUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.MidtermUpdateManyWithWhereWithoutUsersInput | Prisma.MidtermUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.MidtermScalarWhereInput | Prisma.MidtermScalarWhereInput[]
}

export type MidtermCreateWithoutCoursesInput = {
  id?: string
  name: string
  date: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.ResponseCreateNestedManyWithoutMidtermInput
  users: Prisma.UserCreateNestedOneWithoutMidtermsInput
}

export type MidtermUncheckedCreateWithoutCoursesInput = {
  id?: string
  idUser: string
  name: string
  date: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.ResponseUncheckedCreateNestedManyWithoutMidtermInput
}

export type MidtermCreateOrConnectWithoutCoursesInput = {
  where: Prisma.MidtermWhereUniqueInput
  create: Prisma.XOR<Prisma.MidtermCreateWithoutCoursesInput, Prisma.MidtermUncheckedCreateWithoutCoursesInput>
}

export type MidtermCreateManyCoursesInputEnvelope = {
  data: Prisma.MidtermCreateManyCoursesInput | Prisma.MidtermCreateManyCoursesInput[]
  skipDuplicates?: boolean
}

export type MidtermUpsertWithWhereUniqueWithoutCoursesInput = {
  where: Prisma.MidtermWhereUniqueInput
  update: Prisma.XOR<Prisma.MidtermUpdateWithoutCoursesInput, Prisma.MidtermUncheckedUpdateWithoutCoursesInput>
  create: Prisma.XOR<Prisma.MidtermCreateWithoutCoursesInput, Prisma.MidtermUncheckedCreateWithoutCoursesInput>
}

export type MidtermUpdateWithWhereUniqueWithoutCoursesInput = {
  where: Prisma.MidtermWhereUniqueInput
  data: Prisma.XOR<Prisma.MidtermUpdateWithoutCoursesInput, Prisma.MidtermUncheckedUpdateWithoutCoursesInput>
}

export type MidtermUpdateManyWithWhereWithoutCoursesInput = {
  where: Prisma.MidtermScalarWhereInput
  data: Prisma.XOR<Prisma.MidtermUpdateManyMutationInput, Prisma.MidtermUncheckedUpdateManyWithoutCoursesInput>
}

export type MidtermScalarWhereInput = {
  AND?: Prisma.MidtermScalarWhereInput | Prisma.MidtermScalarWhereInput[]
  OR?: Prisma.MidtermScalarWhereInput[]
  NOT?: Prisma.MidtermScalarWhereInput | Prisma.MidtermScalarWhereInput[]
  id?: Prisma.StringFilter<"Midterm"> | string
  idCourse?: Prisma.StringFilter<"Midterm"> | string
  idUser?: Prisma.StringFilter<"Midterm"> | string
  name?: Prisma.StringFilter<"Midterm"> | string
  date?: Prisma.DateTimeFilter<"Midterm"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Midterm"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Midterm"> | Date | string
}

export type MidtermCreateWithoutResponsesInput = {
  id?: string
  name: string
  date: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  courses: Prisma.CourseCreateNestedOneWithoutMidtermsInput
  users: Prisma.UserCreateNestedOneWithoutMidtermsInput
}

export type MidtermUncheckedCreateWithoutResponsesInput = {
  id?: string
  idCourse: string
  idUser: string
  name: string
  date: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MidtermCreateOrConnectWithoutResponsesInput = {
  where: Prisma.MidtermWhereUniqueInput
  create: Prisma.XOR<Prisma.MidtermCreateWithoutResponsesInput, Prisma.MidtermUncheckedCreateWithoutResponsesInput>
}

export type MidtermUpsertWithoutResponsesInput = {
  update: Prisma.XOR<Prisma.MidtermUpdateWithoutResponsesInput, Prisma.MidtermUncheckedUpdateWithoutResponsesInput>
  create: Prisma.XOR<Prisma.MidtermCreateWithoutResponsesInput, Prisma.MidtermUncheckedCreateWithoutResponsesInput>
  where?: Prisma.MidtermWhereInput
}

export type MidtermUpdateToOneWithWhereWithoutResponsesInput = {
  where?: Prisma.MidtermWhereInput
  data: Prisma.XOR<Prisma.MidtermUpdateWithoutResponsesInput, Prisma.MidtermUncheckedUpdateWithoutResponsesInput>
}

export type MidtermUpdateWithoutResponsesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courses?: Prisma.CourseUpdateOneRequiredWithoutMidtermsNestedInput
  users?: Prisma.UserUpdateOneRequiredWithoutMidtermsNestedInput
}

export type MidtermUncheckedUpdateWithoutResponsesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idCourse?: Prisma.StringFieldUpdateOperationsInput | string
  idUser?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MidtermCreateWithoutUsersInput = {
  id?: string
  name: string
  date: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.ResponseCreateNestedManyWithoutMidtermInput
  courses: Prisma.CourseCreateNestedOneWithoutMidtermsInput
}

export type MidtermUncheckedCreateWithoutUsersInput = {
  id?: string
  idCourse: string
  name: string
  date: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.ResponseUncheckedCreateNestedManyWithoutMidtermInput
}

export type MidtermCreateOrConnectWithoutUsersInput = {
  where: Prisma.MidtermWhereUniqueInput
  create: Prisma.XOR<Prisma.MidtermCreateWithoutUsersInput, Prisma.MidtermUncheckedCreateWithoutUsersInput>
}

export type MidtermCreateManyUsersInputEnvelope = {
  data: Prisma.MidtermCreateManyUsersInput | Prisma.MidtermCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type MidtermUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.MidtermWhereUniqueInput
  update: Prisma.XOR<Prisma.MidtermUpdateWithoutUsersInput, Prisma.MidtermUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.MidtermCreateWithoutUsersInput, Prisma.MidtermUncheckedCreateWithoutUsersInput>
}

export type MidtermUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.MidtermWhereUniqueInput
  data: Prisma.XOR<Prisma.MidtermUpdateWithoutUsersInput, Prisma.MidtermUncheckedUpdateWithoutUsersInput>
}

export type MidtermUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.MidtermScalarWhereInput
  data: Prisma.XOR<Prisma.MidtermUpdateManyMutationInput, Prisma.MidtermUncheckedUpdateManyWithoutUsersInput>
}

export type MidtermCreateManyCoursesInput = {
  id?: string
  idUser: string
  name: string
  date: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MidtermUpdateWithoutCoursesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.ResponseUpdateManyWithoutMidtermNestedInput
  users?: Prisma.UserUpdateOneRequiredWithoutMidtermsNestedInput
}

export type MidtermUncheckedUpdateWithoutCoursesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idUser?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.ResponseUncheckedUpdateManyWithoutMidtermNestedInput
}

export type MidtermUncheckedUpdateManyWithoutCoursesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idUser?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MidtermCreateManyUsersInput = {
  id?: string
  idCourse: string
  name: string
  date: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MidtermUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.ResponseUpdateManyWithoutMidtermNestedInput
  courses?: Prisma.CourseUpdateOneRequiredWithoutMidtermsNestedInput
}

export type MidtermUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idCourse?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.ResponseUncheckedUpdateManyWithoutMidtermNestedInput
}

export type MidtermUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idCourse?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type MidtermCountOutputType
 */

export type MidtermCountOutputType = {
  responses: number
}

export type MidtermCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  responses?: boolean | MidtermCountOutputTypeCountResponsesArgs
}

/**
 * MidtermCountOutputType without action
 */
export type MidtermCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MidtermCountOutputType
   */
  select?: Prisma.MidtermCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MidtermCountOutputType without action
 */
export type MidtermCountOutputTypeCountResponsesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ResponseWhereInput
}


export type MidtermSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  idCourse?: boolean
  idUser?: boolean
  name?: boolean
  date?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  responses?: boolean | Prisma.Midterm$responsesArgs<ExtArgs>
  courses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.MidtermCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["midterm"]>

export type MidtermSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  idCourse?: boolean
  idUser?: boolean
  name?: boolean
  date?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  courses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["midterm"]>

export type MidtermSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  idCourse?: boolean
  idUser?: boolean
  name?: boolean
  date?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  courses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["midterm"]>

export type MidtermSelectScalar = {
  id?: boolean
  idCourse?: boolean
  idUser?: boolean
  name?: boolean
  date?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MidtermOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "idCourse" | "idUser" | "name" | "date" | "createdAt" | "updatedAt", ExtArgs["result"]["midterm"]>
export type MidtermInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  responses?: boolean | Prisma.Midterm$responsesArgs<ExtArgs>
  courses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.MidtermCountOutputTypeDefaultArgs<ExtArgs>
}
export type MidtermIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  courses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type MidtermIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  courses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $MidtermPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Midterm"
  objects: {
    responses: Prisma.$ResponsePayload<ExtArgs>[]
    courses: Prisma.$CoursePayload<ExtArgs>
    users: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    idCourse: string
    idUser: string
    name: string
    date: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["midterm"]>
  composites: {}
}

export type MidtermGetPayload<S extends boolean | null | undefined | MidtermDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MidtermPayload, S>

export type MidtermCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MidtermFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MidtermCountAggregateInputType | true
  }

export interface MidtermDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Midterm'], meta: { name: 'Midterm' } }
  /**
   * Find zero or one Midterm that matches the filter.
   * @param {MidtermFindUniqueArgs} args - Arguments to find a Midterm
   * @example
   * // Get one Midterm
   * const midterm = await prisma.midterm.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MidtermFindUniqueArgs>(args: Prisma.SelectSubset<T, MidtermFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MidtermClient<runtime.Types.Result.GetResult<Prisma.$MidtermPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Midterm that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MidtermFindUniqueOrThrowArgs} args - Arguments to find a Midterm
   * @example
   * // Get one Midterm
   * const midterm = await prisma.midterm.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MidtermFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MidtermFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MidtermClient<runtime.Types.Result.GetResult<Prisma.$MidtermPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Midterm that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MidtermFindFirstArgs} args - Arguments to find a Midterm
   * @example
   * // Get one Midterm
   * const midterm = await prisma.midterm.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MidtermFindFirstArgs>(args?: Prisma.SelectSubset<T, MidtermFindFirstArgs<ExtArgs>>): Prisma.Prisma__MidtermClient<runtime.Types.Result.GetResult<Prisma.$MidtermPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Midterm that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MidtermFindFirstOrThrowArgs} args - Arguments to find a Midterm
   * @example
   * // Get one Midterm
   * const midterm = await prisma.midterm.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MidtermFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MidtermFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MidtermClient<runtime.Types.Result.GetResult<Prisma.$MidtermPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Midterms that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MidtermFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Midterms
   * const midterms = await prisma.midterm.findMany()
   * 
   * // Get first 10 Midterms
   * const midterms = await prisma.midterm.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const midtermWithIdOnly = await prisma.midterm.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MidtermFindManyArgs>(args?: Prisma.SelectSubset<T, MidtermFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MidtermPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Midterm.
   * @param {MidtermCreateArgs} args - Arguments to create a Midterm.
   * @example
   * // Create one Midterm
   * const Midterm = await prisma.midterm.create({
   *   data: {
   *     // ... data to create a Midterm
   *   }
   * })
   * 
   */
  create<T extends MidtermCreateArgs>(args: Prisma.SelectSubset<T, MidtermCreateArgs<ExtArgs>>): Prisma.Prisma__MidtermClient<runtime.Types.Result.GetResult<Prisma.$MidtermPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Midterms.
   * @param {MidtermCreateManyArgs} args - Arguments to create many Midterms.
   * @example
   * // Create many Midterms
   * const midterm = await prisma.midterm.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MidtermCreateManyArgs>(args?: Prisma.SelectSubset<T, MidtermCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Midterms and returns the data saved in the database.
   * @param {MidtermCreateManyAndReturnArgs} args - Arguments to create many Midterms.
   * @example
   * // Create many Midterms
   * const midterm = await prisma.midterm.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Midterms and only return the `id`
   * const midtermWithIdOnly = await prisma.midterm.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MidtermCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MidtermCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MidtermPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Midterm.
   * @param {MidtermDeleteArgs} args - Arguments to delete one Midterm.
   * @example
   * // Delete one Midterm
   * const Midterm = await prisma.midterm.delete({
   *   where: {
   *     // ... filter to delete one Midterm
   *   }
   * })
   * 
   */
  delete<T extends MidtermDeleteArgs>(args: Prisma.SelectSubset<T, MidtermDeleteArgs<ExtArgs>>): Prisma.Prisma__MidtermClient<runtime.Types.Result.GetResult<Prisma.$MidtermPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Midterm.
   * @param {MidtermUpdateArgs} args - Arguments to update one Midterm.
   * @example
   * // Update one Midterm
   * const midterm = await prisma.midterm.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MidtermUpdateArgs>(args: Prisma.SelectSubset<T, MidtermUpdateArgs<ExtArgs>>): Prisma.Prisma__MidtermClient<runtime.Types.Result.GetResult<Prisma.$MidtermPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Midterms.
   * @param {MidtermDeleteManyArgs} args - Arguments to filter Midterms to delete.
   * @example
   * // Delete a few Midterms
   * const { count } = await prisma.midterm.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MidtermDeleteManyArgs>(args?: Prisma.SelectSubset<T, MidtermDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Midterms.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MidtermUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Midterms
   * const midterm = await prisma.midterm.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MidtermUpdateManyArgs>(args: Prisma.SelectSubset<T, MidtermUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Midterms and returns the data updated in the database.
   * @param {MidtermUpdateManyAndReturnArgs} args - Arguments to update many Midterms.
   * @example
   * // Update many Midterms
   * const midterm = await prisma.midterm.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Midterms and only return the `id`
   * const midtermWithIdOnly = await prisma.midterm.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MidtermUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MidtermUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MidtermPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Midterm.
   * @param {MidtermUpsertArgs} args - Arguments to update or create a Midterm.
   * @example
   * // Update or create a Midterm
   * const midterm = await prisma.midterm.upsert({
   *   create: {
   *     // ... data to create a Midterm
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Midterm we want to update
   *   }
   * })
   */
  upsert<T extends MidtermUpsertArgs>(args: Prisma.SelectSubset<T, MidtermUpsertArgs<ExtArgs>>): Prisma.Prisma__MidtermClient<runtime.Types.Result.GetResult<Prisma.$MidtermPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Midterms.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MidtermCountArgs} args - Arguments to filter Midterms to count.
   * @example
   * // Count the number of Midterms
   * const count = await prisma.midterm.count({
   *   where: {
   *     // ... the filter for the Midterms we want to count
   *   }
   * })
  **/
  count<T extends MidtermCountArgs>(
    args?: Prisma.Subset<T, MidtermCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MidtermCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Midterm.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MidtermAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MidtermAggregateArgs>(args: Prisma.Subset<T, MidtermAggregateArgs>): Prisma.PrismaPromise<GetMidtermAggregateType<T>>

  /**
   * Group by Midterm.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MidtermGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MidtermGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MidtermGroupByArgs['orderBy'] }
      : { orderBy?: MidtermGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MidtermGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMidtermGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Midterm model
 */
readonly fields: MidtermFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Midterm.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MidtermClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  responses<T extends Prisma.Midterm$responsesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Midterm$responsesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ResponsePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  courses<T extends Prisma.CourseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CourseDefaultArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Midterm model
 */
export interface MidtermFieldRefs {
  readonly id: Prisma.FieldRef<"Midterm", 'String'>
  readonly idCourse: Prisma.FieldRef<"Midterm", 'String'>
  readonly idUser: Prisma.FieldRef<"Midterm", 'String'>
  readonly name: Prisma.FieldRef<"Midterm", 'String'>
  readonly date: Prisma.FieldRef<"Midterm", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Midterm", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Midterm", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Midterm findUnique
 */
export type MidtermFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Midterm
   */
  select?: Prisma.MidtermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Midterm
   */
  omit?: Prisma.MidtermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MidtermInclude<ExtArgs> | null
  /**
   * Filter, which Midterm to fetch.
   */
  where: Prisma.MidtermWhereUniqueInput
}

/**
 * Midterm findUniqueOrThrow
 */
export type MidtermFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Midterm
   */
  select?: Prisma.MidtermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Midterm
   */
  omit?: Prisma.MidtermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MidtermInclude<ExtArgs> | null
  /**
   * Filter, which Midterm to fetch.
   */
  where: Prisma.MidtermWhereUniqueInput
}

/**
 * Midterm findFirst
 */
export type MidtermFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Midterm
   */
  select?: Prisma.MidtermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Midterm
   */
  omit?: Prisma.MidtermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MidtermInclude<ExtArgs> | null
  /**
   * Filter, which Midterm to fetch.
   */
  where?: Prisma.MidtermWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Midterms to fetch.
   */
  orderBy?: Prisma.MidtermOrderByWithRelationInput | Prisma.MidtermOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Midterms.
   */
  cursor?: Prisma.MidtermWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Midterms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Midterms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Midterms.
   */
  distinct?: Prisma.MidtermScalarFieldEnum | Prisma.MidtermScalarFieldEnum[]
}

/**
 * Midterm findFirstOrThrow
 */
export type MidtermFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Midterm
   */
  select?: Prisma.MidtermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Midterm
   */
  omit?: Prisma.MidtermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MidtermInclude<ExtArgs> | null
  /**
   * Filter, which Midterm to fetch.
   */
  where?: Prisma.MidtermWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Midterms to fetch.
   */
  orderBy?: Prisma.MidtermOrderByWithRelationInput | Prisma.MidtermOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Midterms.
   */
  cursor?: Prisma.MidtermWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Midterms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Midterms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Midterms.
   */
  distinct?: Prisma.MidtermScalarFieldEnum | Prisma.MidtermScalarFieldEnum[]
}

/**
 * Midterm findMany
 */
export type MidtermFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Midterm
   */
  select?: Prisma.MidtermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Midterm
   */
  omit?: Prisma.MidtermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MidtermInclude<ExtArgs> | null
  /**
   * Filter, which Midterms to fetch.
   */
  where?: Prisma.MidtermWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Midterms to fetch.
   */
  orderBy?: Prisma.MidtermOrderByWithRelationInput | Prisma.MidtermOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Midterms.
   */
  cursor?: Prisma.MidtermWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Midterms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Midterms.
   */
  skip?: number
  distinct?: Prisma.MidtermScalarFieldEnum | Prisma.MidtermScalarFieldEnum[]
}

/**
 * Midterm create
 */
export type MidtermCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Midterm
   */
  select?: Prisma.MidtermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Midterm
   */
  omit?: Prisma.MidtermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MidtermInclude<ExtArgs> | null
  /**
   * The data needed to create a Midterm.
   */
  data: Prisma.XOR<Prisma.MidtermCreateInput, Prisma.MidtermUncheckedCreateInput>
}

/**
 * Midterm createMany
 */
export type MidtermCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Midterms.
   */
  data: Prisma.MidtermCreateManyInput | Prisma.MidtermCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Midterm createManyAndReturn
 */
export type MidtermCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Midterm
   */
  select?: Prisma.MidtermSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Midterm
   */
  omit?: Prisma.MidtermOmit<ExtArgs> | null
  /**
   * The data used to create many Midterms.
   */
  data: Prisma.MidtermCreateManyInput | Prisma.MidtermCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MidtermIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Midterm update
 */
export type MidtermUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Midterm
   */
  select?: Prisma.MidtermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Midterm
   */
  omit?: Prisma.MidtermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MidtermInclude<ExtArgs> | null
  /**
   * The data needed to update a Midterm.
   */
  data: Prisma.XOR<Prisma.MidtermUpdateInput, Prisma.MidtermUncheckedUpdateInput>
  /**
   * Choose, which Midterm to update.
   */
  where: Prisma.MidtermWhereUniqueInput
}

/**
 * Midterm updateMany
 */
export type MidtermUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Midterms.
   */
  data: Prisma.XOR<Prisma.MidtermUpdateManyMutationInput, Prisma.MidtermUncheckedUpdateManyInput>
  /**
   * Filter which Midterms to update
   */
  where?: Prisma.MidtermWhereInput
  /**
   * Limit how many Midterms to update.
   */
  limit?: number
}

/**
 * Midterm updateManyAndReturn
 */
export type MidtermUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Midterm
   */
  select?: Prisma.MidtermSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Midterm
   */
  omit?: Prisma.MidtermOmit<ExtArgs> | null
  /**
   * The data used to update Midterms.
   */
  data: Prisma.XOR<Prisma.MidtermUpdateManyMutationInput, Prisma.MidtermUncheckedUpdateManyInput>
  /**
   * Filter which Midterms to update
   */
  where?: Prisma.MidtermWhereInput
  /**
   * Limit how many Midterms to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MidtermIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Midterm upsert
 */
export type MidtermUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Midterm
   */
  select?: Prisma.MidtermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Midterm
   */
  omit?: Prisma.MidtermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MidtermInclude<ExtArgs> | null
  /**
   * The filter to search for the Midterm to update in case it exists.
   */
  where: Prisma.MidtermWhereUniqueInput
  /**
   * In case the Midterm found by the `where` argument doesn't exist, create a new Midterm with this data.
   */
  create: Prisma.XOR<Prisma.MidtermCreateInput, Prisma.MidtermUncheckedCreateInput>
  /**
   * In case the Midterm was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MidtermUpdateInput, Prisma.MidtermUncheckedUpdateInput>
}

/**
 * Midterm delete
 */
export type MidtermDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Midterm
   */
  select?: Prisma.MidtermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Midterm
   */
  omit?: Prisma.MidtermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MidtermInclude<ExtArgs> | null
  /**
   * Filter which Midterm to delete.
   */
  where: Prisma.MidtermWhereUniqueInput
}

/**
 * Midterm deleteMany
 */
export type MidtermDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Midterms to delete
   */
  where?: Prisma.MidtermWhereInput
  /**
   * Limit how many Midterms to delete.
   */
  limit?: number
}

/**
 * Midterm.responses
 */
export type Midterm$responsesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Response
   */
  select?: Prisma.ResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Response
   */
  omit?: Prisma.ResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponseInclude<ExtArgs> | null
  where?: Prisma.ResponseWhereInput
  orderBy?: Prisma.ResponseOrderByWithRelationInput | Prisma.ResponseOrderByWithRelationInput[]
  cursor?: Prisma.ResponseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ResponseScalarFieldEnum | Prisma.ResponseScalarFieldEnum[]
}

/**
 * Midterm without action
 */
export type MidtermDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Midterm
   */
  select?: Prisma.MidtermSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Midterm
   */
  omit?: Prisma.MidtermOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MidtermInclude<ExtArgs> | null
}
