
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Tp` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Tp
 * 
 */
export type TpModel = runtime.Types.Result.DefaultSelection<Prisma.$TpPayload>

export type AggregateTp = {
  _count: TpCountAggregateOutputType | null
  _avg: TpAvgAggregateOutputType | null
  _sum: TpSumAggregateOutputType | null
  _min: TpMinAggregateOutputType | null
  _max: TpMaxAggregateOutputType | null
}

export type TpAvgAggregateOutputType = {
  number: number | null
  year: number | null
}

export type TpSumAggregateOutputType = {
  number: number | null
  year: number | null
}

export type TpMinAggregateOutputType = {
  id: string | null
  idCourse: string | null
  idUser: string | null
  name: string | null
  number: number | null
  year: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TpMaxAggregateOutputType = {
  id: string | null
  idCourse: string | null
  idUser: string | null
  name: string | null
  number: number | null
  year: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TpCountAggregateOutputType = {
  id: number
  idCourse: number
  idUser: number
  name: number
  number: number
  year: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TpAvgAggregateInputType = {
  number?: true
  year?: true
}

export type TpSumAggregateInputType = {
  number?: true
  year?: true
}

export type TpMinAggregateInputType = {
  id?: true
  idCourse?: true
  idUser?: true
  name?: true
  number?: true
  year?: true
  createdAt?: true
  updatedAt?: true
}

export type TpMaxAggregateInputType = {
  id?: true
  idCourse?: true
  idUser?: true
  name?: true
  number?: true
  year?: true
  createdAt?: true
  updatedAt?: true
}

export type TpCountAggregateInputType = {
  id?: true
  idCourse?: true
  idUser?: true
  name?: true
  number?: true
  year?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TpAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tp to aggregate.
   */
  where?: Prisma.TpWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tps to fetch.
   */
  orderBy?: Prisma.TpOrderByWithRelationInput | Prisma.TpOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TpWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tps
  **/
  _count?: true | TpCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TpAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TpSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TpMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TpMaxAggregateInputType
}

export type GetTpAggregateType<T extends TpAggregateArgs> = {
      [P in keyof T & keyof AggregateTp]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTp[P]>
    : Prisma.GetScalarType<T[P], AggregateTp[P]>
}




export type TpGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TpWhereInput
  orderBy?: Prisma.TpOrderByWithAggregationInput | Prisma.TpOrderByWithAggregationInput[]
  by: Prisma.TpScalarFieldEnum[] | Prisma.TpScalarFieldEnum
  having?: Prisma.TpScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TpCountAggregateInputType | true
  _avg?: TpAvgAggregateInputType
  _sum?: TpSumAggregateInputType
  _min?: TpMinAggregateInputType
  _max?: TpMaxAggregateInputType
}

export type TpGroupByOutputType = {
  id: string
  idCourse: string
  idUser: string
  name: string
  number: number | null
  year: number
  createdAt: Date
  updatedAt: Date
  _count: TpCountAggregateOutputType | null
  _avg: TpAvgAggregateOutputType | null
  _sum: TpSumAggregateOutputType | null
  _min: TpMinAggregateOutputType | null
  _max: TpMaxAggregateOutputType | null
}

type GetTpGroupByPayload<T extends TpGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TpGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TpGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TpGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TpGroupByOutputType[P]>
      }
    >
  >



export type TpWhereInput = {
  AND?: Prisma.TpWhereInput | Prisma.TpWhereInput[]
  OR?: Prisma.TpWhereInput[]
  NOT?: Prisma.TpWhereInput | Prisma.TpWhereInput[]
  id?: Prisma.StringFilter<"Tp"> | string
  idCourse?: Prisma.StringFilter<"Tp"> | string
  idUser?: Prisma.StringFilter<"Tp"> | string
  name?: Prisma.StringFilter<"Tp"> | string
  number?: Prisma.IntNullableFilter<"Tp"> | number | null
  year?: Prisma.IntFilter<"Tp"> | number
  createdAt?: Prisma.DateTimeFilter<"Tp"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Tp"> | Date | string
  responses?: Prisma.ResponseListRelationFilter
  courses?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
  users?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type TpOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  idCourse?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  name?: Prisma.SortOrder
  number?: Prisma.SortOrderInput | Prisma.SortOrder
  year?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  responses?: Prisma.ResponseOrderByRelationAggregateInput
  courses?: Prisma.CourseOrderByWithRelationInput
  users?: Prisma.UserOrderByWithRelationInput
}

export type TpWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TpWhereInput | Prisma.TpWhereInput[]
  OR?: Prisma.TpWhereInput[]
  NOT?: Prisma.TpWhereInput | Prisma.TpWhereInput[]
  idCourse?: Prisma.StringFilter<"Tp"> | string
  idUser?: Prisma.StringFilter<"Tp"> | string
  name?: Prisma.StringFilter<"Tp"> | string
  number?: Prisma.IntNullableFilter<"Tp"> | number | null
  year?: Prisma.IntFilter<"Tp"> | number
  createdAt?: Prisma.DateTimeFilter<"Tp"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Tp"> | Date | string
  responses?: Prisma.ResponseListRelationFilter
  courses?: Prisma.XOR<Prisma.CourseScalarRelationFilter, Prisma.CourseWhereInput>
  users?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type TpOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  idCourse?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  name?: Prisma.SortOrder
  number?: Prisma.SortOrderInput | Prisma.SortOrder
  year?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TpCountOrderByAggregateInput
  _avg?: Prisma.TpAvgOrderByAggregateInput
  _max?: Prisma.TpMaxOrderByAggregateInput
  _min?: Prisma.TpMinOrderByAggregateInput
  _sum?: Prisma.TpSumOrderByAggregateInput
}

export type TpScalarWhereWithAggregatesInput = {
  AND?: Prisma.TpScalarWhereWithAggregatesInput | Prisma.TpScalarWhereWithAggregatesInput[]
  OR?: Prisma.TpScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TpScalarWhereWithAggregatesInput | Prisma.TpScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Tp"> | string
  idCourse?: Prisma.StringWithAggregatesFilter<"Tp"> | string
  idUser?: Prisma.StringWithAggregatesFilter<"Tp"> | string
  name?: Prisma.StringWithAggregatesFilter<"Tp"> | string
  number?: Prisma.IntNullableWithAggregatesFilter<"Tp"> | number | null
  year?: Prisma.IntWithAggregatesFilter<"Tp"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Tp"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Tp"> | Date | string
}

export type TpCreateInput = {
  id?: string
  name: string
  number?: number | null
  year: number
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.ResponseCreateNestedManyWithoutTpInput
  courses: Prisma.CourseCreateNestedOneWithoutTpsInput
  users: Prisma.UserCreateNestedOneWithoutTpsInput
}

export type TpUncheckedCreateInput = {
  id?: string
  idCourse: string
  idUser: string
  name: string
  number?: number | null
  year: number
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.ResponseUncheckedCreateNestedManyWithoutTpInput
}

export type TpUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.ResponseUpdateManyWithoutTpNestedInput
  courses?: Prisma.CourseUpdateOneRequiredWithoutTpsNestedInput
  users?: Prisma.UserUpdateOneRequiredWithoutTpsNestedInput
}

export type TpUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idCourse?: Prisma.StringFieldUpdateOperationsInput | string
  idUser?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.ResponseUncheckedUpdateManyWithoutTpNestedInput
}

export type TpCreateManyInput = {
  id?: string
  idCourse: string
  idUser: string
  name: string
  number?: number | null
  year: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TpUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TpUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idCourse?: Prisma.StringFieldUpdateOperationsInput | string
  idUser?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TpListRelationFilter = {
  every?: Prisma.TpWhereInput
  some?: Prisma.TpWhereInput
  none?: Prisma.TpWhereInput
}

export type TpOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TpNullableScalarRelationFilter = {
  is?: Prisma.TpWhereInput | null
  isNot?: Prisma.TpWhereInput | null
}

export type TpCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  idCourse?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  name?: Prisma.SortOrder
  number?: Prisma.SortOrder
  year?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TpAvgOrderByAggregateInput = {
  number?: Prisma.SortOrder
  year?: Prisma.SortOrder
}

export type TpMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  idCourse?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  name?: Prisma.SortOrder
  number?: Prisma.SortOrder
  year?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TpMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  idCourse?: Prisma.SortOrder
  idUser?: Prisma.SortOrder
  name?: Prisma.SortOrder
  number?: Prisma.SortOrder
  year?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TpSumOrderByAggregateInput = {
  number?: Prisma.SortOrder
  year?: Prisma.SortOrder
}

export type TpCreateNestedManyWithoutCoursesInput = {
  create?: Prisma.XOR<Prisma.TpCreateWithoutCoursesInput, Prisma.TpUncheckedCreateWithoutCoursesInput> | Prisma.TpCreateWithoutCoursesInput[] | Prisma.TpUncheckedCreateWithoutCoursesInput[]
  connectOrCreate?: Prisma.TpCreateOrConnectWithoutCoursesInput | Prisma.TpCreateOrConnectWithoutCoursesInput[]
  createMany?: Prisma.TpCreateManyCoursesInputEnvelope
  connect?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
}

export type TpUncheckedCreateNestedManyWithoutCoursesInput = {
  create?: Prisma.XOR<Prisma.TpCreateWithoutCoursesInput, Prisma.TpUncheckedCreateWithoutCoursesInput> | Prisma.TpCreateWithoutCoursesInput[] | Prisma.TpUncheckedCreateWithoutCoursesInput[]
  connectOrCreate?: Prisma.TpCreateOrConnectWithoutCoursesInput | Prisma.TpCreateOrConnectWithoutCoursesInput[]
  createMany?: Prisma.TpCreateManyCoursesInputEnvelope
  connect?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
}

export type TpUpdateManyWithoutCoursesNestedInput = {
  create?: Prisma.XOR<Prisma.TpCreateWithoutCoursesInput, Prisma.TpUncheckedCreateWithoutCoursesInput> | Prisma.TpCreateWithoutCoursesInput[] | Prisma.TpUncheckedCreateWithoutCoursesInput[]
  connectOrCreate?: Prisma.TpCreateOrConnectWithoutCoursesInput | Prisma.TpCreateOrConnectWithoutCoursesInput[]
  upsert?: Prisma.TpUpsertWithWhereUniqueWithoutCoursesInput | Prisma.TpUpsertWithWhereUniqueWithoutCoursesInput[]
  createMany?: Prisma.TpCreateManyCoursesInputEnvelope
  set?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  disconnect?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  delete?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  connect?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  update?: Prisma.TpUpdateWithWhereUniqueWithoutCoursesInput | Prisma.TpUpdateWithWhereUniqueWithoutCoursesInput[]
  updateMany?: Prisma.TpUpdateManyWithWhereWithoutCoursesInput | Prisma.TpUpdateManyWithWhereWithoutCoursesInput[]
  deleteMany?: Prisma.TpScalarWhereInput | Prisma.TpScalarWhereInput[]
}

export type TpUncheckedUpdateManyWithoutCoursesNestedInput = {
  create?: Prisma.XOR<Prisma.TpCreateWithoutCoursesInput, Prisma.TpUncheckedCreateWithoutCoursesInput> | Prisma.TpCreateWithoutCoursesInput[] | Prisma.TpUncheckedCreateWithoutCoursesInput[]
  connectOrCreate?: Prisma.TpCreateOrConnectWithoutCoursesInput | Prisma.TpCreateOrConnectWithoutCoursesInput[]
  upsert?: Prisma.TpUpsertWithWhereUniqueWithoutCoursesInput | Prisma.TpUpsertWithWhereUniqueWithoutCoursesInput[]
  createMany?: Prisma.TpCreateManyCoursesInputEnvelope
  set?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  disconnect?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  delete?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  connect?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  update?: Prisma.TpUpdateWithWhereUniqueWithoutCoursesInput | Prisma.TpUpdateWithWhereUniqueWithoutCoursesInput[]
  updateMany?: Prisma.TpUpdateManyWithWhereWithoutCoursesInput | Prisma.TpUpdateManyWithWhereWithoutCoursesInput[]
  deleteMany?: Prisma.TpScalarWhereInput | Prisma.TpScalarWhereInput[]
}

export type TpCreateNestedOneWithoutResponsesInput = {
  create?: Prisma.XOR<Prisma.TpCreateWithoutResponsesInput, Prisma.TpUncheckedCreateWithoutResponsesInput>
  connectOrCreate?: Prisma.TpCreateOrConnectWithoutResponsesInput
  connect?: Prisma.TpWhereUniqueInput
}

export type TpUpdateOneWithoutResponsesNestedInput = {
  create?: Prisma.XOR<Prisma.TpCreateWithoutResponsesInput, Prisma.TpUncheckedCreateWithoutResponsesInput>
  connectOrCreate?: Prisma.TpCreateOrConnectWithoutResponsesInput
  upsert?: Prisma.TpUpsertWithoutResponsesInput
  disconnect?: Prisma.TpWhereInput | boolean
  delete?: Prisma.TpWhereInput | boolean
  connect?: Prisma.TpWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TpUpdateToOneWithWhereWithoutResponsesInput, Prisma.TpUpdateWithoutResponsesInput>, Prisma.TpUncheckedUpdateWithoutResponsesInput>
}

export type TpCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.TpCreateWithoutUsersInput, Prisma.TpUncheckedCreateWithoutUsersInput> | Prisma.TpCreateWithoutUsersInput[] | Prisma.TpUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.TpCreateOrConnectWithoutUsersInput | Prisma.TpCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.TpCreateManyUsersInputEnvelope
  connect?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
}

export type TpUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.TpCreateWithoutUsersInput, Prisma.TpUncheckedCreateWithoutUsersInput> | Prisma.TpCreateWithoutUsersInput[] | Prisma.TpUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.TpCreateOrConnectWithoutUsersInput | Prisma.TpCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.TpCreateManyUsersInputEnvelope
  connect?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
}

export type TpUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.TpCreateWithoutUsersInput, Prisma.TpUncheckedCreateWithoutUsersInput> | Prisma.TpCreateWithoutUsersInput[] | Prisma.TpUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.TpCreateOrConnectWithoutUsersInput | Prisma.TpCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.TpUpsertWithWhereUniqueWithoutUsersInput | Prisma.TpUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.TpCreateManyUsersInputEnvelope
  set?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  disconnect?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  delete?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  connect?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  update?: Prisma.TpUpdateWithWhereUniqueWithoutUsersInput | Prisma.TpUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.TpUpdateManyWithWhereWithoutUsersInput | Prisma.TpUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.TpScalarWhereInput | Prisma.TpScalarWhereInput[]
}

export type TpUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.TpCreateWithoutUsersInput, Prisma.TpUncheckedCreateWithoutUsersInput> | Prisma.TpCreateWithoutUsersInput[] | Prisma.TpUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.TpCreateOrConnectWithoutUsersInput | Prisma.TpCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.TpUpsertWithWhereUniqueWithoutUsersInput | Prisma.TpUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.TpCreateManyUsersInputEnvelope
  set?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  disconnect?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  delete?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  connect?: Prisma.TpWhereUniqueInput | Prisma.TpWhereUniqueInput[]
  update?: Prisma.TpUpdateWithWhereUniqueWithoutUsersInput | Prisma.TpUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.TpUpdateManyWithWhereWithoutUsersInput | Prisma.TpUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.TpScalarWhereInput | Prisma.TpScalarWhereInput[]
}

export type TpCreateWithoutCoursesInput = {
  id?: string
  name: string
  number?: number | null
  year: number
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.ResponseCreateNestedManyWithoutTpInput
  users: Prisma.UserCreateNestedOneWithoutTpsInput
}

export type TpUncheckedCreateWithoutCoursesInput = {
  id?: string
  idUser: string
  name: string
  number?: number | null
  year: number
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.ResponseUncheckedCreateNestedManyWithoutTpInput
}

export type TpCreateOrConnectWithoutCoursesInput = {
  where: Prisma.TpWhereUniqueInput
  create: Prisma.XOR<Prisma.TpCreateWithoutCoursesInput, Prisma.TpUncheckedCreateWithoutCoursesInput>
}

export type TpCreateManyCoursesInputEnvelope = {
  data: Prisma.TpCreateManyCoursesInput | Prisma.TpCreateManyCoursesInput[]
  skipDuplicates?: boolean
}

export type TpUpsertWithWhereUniqueWithoutCoursesInput = {
  where: Prisma.TpWhereUniqueInput
  update: Prisma.XOR<Prisma.TpUpdateWithoutCoursesInput, Prisma.TpUncheckedUpdateWithoutCoursesInput>
  create: Prisma.XOR<Prisma.TpCreateWithoutCoursesInput, Prisma.TpUncheckedCreateWithoutCoursesInput>
}

export type TpUpdateWithWhereUniqueWithoutCoursesInput = {
  where: Prisma.TpWhereUniqueInput
  data: Prisma.XOR<Prisma.TpUpdateWithoutCoursesInput, Prisma.TpUncheckedUpdateWithoutCoursesInput>
}

export type TpUpdateManyWithWhereWithoutCoursesInput = {
  where: Prisma.TpScalarWhereInput
  data: Prisma.XOR<Prisma.TpUpdateManyMutationInput, Prisma.TpUncheckedUpdateManyWithoutCoursesInput>
}

export type TpScalarWhereInput = {
  AND?: Prisma.TpScalarWhereInput | Prisma.TpScalarWhereInput[]
  OR?: Prisma.TpScalarWhereInput[]
  NOT?: Prisma.TpScalarWhereInput | Prisma.TpScalarWhereInput[]
  id?: Prisma.StringFilter<"Tp"> | string
  idCourse?: Prisma.StringFilter<"Tp"> | string
  idUser?: Prisma.StringFilter<"Tp"> | string
  name?: Prisma.StringFilter<"Tp"> | string
  number?: Prisma.IntNullableFilter<"Tp"> | number | null
  year?: Prisma.IntFilter<"Tp"> | number
  createdAt?: Prisma.DateTimeFilter<"Tp"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Tp"> | Date | string
}

export type TpCreateWithoutResponsesInput = {
  id?: string
  name: string
  number?: number | null
  year: number
  createdAt?: Date | string
  updatedAt?: Date | string
  courses: Prisma.CourseCreateNestedOneWithoutTpsInput
  users: Prisma.UserCreateNestedOneWithoutTpsInput
}

export type TpUncheckedCreateWithoutResponsesInput = {
  id?: string
  idCourse: string
  idUser: string
  name: string
  number?: number | null
  year: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TpCreateOrConnectWithoutResponsesInput = {
  where: Prisma.TpWhereUniqueInput
  create: Prisma.XOR<Prisma.TpCreateWithoutResponsesInput, Prisma.TpUncheckedCreateWithoutResponsesInput>
}

export type TpUpsertWithoutResponsesInput = {
  update: Prisma.XOR<Prisma.TpUpdateWithoutResponsesInput, Prisma.TpUncheckedUpdateWithoutResponsesInput>
  create: Prisma.XOR<Prisma.TpCreateWithoutResponsesInput, Prisma.TpUncheckedCreateWithoutResponsesInput>
  where?: Prisma.TpWhereInput
}

export type TpUpdateToOneWithWhereWithoutResponsesInput = {
  where?: Prisma.TpWhereInput
  data: Prisma.XOR<Prisma.TpUpdateWithoutResponsesInput, Prisma.TpUncheckedUpdateWithoutResponsesInput>
}

export type TpUpdateWithoutResponsesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  courses?: Prisma.CourseUpdateOneRequiredWithoutTpsNestedInput
  users?: Prisma.UserUpdateOneRequiredWithoutTpsNestedInput
}

export type TpUncheckedUpdateWithoutResponsesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idCourse?: Prisma.StringFieldUpdateOperationsInput | string
  idUser?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TpCreateWithoutUsersInput = {
  id?: string
  name: string
  number?: number | null
  year: number
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.ResponseCreateNestedManyWithoutTpInput
  courses: Prisma.CourseCreateNestedOneWithoutTpsInput
}

export type TpUncheckedCreateWithoutUsersInput = {
  id?: string
  idCourse: string
  name: string
  number?: number | null
  year: number
  createdAt?: Date | string
  updatedAt?: Date | string
  responses?: Prisma.ResponseUncheckedCreateNestedManyWithoutTpInput
}

export type TpCreateOrConnectWithoutUsersInput = {
  where: Prisma.TpWhereUniqueInput
  create: Prisma.XOR<Prisma.TpCreateWithoutUsersInput, Prisma.TpUncheckedCreateWithoutUsersInput>
}

export type TpCreateManyUsersInputEnvelope = {
  data: Prisma.TpCreateManyUsersInput | Prisma.TpCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type TpUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.TpWhereUniqueInput
  update: Prisma.XOR<Prisma.TpUpdateWithoutUsersInput, Prisma.TpUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.TpCreateWithoutUsersInput, Prisma.TpUncheckedCreateWithoutUsersInput>
}

export type TpUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.TpWhereUniqueInput
  data: Prisma.XOR<Prisma.TpUpdateWithoutUsersInput, Prisma.TpUncheckedUpdateWithoutUsersInput>
}

export type TpUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.TpScalarWhereInput
  data: Prisma.XOR<Prisma.TpUpdateManyMutationInput, Prisma.TpUncheckedUpdateManyWithoutUsersInput>
}

export type TpCreateManyCoursesInput = {
  id?: string
  idUser: string
  name: string
  number?: number | null
  year: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TpUpdateWithoutCoursesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.ResponseUpdateManyWithoutTpNestedInput
  users?: Prisma.UserUpdateOneRequiredWithoutTpsNestedInput
}

export type TpUncheckedUpdateWithoutCoursesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idUser?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.ResponseUncheckedUpdateManyWithoutTpNestedInput
}

export type TpUncheckedUpdateManyWithoutCoursesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idUser?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TpCreateManyUsersInput = {
  id?: string
  idCourse: string
  name: string
  number?: number | null
  year: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TpUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.ResponseUpdateManyWithoutTpNestedInput
  courses?: Prisma.CourseUpdateOneRequiredWithoutTpsNestedInput
}

export type TpUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idCourse?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  responses?: Prisma.ResponseUncheckedUpdateManyWithoutTpNestedInput
}

export type TpUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idCourse?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  number?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  year?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TpCountOutputType
 */

export type TpCountOutputType = {
  responses: number
}

export type TpCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  responses?: boolean | TpCountOutputTypeCountResponsesArgs
}

/**
 * TpCountOutputType without action
 */
export type TpCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TpCountOutputType
   */
  select?: Prisma.TpCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TpCountOutputType without action
 */
export type TpCountOutputTypeCountResponsesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ResponseWhereInput
}


export type TpSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  idCourse?: boolean
  idUser?: boolean
  name?: boolean
  number?: boolean
  year?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  responses?: boolean | Prisma.Tp$responsesArgs<ExtArgs>
  courses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.TpCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tp"]>

export type TpSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  idCourse?: boolean
  idUser?: boolean
  name?: boolean
  number?: boolean
  year?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  courses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tp"]>

export type TpSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  idCourse?: boolean
  idUser?: boolean
  name?: boolean
  number?: boolean
  year?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  courses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tp"]>

export type TpSelectScalar = {
  id?: boolean
  idCourse?: boolean
  idUser?: boolean
  name?: boolean
  number?: boolean
  year?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TpOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "idCourse" | "idUser" | "name" | "number" | "year" | "createdAt" | "updatedAt", ExtArgs["result"]["tp"]>
export type TpInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  responses?: boolean | Prisma.Tp$responsesArgs<ExtArgs>
  courses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.TpCountOutputTypeDefaultArgs<ExtArgs>
}
export type TpIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  courses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type TpIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  courses?: boolean | Prisma.CourseDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $TpPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Tp"
  objects: {
    responses: Prisma.$ResponsePayload<ExtArgs>[]
    courses: Prisma.$CoursePayload<ExtArgs>
    users: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    idCourse: string
    idUser: string
    name: string
    number: number | null
    year: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["tp"]>
  composites: {}
}

export type TpGetPayload<S extends boolean | null | undefined | TpDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TpPayload, S>

export type TpCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TpFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TpCountAggregateInputType | true
  }

export interface TpDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Tp'], meta: { name: 'Tp' } }
  /**
   * Find zero or one Tp that matches the filter.
   * @param {TpFindUniqueArgs} args - Arguments to find a Tp
   * @example
   * // Get one Tp
   * const tp = await prisma.tp.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TpFindUniqueArgs>(args: Prisma.SelectSubset<T, TpFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TpClient<runtime.Types.Result.GetResult<Prisma.$TpPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tp that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TpFindUniqueOrThrowArgs} args - Arguments to find a Tp
   * @example
   * // Get one Tp
   * const tp = await prisma.tp.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TpFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TpFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TpClient<runtime.Types.Result.GetResult<Prisma.$TpPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tp that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TpFindFirstArgs} args - Arguments to find a Tp
   * @example
   * // Get one Tp
   * const tp = await prisma.tp.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TpFindFirstArgs>(args?: Prisma.SelectSubset<T, TpFindFirstArgs<ExtArgs>>): Prisma.Prisma__TpClient<runtime.Types.Result.GetResult<Prisma.$TpPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tp that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TpFindFirstOrThrowArgs} args - Arguments to find a Tp
   * @example
   * // Get one Tp
   * const tp = await prisma.tp.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TpFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TpFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TpClient<runtime.Types.Result.GetResult<Prisma.$TpPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TpFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tps
   * const tps = await prisma.tp.findMany()
   * 
   * // Get first 10 Tps
   * const tps = await prisma.tp.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tpWithIdOnly = await prisma.tp.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TpFindManyArgs>(args?: Prisma.SelectSubset<T, TpFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TpPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tp.
   * @param {TpCreateArgs} args - Arguments to create a Tp.
   * @example
   * // Create one Tp
   * const Tp = await prisma.tp.create({
   *   data: {
   *     // ... data to create a Tp
   *   }
   * })
   * 
   */
  create<T extends TpCreateArgs>(args: Prisma.SelectSubset<T, TpCreateArgs<ExtArgs>>): Prisma.Prisma__TpClient<runtime.Types.Result.GetResult<Prisma.$TpPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tps.
   * @param {TpCreateManyArgs} args - Arguments to create many Tps.
   * @example
   * // Create many Tps
   * const tp = await prisma.tp.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TpCreateManyArgs>(args?: Prisma.SelectSubset<T, TpCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tps and returns the data saved in the database.
   * @param {TpCreateManyAndReturnArgs} args - Arguments to create many Tps.
   * @example
   * // Create many Tps
   * const tp = await prisma.tp.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tps and only return the `id`
   * const tpWithIdOnly = await prisma.tp.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TpCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TpCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TpPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tp.
   * @param {TpDeleteArgs} args - Arguments to delete one Tp.
   * @example
   * // Delete one Tp
   * const Tp = await prisma.tp.delete({
   *   where: {
   *     // ... filter to delete one Tp
   *   }
   * })
   * 
   */
  delete<T extends TpDeleteArgs>(args: Prisma.SelectSubset<T, TpDeleteArgs<ExtArgs>>): Prisma.Prisma__TpClient<runtime.Types.Result.GetResult<Prisma.$TpPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tp.
   * @param {TpUpdateArgs} args - Arguments to update one Tp.
   * @example
   * // Update one Tp
   * const tp = await prisma.tp.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TpUpdateArgs>(args: Prisma.SelectSubset<T, TpUpdateArgs<ExtArgs>>): Prisma.Prisma__TpClient<runtime.Types.Result.GetResult<Prisma.$TpPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tps.
   * @param {TpDeleteManyArgs} args - Arguments to filter Tps to delete.
   * @example
   * // Delete a few Tps
   * const { count } = await prisma.tp.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TpDeleteManyArgs>(args?: Prisma.SelectSubset<T, TpDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TpUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tps
   * const tp = await prisma.tp.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TpUpdateManyArgs>(args: Prisma.SelectSubset<T, TpUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tps and returns the data updated in the database.
   * @param {TpUpdateManyAndReturnArgs} args - Arguments to update many Tps.
   * @example
   * // Update many Tps
   * const tp = await prisma.tp.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tps and only return the `id`
   * const tpWithIdOnly = await prisma.tp.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TpUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TpUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TpPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tp.
   * @param {TpUpsertArgs} args - Arguments to update or create a Tp.
   * @example
   * // Update or create a Tp
   * const tp = await prisma.tp.upsert({
   *   create: {
   *     // ... data to create a Tp
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tp we want to update
   *   }
   * })
   */
  upsert<T extends TpUpsertArgs>(args: Prisma.SelectSubset<T, TpUpsertArgs<ExtArgs>>): Prisma.Prisma__TpClient<runtime.Types.Result.GetResult<Prisma.$TpPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TpCountArgs} args - Arguments to filter Tps to count.
   * @example
   * // Count the number of Tps
   * const count = await prisma.tp.count({
   *   where: {
   *     // ... the filter for the Tps we want to count
   *   }
   * })
  **/
  count<T extends TpCountArgs>(
    args?: Prisma.Subset<T, TpCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TpCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tp.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TpAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TpAggregateArgs>(args: Prisma.Subset<T, TpAggregateArgs>): Prisma.PrismaPromise<GetTpAggregateType<T>>

  /**
   * Group by Tp.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TpGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TpGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TpGroupByArgs['orderBy'] }
      : { orderBy?: TpGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TpGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTpGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Tp model
 */
readonly fields: TpFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Tp.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TpClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  responses<T extends Prisma.Tp$responsesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tp$responsesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ResponsePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  courses<T extends Prisma.CourseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CourseDefaultArgs<ExtArgs>>): Prisma.Prisma__CourseClient<runtime.Types.Result.GetResult<Prisma.$CoursePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Tp model
 */
export interface TpFieldRefs {
  readonly id: Prisma.FieldRef<"Tp", 'String'>
  readonly idCourse: Prisma.FieldRef<"Tp", 'String'>
  readonly idUser: Prisma.FieldRef<"Tp", 'String'>
  readonly name: Prisma.FieldRef<"Tp", 'String'>
  readonly number: Prisma.FieldRef<"Tp", 'Int'>
  readonly year: Prisma.FieldRef<"Tp", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Tp", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Tp", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Tp findUnique
 */
export type TpFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tp
   */
  select?: Prisma.TpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tp
   */
  omit?: Prisma.TpOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TpInclude<ExtArgs> | null
  /**
   * Filter, which Tp to fetch.
   */
  where: Prisma.TpWhereUniqueInput
}

/**
 * Tp findUniqueOrThrow
 */
export type TpFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tp
   */
  select?: Prisma.TpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tp
   */
  omit?: Prisma.TpOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TpInclude<ExtArgs> | null
  /**
   * Filter, which Tp to fetch.
   */
  where: Prisma.TpWhereUniqueInput
}

/**
 * Tp findFirst
 */
export type TpFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tp
   */
  select?: Prisma.TpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tp
   */
  omit?: Prisma.TpOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TpInclude<ExtArgs> | null
  /**
   * Filter, which Tp to fetch.
   */
  where?: Prisma.TpWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tps to fetch.
   */
  orderBy?: Prisma.TpOrderByWithRelationInput | Prisma.TpOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tps.
   */
  cursor?: Prisma.TpWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tps.
   */
  distinct?: Prisma.TpScalarFieldEnum | Prisma.TpScalarFieldEnum[]
}

/**
 * Tp findFirstOrThrow
 */
export type TpFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tp
   */
  select?: Prisma.TpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tp
   */
  omit?: Prisma.TpOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TpInclude<ExtArgs> | null
  /**
   * Filter, which Tp to fetch.
   */
  where?: Prisma.TpWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tps to fetch.
   */
  orderBy?: Prisma.TpOrderByWithRelationInput | Prisma.TpOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tps.
   */
  cursor?: Prisma.TpWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tps.
   */
  distinct?: Prisma.TpScalarFieldEnum | Prisma.TpScalarFieldEnum[]
}

/**
 * Tp findMany
 */
export type TpFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tp
   */
  select?: Prisma.TpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tp
   */
  omit?: Prisma.TpOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TpInclude<ExtArgs> | null
  /**
   * Filter, which Tps to fetch.
   */
  where?: Prisma.TpWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tps to fetch.
   */
  orderBy?: Prisma.TpOrderByWithRelationInput | Prisma.TpOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tps.
   */
  cursor?: Prisma.TpWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tps.
   */
  skip?: number
  distinct?: Prisma.TpScalarFieldEnum | Prisma.TpScalarFieldEnum[]
}

/**
 * Tp create
 */
export type TpCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tp
   */
  select?: Prisma.TpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tp
   */
  omit?: Prisma.TpOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TpInclude<ExtArgs> | null
  /**
   * The data needed to create a Tp.
   */
  data: Prisma.XOR<Prisma.TpCreateInput, Prisma.TpUncheckedCreateInput>
}

/**
 * Tp createMany
 */
export type TpCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tps.
   */
  data: Prisma.TpCreateManyInput | Prisma.TpCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Tp createManyAndReturn
 */
export type TpCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tp
   */
  select?: Prisma.TpSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tp
   */
  omit?: Prisma.TpOmit<ExtArgs> | null
  /**
   * The data used to create many Tps.
   */
  data: Prisma.TpCreateManyInput | Prisma.TpCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TpIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Tp update
 */
export type TpUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tp
   */
  select?: Prisma.TpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tp
   */
  omit?: Prisma.TpOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TpInclude<ExtArgs> | null
  /**
   * The data needed to update a Tp.
   */
  data: Prisma.XOR<Prisma.TpUpdateInput, Prisma.TpUncheckedUpdateInput>
  /**
   * Choose, which Tp to update.
   */
  where: Prisma.TpWhereUniqueInput
}

/**
 * Tp updateMany
 */
export type TpUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tps.
   */
  data: Prisma.XOR<Prisma.TpUpdateManyMutationInput, Prisma.TpUncheckedUpdateManyInput>
  /**
   * Filter which Tps to update
   */
  where?: Prisma.TpWhereInput
  /**
   * Limit how many Tps to update.
   */
  limit?: number
}

/**
 * Tp updateManyAndReturn
 */
export type TpUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tp
   */
  select?: Prisma.TpSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tp
   */
  omit?: Prisma.TpOmit<ExtArgs> | null
  /**
   * The data used to update Tps.
   */
  data: Prisma.XOR<Prisma.TpUpdateManyMutationInput, Prisma.TpUncheckedUpdateManyInput>
  /**
   * Filter which Tps to update
   */
  where?: Prisma.TpWhereInput
  /**
   * Limit how many Tps to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TpIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Tp upsert
 */
export type TpUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tp
   */
  select?: Prisma.TpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tp
   */
  omit?: Prisma.TpOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TpInclude<ExtArgs> | null
  /**
   * The filter to search for the Tp to update in case it exists.
   */
  where: Prisma.TpWhereUniqueInput
  /**
   * In case the Tp found by the `where` argument doesn't exist, create a new Tp with this data.
   */
  create: Prisma.XOR<Prisma.TpCreateInput, Prisma.TpUncheckedCreateInput>
  /**
   * In case the Tp was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TpUpdateInput, Prisma.TpUncheckedUpdateInput>
}

/**
 * Tp delete
 */
export type TpDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tp
   */
  select?: Prisma.TpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tp
   */
  omit?: Prisma.TpOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TpInclude<ExtArgs> | null
  /**
   * Filter which Tp to delete.
   */
  where: Prisma.TpWhereUniqueInput
}

/**
 * Tp deleteMany
 */
export type TpDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tps to delete
   */
  where?: Prisma.TpWhereInput
  /**
   * Limit how many Tps to delete.
   */
  limit?: number
}

/**
 * Tp.responses
 */
export type Tp$responsesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Response
   */
  select?: Prisma.ResponseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Response
   */
  omit?: Prisma.ResponseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResponseInclude<ExtArgs> | null
  where?: Prisma.ResponseWhereInput
  orderBy?: Prisma.ResponseOrderByWithRelationInput | Prisma.ResponseOrderByWithRelationInput[]
  cursor?: Prisma.ResponseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ResponseScalarFieldEnum | Prisma.ResponseScalarFieldEnum[]
}

/**
 * Tp without action
 */
export type TpDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tp
   */
  select?: Prisma.TpSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tp
   */
  omit?: Prisma.TpOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TpInclude<ExtArgs> | null
}
