
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Correlative
 * 
 */
export type Correlative = Prisma.CorrelativeModel
/**
 * Model Course
 * 
 */
export type Course = Prisma.CourseModel
/**
 * Model CourseDegree
 * 
 */
export type CourseDegree = Prisma.CourseDegreeModel
/**
 * Model CourseYear
 * 
 */
export type CourseYear = Prisma.CourseYearModel
/**
 * Model Degree
 * 
 */
export type Degree = Prisma.DegreeModel
/**
 * Model DegreePlan
 * 
 */
export type DegreePlan = Prisma.DegreePlanModel
/**
 * Model Link
 * 
 */
export type Link = Prisma.LinkModel
/**
 * Model Midterm
 * 
 */
export type Midterm = Prisma.MidtermModel
/**
 * Model Comment
 * 
 */
export type Comment = Prisma.CommentModel
/**
 * Model Response
 * 
 */
export type Response = Prisma.ResponseModel
/**
 * Model Plan
 * 
 */
export type Plan = Prisma.PlanModel
/**
 * Model Tp
 * 
 */
export type Tp = Prisma.TpModel
/**
 * Model Reaction
 * 
 */
export type Reaction = Prisma.ReactionModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Year
 * 
 */
export type Year = Prisma.YearModel
