
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TypeResponse = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  CODE: 'CODE',
  PDF: 'PDF'
} as const

export type TypeResponse = (typeof TypeResponse)[keyof typeof TypeResponse]


export const TypeReaction = {
  LIKE: 'LIKE',
  DISLIKE: 'DISLIKE'
} as const

export type TypeReaction = (typeof TypeReaction)[keyof typeof TypeReaction]


export const ReactionTo = {
  RESPONSE: 'RESPONSE',
  COMMENT: 'COMMENT',
  TP: 'TP',
  MIDTERM: 'MIDTERM',
  LINK: 'LINK'
} as const

export type ReactionTo = (typeof ReactionTo)[keyof typeof ReactionTo]
