
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Correlative: 'Correlative',
  Course: 'Course',
  CourseDegree: 'CourseDegree',
  CourseYear: 'CourseYear',
  Degree: 'Degree',
  DegreePlan: 'DegreePlan',
  Link: 'Link',
  Midterm: 'Midterm',
  Comment: 'Comment',
  Response: 'Response',
  Plan: 'Plan',
  Tp: 'Tp',
  Reaction: 'Reaction',
  User: 'User',
  Year: 'Year'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CorrelativeScalarFieldEnum = {
  idCourse: 'idCourse',
  idCorrelativeCourse: 'idCorrelativeCourse',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CorrelativeScalarFieldEnum = (typeof CorrelativeScalarFieldEnum)[keyof typeof CorrelativeScalarFieldEnum]


export const CourseScalarFieldEnum = {
  id: 'id',
  name: 'name',
  nameNormalized: 'nameNormalized',
  cg: 'cg',
  hs: 'hs',
  optional: 'optional',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CourseScalarFieldEnum = (typeof CourseScalarFieldEnum)[keyof typeof CourseScalarFieldEnum]


export const CourseDegreeScalarFieldEnum = {
  idCourse: 'idCourse',
  idDegree: 'idDegree',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CourseDegreeScalarFieldEnum = (typeof CourseDegreeScalarFieldEnum)[keyof typeof CourseDegreeScalarFieldEnum]


export const CourseYearScalarFieldEnum = {
  idCourse: 'idCourse',
  idYear: 'idYear',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CourseYearScalarFieldEnum = (typeof CourseYearScalarFieldEnum)[keyof typeof CourseYearScalarFieldEnum]


export const DegreeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DegreeScalarFieldEnum = (typeof DegreeScalarFieldEnum)[keyof typeof DegreeScalarFieldEnum]


export const DegreePlanScalarFieldEnum = {
  idDegree: 'idDegree',
  idPlan: 'idPlan',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DegreePlanScalarFieldEnum = (typeof DegreePlanScalarFieldEnum)[keyof typeof DegreePlanScalarFieldEnum]


export const LinkScalarFieldEnum = {
  id: 'id',
  idCourse: 'idCourse',
  idUser: 'idUser',
  name: 'name',
  link: 'link',
  official: 'official',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LinkScalarFieldEnum = (typeof LinkScalarFieldEnum)[keyof typeof LinkScalarFieldEnum]


export const MidtermScalarFieldEnum = {
  id: 'id',
  idCourse: 'idCourse',
  idUser: 'idUser',
  name: 'name',
  date: 'date',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MidtermScalarFieldEnum = (typeof MidtermScalarFieldEnum)[keyof typeof MidtermScalarFieldEnum]


export const CommentScalarFieldEnum = {
  id: 'id',
  idResponse: 'idResponse',
  idUser: 'idUser',
  text: 'text',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CommentScalarFieldEnum = (typeof CommentScalarFieldEnum)[keyof typeof CommentScalarFieldEnum]


export const ResponseScalarFieldEnum = {
  id: 'id',
  idUser: 'idUser',
  idTp: 'idTp',
  idMidterm: 'idMidterm',
  number: 'number',
  type: 'type',
  text: 'text',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ResponseScalarFieldEnum = (typeof ResponseScalarFieldEnum)[keyof typeof ResponseScalarFieldEnum]


export const PlanScalarFieldEnum = {
  id: 'id',
  year: 'year',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlanScalarFieldEnum = (typeof PlanScalarFieldEnum)[keyof typeof PlanScalarFieldEnum]


export const TpScalarFieldEnum = {
  id: 'id',
  idCourse: 'idCourse',
  idUser: 'idUser',
  name: 'name',
  number: 'number',
  year: 'year',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TpScalarFieldEnum = (typeof TpScalarFieldEnum)[keyof typeof TpScalarFieldEnum]


export const ReactionScalarFieldEnum = {
  id: 'id',
  idUser: 'idUser',
  idTarget: 'idTarget',
  typeTarget: 'typeTarget',
  reaction: 'reaction',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ReactionScalarFieldEnum = (typeof ReactionScalarFieldEnum)[keyof typeof ReactionScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  image: 'image',
  tier: 'tier',
  banned: 'banned',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const YearScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type YearScalarFieldEnum = (typeof YearScalarFieldEnum)[keyof typeof YearScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

