
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.4.2
 * Query Engine version: 94a226be1cf2967af2541cca5529f0f7ba866919
 */
export const prismaVersion: PrismaVersion = {
  client: "7.4.2",
  engine: "94a226be1cf2967af2541cca5529f0f7ba866919"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Correlative: 'Correlative',
  Course: 'Course',
  CourseDegree: 'CourseDegree',
  CourseYear: 'CourseYear',
  Degree: 'Degree',
  DegreePlan: 'DegreePlan',
  Link: 'Link',
  Midterm: 'Midterm',
  Comment: 'Comment',
  Response: 'Response',
  Plan: 'Plan',
  Tp: 'Tp',
  Reaction: 'Reaction',
  User: 'User',
  Year: 'Year'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "correlative" | "course" | "courseDegree" | "courseYear" | "degree" | "degreePlan" | "link" | "midterm" | "comment" | "response" | "plan" | "tp" | "reaction" | "user" | "year"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Correlative: {
      payload: Prisma.$CorrelativePayload<ExtArgs>
      fields: Prisma.CorrelativeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CorrelativeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CorrelativePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CorrelativeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CorrelativePayload>
        }
        findFirst: {
          args: Prisma.CorrelativeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CorrelativePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CorrelativeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CorrelativePayload>
        }
        findMany: {
          args: Prisma.CorrelativeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CorrelativePayload>[]
        }
        create: {
          args: Prisma.CorrelativeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CorrelativePayload>
        }
        createMany: {
          args: Prisma.CorrelativeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CorrelativeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CorrelativePayload>[]
        }
        delete: {
          args: Prisma.CorrelativeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CorrelativePayload>
        }
        update: {
          args: Prisma.CorrelativeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CorrelativePayload>
        }
        deleteMany: {
          args: Prisma.CorrelativeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CorrelativeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CorrelativeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CorrelativePayload>[]
        }
        upsert: {
          args: Prisma.CorrelativeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CorrelativePayload>
        }
        aggregate: {
          args: Prisma.CorrelativeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCorrelative>
        }
        groupBy: {
          args: Prisma.CorrelativeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CorrelativeGroupByOutputType>[]
        }
        count: {
          args: Prisma.CorrelativeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CorrelativeCountAggregateOutputType> | number
        }
      }
    }
    Course: {
      payload: Prisma.$CoursePayload<ExtArgs>
      fields: Prisma.CourseFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CourseFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CoursePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CourseFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CoursePayload>
        }
        findFirst: {
          args: Prisma.CourseFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CoursePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CourseFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CoursePayload>
        }
        findMany: {
          args: Prisma.CourseFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CoursePayload>[]
        }
        create: {
          args: Prisma.CourseCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CoursePayload>
        }
        createMany: {
          args: Prisma.CourseCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CourseCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CoursePayload>[]
        }
        delete: {
          args: Prisma.CourseDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CoursePayload>
        }
        update: {
          args: Prisma.CourseUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CoursePayload>
        }
        deleteMany: {
          args: Prisma.CourseDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CourseUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CourseUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CoursePayload>[]
        }
        upsert: {
          args: Prisma.CourseUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CoursePayload>
        }
        aggregate: {
          args: Prisma.CourseAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCourse>
        }
        groupBy: {
          args: Prisma.CourseGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CourseGroupByOutputType>[]
        }
        count: {
          args: Prisma.CourseCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CourseCountAggregateOutputType> | number
        }
      }
    }
    CourseDegree: {
      payload: Prisma.$CourseDegreePayload<ExtArgs>
      fields: Prisma.CourseDegreeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CourseDegreeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseDegreePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CourseDegreeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseDegreePayload>
        }
        findFirst: {
          args: Prisma.CourseDegreeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseDegreePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CourseDegreeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseDegreePayload>
        }
        findMany: {
          args: Prisma.CourseDegreeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseDegreePayload>[]
        }
        create: {
          args: Prisma.CourseDegreeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseDegreePayload>
        }
        createMany: {
          args: Prisma.CourseDegreeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CourseDegreeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseDegreePayload>[]
        }
        delete: {
          args: Prisma.CourseDegreeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseDegreePayload>
        }
        update: {
          args: Prisma.CourseDegreeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseDegreePayload>
        }
        deleteMany: {
          args: Prisma.CourseDegreeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CourseDegreeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CourseDegreeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseDegreePayload>[]
        }
        upsert: {
          args: Prisma.CourseDegreeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseDegreePayload>
        }
        aggregate: {
          args: Prisma.CourseDegreeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCourseDegree>
        }
        groupBy: {
          args: Prisma.CourseDegreeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CourseDegreeGroupByOutputType>[]
        }
        count: {
          args: Prisma.CourseDegreeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CourseDegreeCountAggregateOutputType> | number
        }
      }
    }
    CourseYear: {
      payload: Prisma.$CourseYearPayload<ExtArgs>
      fields: Prisma.CourseYearFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CourseYearFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseYearPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CourseYearFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseYearPayload>
        }
        findFirst: {
          args: Prisma.CourseYearFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseYearPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CourseYearFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseYearPayload>
        }
        findMany: {
          args: Prisma.CourseYearFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseYearPayload>[]
        }
        create: {
          args: Prisma.CourseYearCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseYearPayload>
        }
        createMany: {
          args: Prisma.CourseYearCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CourseYearCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseYearPayload>[]
        }
        delete: {
          args: Prisma.CourseYearDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseYearPayload>
        }
        update: {
          args: Prisma.CourseYearUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseYearPayload>
        }
        deleteMany: {
          args: Prisma.CourseYearDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CourseYearUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CourseYearUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseYearPayload>[]
        }
        upsert: {
          args: Prisma.CourseYearUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CourseYearPayload>
        }
        aggregate: {
          args: Prisma.CourseYearAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCourseYear>
        }
        groupBy: {
          args: Prisma.CourseYearGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CourseYearGroupByOutputType>[]
        }
        count: {
          args: Prisma.CourseYearCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CourseYearCountAggregateOutputType> | number
        }
      }
    }
    Degree: {
      payload: Prisma.$DegreePayload<ExtArgs>
      fields: Prisma.DegreeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DegreeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DegreeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePayload>
        }
        findFirst: {
          args: Prisma.DegreeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DegreeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePayload>
        }
        findMany: {
          args: Prisma.DegreeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePayload>[]
        }
        create: {
          args: Prisma.DegreeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePayload>
        }
        createMany: {
          args: Prisma.DegreeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DegreeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePayload>[]
        }
        delete: {
          args: Prisma.DegreeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePayload>
        }
        update: {
          args: Prisma.DegreeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePayload>
        }
        deleteMany: {
          args: Prisma.DegreeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DegreeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DegreeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePayload>[]
        }
        upsert: {
          args: Prisma.DegreeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePayload>
        }
        aggregate: {
          args: Prisma.DegreeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDegree>
        }
        groupBy: {
          args: Prisma.DegreeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DegreeGroupByOutputType>[]
        }
        count: {
          args: Prisma.DegreeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DegreeCountAggregateOutputType> | number
        }
      }
    }
    DegreePlan: {
      payload: Prisma.$DegreePlanPayload<ExtArgs>
      fields: Prisma.DegreePlanFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DegreePlanFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePlanPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DegreePlanFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePlanPayload>
        }
        findFirst: {
          args: Prisma.DegreePlanFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePlanPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DegreePlanFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePlanPayload>
        }
        findMany: {
          args: Prisma.DegreePlanFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePlanPayload>[]
        }
        create: {
          args: Prisma.DegreePlanCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePlanPayload>
        }
        createMany: {
          args: Prisma.DegreePlanCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DegreePlanCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePlanPayload>[]
        }
        delete: {
          args: Prisma.DegreePlanDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePlanPayload>
        }
        update: {
          args: Prisma.DegreePlanUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePlanPayload>
        }
        deleteMany: {
          args: Prisma.DegreePlanDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DegreePlanUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DegreePlanUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePlanPayload>[]
        }
        upsert: {
          args: Prisma.DegreePlanUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DegreePlanPayload>
        }
        aggregate: {
          args: Prisma.DegreePlanAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDegreePlan>
        }
        groupBy: {
          args: Prisma.DegreePlanGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DegreePlanGroupByOutputType>[]
        }
        count: {
          args: Prisma.DegreePlanCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DegreePlanCountAggregateOutputType> | number
        }
      }
    }
    Link: {
      payload: Prisma.$LinkPayload<ExtArgs>
      fields: Prisma.LinkFieldRefs
      operations: {
        findUnique: {
          args: Prisma.LinkFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.LinkFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkPayload>
        }
        findFirst: {
          args: Prisma.LinkFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.LinkFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkPayload>
        }
        findMany: {
          args: Prisma.LinkFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkPayload>[]
        }
        create: {
          args: Prisma.LinkCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkPayload>
        }
        createMany: {
          args: Prisma.LinkCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.LinkCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkPayload>[]
        }
        delete: {
          args: Prisma.LinkDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkPayload>
        }
        update: {
          args: Prisma.LinkUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkPayload>
        }
        deleteMany: {
          args: Prisma.LinkDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.LinkUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.LinkUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkPayload>[]
        }
        upsert: {
          args: Prisma.LinkUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LinkPayload>
        }
        aggregate: {
          args: Prisma.LinkAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateLink>
        }
        groupBy: {
          args: Prisma.LinkGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LinkGroupByOutputType>[]
        }
        count: {
          args: Prisma.LinkCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LinkCountAggregateOutputType> | number
        }
      }
    }
    Midterm: {
      payload: Prisma.$MidtermPayload<ExtArgs>
      fields: Prisma.MidtermFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MidtermFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MidtermPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MidtermFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MidtermPayload>
        }
        findFirst: {
          args: Prisma.MidtermFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MidtermPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MidtermFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MidtermPayload>
        }
        findMany: {
          args: Prisma.MidtermFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MidtermPayload>[]
        }
        create: {
          args: Prisma.MidtermCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MidtermPayload>
        }
        createMany: {
          args: Prisma.MidtermCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MidtermCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MidtermPayload>[]
        }
        delete: {
          args: Prisma.MidtermDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MidtermPayload>
        }
        update: {
          args: Prisma.MidtermUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MidtermPayload>
        }
        deleteMany: {
          args: Prisma.MidtermDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MidtermUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MidtermUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MidtermPayload>[]
        }
        upsert: {
          args: Prisma.MidtermUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MidtermPayload>
        }
        aggregate: {
          args: Prisma.MidtermAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMidterm>
        }
        groupBy: {
          args: Prisma.MidtermGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MidtermGroupByOutputType>[]
        }
        count: {
          args: Prisma.MidtermCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MidtermCountAggregateOutputType> | number
        }
      }
    }
    Comment: {
      payload: Prisma.$CommentPayload<ExtArgs>
      fields: Prisma.CommentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CommentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CommentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommentPayload>
        }
        findFirst: {
          args: Prisma.CommentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CommentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommentPayload>
        }
        findMany: {
          args: Prisma.CommentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommentPayload>[]
        }
        create: {
          args: Prisma.CommentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommentPayload>
        }
        createMany: {
          args: Prisma.CommentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CommentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommentPayload>[]
        }
        delete: {
          args: Prisma.CommentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommentPayload>
        }
        update: {
          args: Prisma.CommentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommentPayload>
        }
        deleteMany: {
          args: Prisma.CommentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CommentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CommentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommentPayload>[]
        }
        upsert: {
          args: Prisma.CommentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommentPayload>
        }
        aggregate: {
          args: Prisma.CommentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateComment>
        }
        groupBy: {
          args: Prisma.CommentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CommentGroupByOutputType>[]
        }
        count: {
          args: Prisma.CommentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CommentCountAggregateOutputType> | number
        }
      }
    }
    Response: {
      payload: Prisma.$ResponsePayload<ExtArgs>
      fields: Prisma.ResponseFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ResponseFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ResponsePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ResponseFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ResponsePayload>
        }
        findFirst: {
          args: Prisma.ResponseFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ResponsePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ResponseFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ResponsePayload>
        }
        findMany: {
          args: Prisma.ResponseFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ResponsePayload>[]
        }
        create: {
          args: Prisma.ResponseCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ResponsePayload>
        }
        createMany: {
          args: Prisma.ResponseCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ResponseCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ResponsePayload>[]
        }
        delete: {
          args: Prisma.ResponseDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ResponsePayload>
        }
        update: {
          args: Prisma.ResponseUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ResponsePayload>
        }
        deleteMany: {
          args: Prisma.ResponseDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ResponseUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ResponseUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ResponsePayload>[]
        }
        upsert: {
          args: Prisma.ResponseUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ResponsePayload>
        }
        aggregate: {
          args: Prisma.ResponseAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateResponse>
        }
        groupBy: {
          args: Prisma.ResponseGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ResponseGroupByOutputType>[]
        }
        count: {
          args: Prisma.ResponseCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ResponseCountAggregateOutputType> | number
        }
      }
    }
    Plan: {
      payload: Prisma.$PlanPayload<ExtArgs>
      fields: Prisma.PlanFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PlanFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlanPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PlanFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlanPayload>
        }
        findFirst: {
          args: Prisma.PlanFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlanPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PlanFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlanPayload>
        }
        findMany: {
          args: Prisma.PlanFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlanPayload>[]
        }
        create: {
          args: Prisma.PlanCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlanPayload>
        }
        createMany: {
          args: Prisma.PlanCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PlanCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlanPayload>[]
        }
        delete: {
          args: Prisma.PlanDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlanPayload>
        }
        update: {
          args: Prisma.PlanUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlanPayload>
        }
        deleteMany: {
          args: Prisma.PlanDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PlanUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PlanUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlanPayload>[]
        }
        upsert: {
          args: Prisma.PlanUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlanPayload>
        }
        aggregate: {
          args: Prisma.PlanAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePlan>
        }
        groupBy: {
          args: Prisma.PlanGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PlanGroupByOutputType>[]
        }
        count: {
          args: Prisma.PlanCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PlanCountAggregateOutputType> | number
        }
      }
    }
    Tp: {
      payload: Prisma.$TpPayload<ExtArgs>
      fields: Prisma.TpFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TpFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TpPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TpFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TpPayload>
        }
        findFirst: {
          args: Prisma.TpFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TpPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TpFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TpPayload>
        }
        findMany: {
          args: Prisma.TpFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TpPayload>[]
        }
        create: {
          args: Prisma.TpCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TpPayload>
        }
        createMany: {
          args: Prisma.TpCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TpCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TpPayload>[]
        }
        delete: {
          args: Prisma.TpDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TpPayload>
        }
        update: {
          args: Prisma.TpUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TpPayload>
        }
        deleteMany: {
          args: Prisma.TpDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TpUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TpUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TpPayload>[]
        }
        upsert: {
          args: Prisma.TpUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TpPayload>
        }
        aggregate: {
          args: Prisma.TpAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTp>
        }
        groupBy: {
          args: Prisma.TpGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TpGroupByOutputType>[]
        }
        count: {
          args: Prisma.TpCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TpCountAggregateOutputType> | number
        }
      }
    }
    Reaction: {
      payload: Prisma.$ReactionPayload<ExtArgs>
      fields: Prisma.ReactionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ReactionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReactionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ReactionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReactionPayload>
        }
        findFirst: {
          args: Prisma.ReactionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReactionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ReactionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReactionPayload>
        }
        findMany: {
          args: Prisma.ReactionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReactionPayload>[]
        }
        create: {
          args: Prisma.ReactionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReactionPayload>
        }
        createMany: {
          args: Prisma.ReactionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ReactionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReactionPayload>[]
        }
        delete: {
          args: Prisma.ReactionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReactionPayload>
        }
        update: {
          args: Prisma.ReactionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReactionPayload>
        }
        deleteMany: {
          args: Prisma.ReactionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ReactionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ReactionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReactionPayload>[]
        }
        upsert: {
          args: Prisma.ReactionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReactionPayload>
        }
        aggregate: {
          args: Prisma.ReactionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateReaction>
        }
        groupBy: {
          args: Prisma.ReactionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ReactionGroupByOutputType>[]
        }
        count: {
          args: Prisma.ReactionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ReactionCountAggregateOutputType> | number
        }
      }
    }
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    Year: {
      payload: Prisma.$YearPayload<ExtArgs>
      fields: Prisma.YearFieldRefs
      operations: {
        findUnique: {
          args: Prisma.YearFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$YearPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.YearFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$YearPayload>
        }
        findFirst: {
          args: Prisma.YearFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$YearPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.YearFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$YearPayload>
        }
        findMany: {
          args: Prisma.YearFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$YearPayload>[]
        }
        create: {
          args: Prisma.YearCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$YearPayload>
        }
        createMany: {
          args: Prisma.YearCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.YearCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$YearPayload>[]
        }
        delete: {
          args: Prisma.YearDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$YearPayload>
        }
        update: {
          args: Prisma.YearUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$YearPayload>
        }
        deleteMany: {
          args: Prisma.YearDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.YearUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.YearUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$YearPayload>[]
        }
        upsert: {
          args: Prisma.YearUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$YearPayload>
        }
        aggregate: {
          args: Prisma.YearAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateYear>
        }
        groupBy: {
          args: Prisma.YearGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.YearGroupByOutputType>[]
        }
        count: {
          args: Prisma.YearCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.YearCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CorrelativeScalarFieldEnum = {
  idCourse: 'idCourse',
  idCorrelativeCourse: 'idCorrelativeCourse',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CorrelativeScalarFieldEnum = (typeof CorrelativeScalarFieldEnum)[keyof typeof CorrelativeScalarFieldEnum]


export const CourseScalarFieldEnum = {
  id: 'id',
  name: 'name',
  nameNormalized: 'nameNormalized',
  cg: 'cg',
  hs: 'hs',
  optional: 'optional',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CourseScalarFieldEnum = (typeof CourseScalarFieldEnum)[keyof typeof CourseScalarFieldEnum]


export const CourseDegreeScalarFieldEnum = {
  idCourse: 'idCourse',
  idDegree: 'idDegree',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CourseDegreeScalarFieldEnum = (typeof CourseDegreeScalarFieldEnum)[keyof typeof CourseDegreeScalarFieldEnum]


export const CourseYearScalarFieldEnum = {
  idCourse: 'idCourse',
  idYear: 'idYear',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CourseYearScalarFieldEnum = (typeof CourseYearScalarFieldEnum)[keyof typeof CourseYearScalarFieldEnum]


export const DegreeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DegreeScalarFieldEnum = (typeof DegreeScalarFieldEnum)[keyof typeof DegreeScalarFieldEnum]


export const DegreePlanScalarFieldEnum = {
  idDegree: 'idDegree',
  idPlan: 'idPlan',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DegreePlanScalarFieldEnum = (typeof DegreePlanScalarFieldEnum)[keyof typeof DegreePlanScalarFieldEnum]


export const LinkScalarFieldEnum = {
  id: 'id',
  idCourse: 'idCourse',
  idUser: 'idUser',
  name: 'name',
  link: 'link',
  official: 'official',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LinkScalarFieldEnum = (typeof LinkScalarFieldEnum)[keyof typeof LinkScalarFieldEnum]


export const MidtermScalarFieldEnum = {
  id: 'id',
  idCourse: 'idCourse',
  idUser: 'idUser',
  name: 'name',
  date: 'date',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MidtermScalarFieldEnum = (typeof MidtermScalarFieldEnum)[keyof typeof MidtermScalarFieldEnum]


export const CommentScalarFieldEnum = {
  id: 'id',
  idResponse: 'idResponse',
  idUser: 'idUser',
  text: 'text',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CommentScalarFieldEnum = (typeof CommentScalarFieldEnum)[keyof typeof CommentScalarFieldEnum]


export const ResponseScalarFieldEnum = {
  id: 'id',
  idUser: 'idUser',
  idTp: 'idTp',
  idMidterm: 'idMidterm',
  number: 'number',
  type: 'type',
  text: 'text',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ResponseScalarFieldEnum = (typeof ResponseScalarFieldEnum)[keyof typeof ResponseScalarFieldEnum]


export const PlanScalarFieldEnum = {
  id: 'id',
  year: 'year',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlanScalarFieldEnum = (typeof PlanScalarFieldEnum)[keyof typeof PlanScalarFieldEnum]


export const TpScalarFieldEnum = {
  id: 'id',
  idCourse: 'idCourse',
  idUser: 'idUser',
  name: 'name',
  number: 'number',
  year: 'year',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TpScalarFieldEnum = (typeof TpScalarFieldEnum)[keyof typeof TpScalarFieldEnum]


export const ReactionScalarFieldEnum = {
  id: 'id',
  idUser: 'idUser',
  idTarget: 'idTarget',
  typeTarget: 'typeTarget',
  reaction: 'reaction',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ReactionScalarFieldEnum = (typeof ReactionScalarFieldEnum)[keyof typeof ReactionScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  image: 'image',
  tier: 'tier',
  banned: 'banned',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const YearScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type YearScalarFieldEnum = (typeof YearScalarFieldEnum)[keyof typeof YearScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'TypeResponse'
 */
export type EnumTypeResponseFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'TypeResponse'>
    


/**
 * Reference to a field of type 'TypeResponse[]'
 */
export type ListEnumTypeResponseFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'TypeResponse[]'>
    


/**
 * Reference to a field of type 'ReactionTo'
 */
export type EnumReactionToFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ReactionTo'>
    


/**
 * Reference to a field of type 'ReactionTo[]'
 */
export type ListEnumReactionToFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'ReactionTo[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  correlative?: Prisma.CorrelativeOmit
  course?: Prisma.CourseOmit
  courseDegree?: Prisma.CourseDegreeOmit
  courseYear?: Prisma.CourseYearOmit
  degree?: Prisma.DegreeOmit
  degreePlan?: Prisma.DegreePlanOmit
  link?: Prisma.LinkOmit
  midterm?: Prisma.MidtermOmit
  comment?: Prisma.CommentOmit
  response?: Prisma.ResponseOmit
  plan?: Prisma.PlanOmit
  tp?: Prisma.TpOmit
  reaction?: Prisma.ReactionOmit
  user?: Prisma.UserOmit
  year?: Prisma.YearOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

