import { PrismaClient } from '../prismaClient/client'

export const courseSeed = async (db: PrismaClient) => {
  const courses = await db.course.findMany()
  if (!courses.length)
    await db.course.createMany({
      data: [
        { name: 'Análisis Matemático I', nameNormalized: 'analisis matematico i', cg: 6, hs: 96 },
        { name: 'Álgebra I-B', nameNormalized: 'algebra i-b', cg: 4, hs: 64 },
        { name: 'Informática Básica', nameNormalized: 'informatica basica', cg: 4, hs: 64 },
        { name: 'Tecnologías Informáticas A', nameNormalized: 'tecnologias informaticas a', cg: 6, hs: 96 },
        { name: 'Física A', nameNormalized: 'fisica a', cg: 6, hs: 96 },
        { name: 'Probabilidad y Estadística', nameNormalized: 'probabilidad y estadistica', cg: 4, hs: 64 },
        { name: 'Programación B', nameNormalized: 'programacion b', cg: 8, hs: 128 },
        { name: 'Tecnologías Informáticas B', nameNormalized: 'tecnologias informaticas b', cg: 6, hs: 96 },
        { name: 'Inglés I', nameNormalized: 'ingles i', cg: 3, hs: 48 },
        { name: 'Investigación de Operaciones', nameNormalized: 'investigacion de operaciones', cg: 4, hs: 64 },
        { name: 'Estructura y Organización de Datos', nameNormalized: 'estructura y organizacion de datos', cg: 5, hs: 80 },
        { name: 'Fundamentos de Sistemas Operativos', nameNormalized: 'fundamentos de sistemas operativos', cg: 6, hs: 96 },
        { name: 'Fundamentos de Lenguajes Formales', nameNormalized: 'fundamentos de lenguajes formales', cg: 4, hs: 64 },
        { name: 'Sistemas de Bases de Datos', nameNormalized: 'sistemas de bases de datos', cg: 6, hs: 96 },
        {
          name: 'Introducción a la Inteligencia Artificial',
          nameNormalized: 'introduccion a la inteligencia artificial',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Redes y Comunicación de Datos B', nameNormalized: 'redes y comunicacion de datos b', cg: 4, hs: 64 },
        { name: 'Análisis y Diseño de Sistemas B', nameNormalized: 'analisis y diseno de sistemas b', cg: 6, hs: 96 },
        {
          name: 'Comportamiento Organizacional y Relaciones del Trabajo',
          nameNormalized: 'comportamiento organizacional y relaciones del trabajo',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Teoría de Modelos y Simulación', nameNormalized: 'teoria de modelos y simulacion', cg: 4, hs: 64 },
        {
          name: 'Ética, Legislación y Propiedad Intelectual en el Ejercicio Profesional',
          nameNormalized: 'etica legislacion y propiedad intelectual en el ejercicio profesional',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Auditoría y homologación', nameNormalized: 'auditoria y homologacion', cg: 4, hs: 64 },
        { name: 'Análisis Matemático II', nameNormalized: 'analisis matematico ii', cg: 5, hs: 80 },
        { name: 'Álgebra II', nameNormalized: 'algebra ii', cg: 5, hs: 80 },
        { name: 'Programación A', nameNormalized: 'programacion a', cg: 8, hs: 128 },
        { name: 'Introducción a la Matemática Discreta', nameNormalized: 'introduccion a la matematica discreta', cg: 4, hs: 64 },
        { name: 'Física B-II', nameNormalized: 'fisica b-ii', cg: 6, hs: 96 },
        {
          name: 'Teorías de la Información y la Computación',
          nameNormalized: 'teorias de la informacion y la computacion',
          cg: 5,
          hs: 80,
          optional: false,
        },
        {
          name: 'Fundamentos de la Arquitectura de Computadoras',
          nameNormalized: 'fundamentos de la arquitectura de computadoras',
          cg: 5,
          hs: 80,
          optional: false,
        },
        { name: 'Programación C', nameNormalized: 'programacion c', cg: 8, hs: 128 },
        { name: 'Inglés II', nameNormalized: 'ingles ii', cg: 3, hs: 48 },
        { name: 'Calidad de Software A', nameNormalized: 'calidad de software a', cg: 4, hs: 64 },
        {
          name: 'Administración Empresarial en la Economía del Conocimiento',
          nameNormalized: 'administracion empresarial en la economia del conocimiento',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Redes y Computación de Datos A', nameNormalized: 'redes y computacion de datos a', cg: 4, hs: 64 },
        { name: 'Análisis y Diseño de Sistemas A', nameNormalized: 'analisis y diseno de sistemas a', cg: 6, hs: 96 },
        { name: 'Calidad de Software B', nameNormalized: 'calidad de software b', cg: 4, hs: 64 },
        { name: 'Gestión de Proyectos Informáticos', nameNormalized: 'gestion de proyectos informaticos', cg: 4, hs: 64 },
        { name: 'Gestión de la Seguridad Informática', nameNormalized: 'gestion de la seguridad informatica', cg: 4, hs: 64 },
        {
          name: 'Diseño e Implementación de Sistemas Distribuidos',
          nameNormalized: 'diseno e implementacion de sistemas distribuidos',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Seguridad y Salud Ocupacional', nameNormalized: 'seguridad y salud ocupacional', cg: 4, hs: 64 },
        { name: 'Análisis Matemático III', nameNormalized: 'analisis matematico iii', cg: 6, hs: 96 },
        { name: 'Proyecto Transversal C II', nameNormalized: 'proyecto transversal c ii', cg: 2, hs: 32 },
        { name: 'Teoría de Circuitos', nameNormalized: 'teoria de circuitos', cg: 6, hs: 96 },
        { name: 'Dispositivos y Circuitos Electrónicos', nameNormalized: 'dispositivos y circuitos electronicos', cg: 6, hs: 96 },
        { name: 'Señales y Sistemas de Tiempo Discreto', nameNormalized: 'senales y sistemas de tiempo discreto', cg: 4, hs: 64 },
        { name: 'Programación III', nameNormalized: 'programacion iii', cg: 5, hs: 80 },
        { name: 'Circuitos Digitales', nameNormalized: 'circuitos digitales', cg: 6, hs: 96 },
        { name: 'Sistemas Operativos', nameNormalized: 'sistemas operativos', cg: 6, hs: 96 },
        { name: 'Sistemas Embebidos', nameNormalized: 'sistemas embebidos', cg: 7, hs: 112 },
        { name: 'Ingeniería de Soluciones', nameNormalized: 'ingenieria de soluciones', cg: 4, hs: 64 },
        { name: 'Organización Empresarial e Industrial', nameNormalized: 'organizacion empresarial e industrial', cg: 4, hs: 64 },
        { name: 'Sistemas de Computación Distribuidos I', nameNormalized: 'sistemas de computacion distribuidos i', cg: 6, hs: 96 },
        { name: 'Mecanismos de Seguridad en Redes', nameNormalized: 'mecanismos de seguridad en redes', cg: 3, hs: 48 },
        { name: 'Economía para Ingeniería', nameNormalized: 'economia para ingenieria', cg: 4, hs: 64 },
        { name: 'Diseño Digital Avanzado', nameNormalized: 'diseno digital avanzado', cg: 5, hs: 80 },
        { name: 'Proyecto Transversal C I', nameNormalized: 'proyecto transversal c i', cg: 2, hs: 32 },
        { name: 'Fisica C-II', nameNormalized: 'fisica c-ii', cg: 4, hs: 64 },
        { name: 'Señales y Sistemas de Tiempo Continuo', nameNormalized: 'senales y sistemas de tiempo continuo', cg: 6, hs: 96 },
        { name: 'Proyecto Transversal C III', nameNormalized: 'proyecto transversal c iii', cg: 2, hs: 32 },
        { name: 'Arquitectura de Computadoras', nameNormalized: 'arquitectura de computadoras', cg: 6, hs: 96 },
        { name: 'Control Discreto', nameNormalized: 'control discreto', cg: 6, hs: 96 },
        { name: 'Principios de la Seguridad Informática', nameNormalized: 'principios de la seguridad informatica', cg: 3, hs: 48 },
        { name: 'Fundamentos de Comunicaciones Digitales', nameNormalized: 'fundamentos de comunicaciones digitales', cg: 6, hs: 96 },
        { name: 'Redes de Transmisión de Datos', nameNormalized: 'redes de transmision de datos', cg: 6, hs: 96 },
        {
          name: 'Ética, Legislación y Ejercicio Profesional',
          nameNormalized: 'etica legislacion y ejercicio profesional',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Inteligencia Computacional', nameNormalized: 'inteligencia computacional', cg: 5, hs: 80 },
        { name: 'Sistemas de Computación Distribuidos II', nameNormalized: 'sistemas de computacion distribuidos ii', cg: 6, hs: 96 },
        { name: 'Química General e Inorgánica', nameNormalized: 'quimica general e inorganica', cg: 6, hs: 96 },
        { name: 'Taller de Ingeniería I', nameNormalized: 'taller de ingenieria i', cg: 6, hs: 96 },
        { name: 'Balance de Masa y Energía', nameNormalized: 'balance de masa y energia', cg: 4, hs: 64 },
        { name: 'Fundamentos de la Programación', nameNormalized: 'fundamentos de la programacion', cg: 4, hs: 64 },
        { name: 'Taller de Ingeniería II', nameNormalized: 'taller de ingenieria ii', cg: 6, hs: 96 },
        { name: 'Métodos Numéricos para Ingeniería', nameNormalized: 'metodos numericos para ingenieria', cg: 4, hs: 64 },
        { name: 'Operaciones Unitarias I', nameNormalized: 'operaciones unitarias i', cg: 8, hs: 128 },
        { name: 'Termodinámica II', nameNormalized: 'termodinamica ii', cg: 4, hs: 64 },
        { name: 'Taller de Ingeniería III', nameNormalized: 'taller de ingenieria iii', cg: 8, hs: 128 },
        { name: 'Ingeniería de Reacciones Químicas I', nameNormalized: 'ingenieria de reacciones quimicas i', cg: 7, hs: 112 },
        { name: 'Fisicoquímica I', nameNormalized: 'fisicoquimica i', cg: 5, hs: 80 },
        { name: 'Termodinámica I', nameNormalized: 'termodinamica i', cg: 4, hs: 64 },
        { name: 'Química del Carbono', nameNormalized: 'quimica del carbono', cg: 5, hs: 80 },
        { name: 'Fisicoquímica II', nameNormalized: 'fisicoquimica ii', cg: 3, hs: 48 },
        { name: 'Operación de Plantas de Procesos', nameNormalized: 'operacion de plantas de procesos', cg: 2, hs: 32 },
        { name: 'Operaciones Unitarias II', nameNormalized: 'operaciones unitarias ii', cg: 8, hs: 128 },
        { name: 'Ingeniería de Sistemas de Procesos', nameNormalized: 'ingenieria de sistemas de procesos', cg: 3, hs: 48 },
        { name: 'Ingeniería de Reacciones Químicas II', nameNormalized: 'ingenieria de reacciones quimicas ii', cg: 5, hs: 80 },
        { name: 'Química Biológica y Microbiología', nameNormalized: 'quimica biologica y microbiologia', cg: 4, hs: 64 },
        { name: 'Sistemas de Gestión Integrados', nameNormalized: 'sistemas de gestion integrados', cg: 4, hs: 64 },
        { name: 'Técnicas de Análisis Fisicoquímicos', nameNormalized: 'tecnicas de analisis fisicoquimicos', cg: 4, hs: 64 },
        {
          name: 'Dinámica, Instrumentación y Control de Procesos',
          nameNormalized: 'dinamica, instrumentacion y control de procesos',
          cg: 7,
          hs: 112,
          optional: false,
        },
        { name: 'Tecnología de los Materiales', nameNormalized: 'tecnologia de los materiales', cg: 4, hs: 64 },
        {
          name: 'Ingeniería de los Procesos Biotecnológicos',
          nameNormalized: 'ingenieria de los procesos biotecnologicos',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Álgebra I-A', nameNormalized: 'algebra i-a', cg: 6, hs: 96 },
        {
          name: 'Sistemas de Representación para Ingeniería',
          nameNormalized: 'sistemas de representacion para ingenieria',
          cg: 3,
          hs: 48,
          optional: false,
        },
        { name: 'Fundamentos de Química', nameNormalized: 'fundamentos de quimica', cg: 4, hs: 64 },
        {
          name: 'Fundamentos de la Estática y Resistencia de Materiales',
          nameNormalized: 'fundamentos de la estatica y resistencia de materiales',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Electrotecnia B', nameNormalized: 'electrotecnia b', cg: 6, hs: 96 },
        { name: 'Mediciones Eléctricas A', nameNormalized: 'mediciones electricas a', cg: 6, hs: 96 },
        { name: 'Automatización A', nameNormalized: 'automatizacion a', cg: 6, hs: 96 },
        {
          name: 'Introducción a la Mecánica de los Fluidos',
          nameNormalized: 'introduccion a la mecanica de los fluidos',
          cg: 3,
          hs: 48,
          optional: false,
        },
        { name: 'Máquinas eléctricas B', nameNormalized: 'maquinas electricas b', cg: 6, hs: 96 },
        { name: 'Materiales Electrotécnicos', nameNormalized: 'materiales electrotecnicos', cg: 4, hs: 64 },
        {
          name: 'Formulación y Evaluación de Proyectos de Inversión',
          nameNormalized: 'formulacion y evaluacion de proyectos de inversion',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Instalaciones Eléctricas A', nameNormalized: 'instalaciones electricas a', cg: 6, hs: 96 },
        { name: 'Física C-I', nameNormalized: 'fisica c-i', cg: 6, hs: 96 },
        { name: 'Electrotecnia A', nameNormalized: 'electrotecnia a', cg: 6, hs: 96 },
        {
          name: 'Introducción a la Termodinámica y Máquinas Térmicas',
          nameNormalized: 'introduccion a la termodinamica y maquinas termicas',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Mediciones Eléctricas B', nameNormalized: 'mediciones electricas b', cg: 6, hs: 96 },
        { name: 'Tecnología CAD Aplicada', nameNormalized: 'tecnologia cad aplicada', cg: 4, hs: 64 },
        { name: 'Principios de Electrónica', nameNormalized: 'principios de electronica', cg: 4, hs: 64 },
        { name: 'Electrotecnia C', nameNormalized: 'electrotecnia c', cg: 6, hs: 96 },
        {
          name: 'Sistemas de Transmisión de Energía Eléctrica',
          nameNormalized: 'sistemas de transmision de energia electrica',
          cg: 6,
          hs: 96,
          optional: false,
        },
        { name: 'Instalaciones Eléctricas B', nameNormalized: 'instalaciones electricas b', cg: 4, hs: 64 },
        { name: 'Automatización B', nameNormalized: 'automatizacion b', cg: 4, hs: 64 },
        { name: 'Electrónica de Potencia I', nameNormalized: 'electronica de potencia i', cg: 4, hs: 64 },
        { name: 'Generación de Energía Eléctrica B', nameNormalized: 'generacion de energia electrica b', cg: 4, hs: 64 },
        {
          name: 'Protección y Análisis de Sistemas de Potencia',
          nameNormalized: 'proteccion y analisis de sistemas de potencia',
          cg: 6,
          hs: 96,
          optional: false,
        },
        { name: 'Redes Eléctricas Inteligentes', nameNormalized: 'redes electricas inteligentes', cg: 5, hs: 80 },
        { name: 'Estática I', nameNormalized: 'estatica i', cg: 5, hs: 80 },
        { name: 'Introducción a la Mecánica del Continuo', nameNormalized: 'introduccion a la mecanica del continuo', cg: 3, hs: 48 },
        { name: 'Materiales Estructurales', nameNormalized: 'materiales estructurales', cg: 4, hs: 64 },
        {
          name: 'Mecánica de la Partícula y Cuerpo Rígido',
          nameNormalized: 'mecanica de la particula y cuerpo rigido',
          cg: 7,
          hs: 112,
          optional: false,
        },
        {
          name: 'Introducción a la Metrología y Fabricación',
          nameNormalized: 'introduccion a la metrologia y fabricacion',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Mantenimiento Industrial', nameNormalized: 'mantenimiento industrial', cg: 3, hs: 48 },
        { name: 'Elementos de máquinas', nameNormalized: 'elementos de maquinas', cg: 6, hs: 96 },
        { name: 'Estática II', nameNormalized: 'estatica ii', cg: 5, hs: 80 },
        {
          name: 'Componentes de los Sistemas Eléctricos de Potencia',
          nameNormalized: 'componentes de los sistemas electricos de potencia',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Transferencia y Tecnología del Calor', nameNormalized: 'transferencia y tecnologia del calor', cg: 4, hs: 64 },
        { name: 'Fluidos y Máquinas Fluidodinámicas', nameNormalized: 'fluidos y maquinas fluidodinamicas', cg: 6, hs: 96 },
        { name: 'Proyecto Transversal I', nameNormalized: 'proyecto transversal i', cg: 2, hs: 32 },
        { name: 'Proyecto Transversal II', nameNormalized: 'proyecto transversal ii', cg: 2, hs: 32 },
        { name: 'Física B-I', nameNormalized: 'fisica b-i', cg: 8, hs: 128 },
        { name: 'Proyecto Transversal III', nameNormalized: 'proyecto transversal iii', cg: 2, hs: 32 },
        { name: 'Programación I', nameNormalized: 'programacion i', cg: 5, hs: 80 },
        { name: 'Teoría de Señales y Sistemas', nameNormalized: 'teoria de senales y sistemas', cg: 7, hs: 112 },
        { name: 'Análisis de Circuitos', nameNormalized: 'analisis de circuitos', cg: 7, hs: 112 },
        { name: 'Proyecto Transversal IV', nameNormalized: 'proyecto transversal iv', cg: 2, hs: 32 },
        { name: 'Filtros Analógicos', nameNormalized: 'filtros analogicos', cg: 6, hs: 96 },
        {
          name: 'Probabilidad, Estadística y Procesos Estocásticos',
          nameNormalized: 'probabilidad estadistica y procesos estocasticos',
          cg: 7,
          hs: 112,
          optional: false,
        },
        { name: 'Dispositivos Semiconductores', nameNormalized: 'dispositivos semiconductores', cg: 8, hs: 128 },
        { name: 'Tecnología Electrónica', nameNormalized: 'tecnologia electronica', cg: 3, hs: 48 },
        { name: 'Proyecto Transversal V', nameNormalized: 'proyecto transversal v', cg: 2, hs: 32 },
        { name: 'Técnicas y Dispositivos Digitales', nameNormalized: 'tecnicas y dispositivos digitales', cg: 5, hs: 80 },
        { name: 'Sistemas y Circuitos Electrónicos', nameNormalized: 'sistemas y circuitos electronicos', cg: 6, hs: 96 },
        {
          name: 'Introducción al Tratamiento Digital de Señales',
          nameNormalized: 'introduccion al tratamiento digital de senales',
          cg: 6,
          hs: 96,
          optional: false,
        },
        { name: 'Líneas de Transmisión y Antenas', nameNormalized: 'lineas de transmision y antenas', cg: 6, hs: 96 },
        { name: 'Electrónica Digital', nameNormalized: 'electronica digital', cg: 5, hs: 80 },
        { name: 'Electrónica Aplicada', nameNormalized: 'electronica aplicada', cg: 6, hs: 96 },
        { name: 'Proyecto Transversal VI', nameNormalized: 'proyecto transversal vi', cg: 2, hs: 32 },
        {
          name: 'Instrumentación y Mediciones Electrónicas II',
          nameNormalized: 'instrumentacion y mediciones electronicas ii',
          cg: 6,
          hs: 96,
          optional: false,
        },
        { name: 'Redes de Datos', nameNormalized: 'redes de datos', cg: 5, hs: 80 },
        {
          name: 'Introducción a la Arquitectura de Computadoras',
          nameNormalized: 'introduccion a la arquitectura de computadoras',
          cg: 6,
          hs: 96,
          optional: false,
        },
        { name: 'Control Automático', nameNormalized: 'control automatico', cg: 6, hs: 96 },
        { name: 'Introducción a la Ciencia de Materiales', nameNormalized: 'introduccion a la ciencia de materiales', cg: 6, hs: 96 },
        { name: 'Física Experimental A', nameNormalized: 'fisica experimental a', cg: 4, hs: 64 },
        { name: 'Mecánica de Materiales y Componentes', nameNormalized: 'mecanica de materiales y componentes', cg: 4, hs: 64 },
        { name: 'Química del Estado Sólido', nameNormalized: 'quimica del estado solido', cg: 6, hs: 96 },
        { name: 'Cerámica de Aplicación Industrial', nameNormalized: 'ceramica de aplicacion industrial', cg: 6, hs: 96 },
        { name: 'Transporte de Calor y Materia', nameNormalized: 'transporte de calor y materia', cg: 4, hs: 64 },
        { name: 'Modelado y Simulación de Materiales I', nameNormalized: 'modelado y simulacion de materiales i', cg: 3, hs: 48 },
        {
          name: 'Introducción a la Física del Estado Sólido',
          nameNormalized: 'introduccion a la fisica del estado solido',
          cg: 6,
          hs: 96,
          optional: false,
        },
        { name: 'Introducción al Diseño 3D', nameNormalized: 'introduccion al diseno 3d', cg: 3, hs: 48 },
        { name: 'Termodinámica de Materiales', nameNormalized: 'termodinamica de materiales', cg: 7, hs: 112 },
        { name: 'Fluidodinámica', nameNormalized: 'fluidodinamica', cg: 5, hs: 80 },
        { name: 'Introducción a Polímeros', nameNormalized: 'introduccion a polimeros', cg: 6, hs: 96 },
        { name: 'Propiedades Funcionales de Materiales', nameNormalized: 'propiedades funcionales de materiales', cg: 4, hs: 64 },
        { name: 'Fundamentos de Metalurgia Física', nameNormalized: 'fundamentos de metalurgia fisica', cg: 6, hs: 96 },
        {
          name: 'Comportamiento Mecánico de Polímeros y Cerámicos',
          nameNormalized: 'comportamiento mecanico de polimeros y ceramicos',
          cg: 6,
          hs: 96,
          optional: false,
        },
        { name: 'Modelado y Simulación de Materiales II', nameNormalized: 'modelado y simulacion de materiales ii', cg: 3, hs: 48 },
        { name: 'Procesamiento de Plásticos', nameNormalized: 'procesamiento de plasticos', cg: 6, hs: 96 },
        { name: 'Corrosión de Metales y Aleaciones', nameNormalized: 'corrosion de metales y aleaciones', cg: 4, hs: 64 },
        { name: 'Procesamiento de Compuestos', nameNormalized: 'procesamiento de compuestos', cg: 6, hs: 96 },
        {
          name: 'Laboratorio de Transformación de Materiales',
          nameNormalized: 'laboratorio de transformacion de materiales',
          cg: 5,
          hs: 80,
          optional: false,
        },
        { name: 'Selección de Materiales', nameNormalized: 'seleccion de materiales', cg: 7, hs: 112 },
        {
          name: 'Adquisición y Análisis de la Información Experimental',
          nameNormalized: 'adquisicion y analisis de la informacion experimental',
          cg: 5,
          hs: 80,
          optional: false,
        },
        { name: 'Procesamiento de Metales', nameNormalized: 'procesamiento de metales', cg: 6, hs: 96 },
        { name: 'Propiedades Estructurales de Metales', nameNormalized: 'propiedades estructurales de metales', cg: 3, hs: 48 },
        { name: 'Dibujo A', nameNormalized: 'dibujo a', cg: 3, hs: 48 },
        { name: 'Mecanismos y Elementos de la Mecánica', nameNormalized: 'mecanismos y elementos de la mecanica', cg: 2, hs: 32 },
        { name: 'Termodinámica para Ingeniería Mecánica', nameNormalized: 'termodinamica para ingenieria mecanica', cg: 5, hs: 80 },
        {
          name: 'Mecánica de la Partícula y del Cuerpo Rígido',
          nameNormalized: 'mecanica de la particula y del cuerpo rigido',
          cg: 7,
          hs: 112,
          optional: false,
        },
        {
          name: 'Metrología e Introducción a la Fabricación',
          nameNormalized: 'metrologia e introduccion a la fabricacion',
          cg: 5,
          hs: 80,
          optional: false,
        },
        { name: 'Vibraciones Mecánicas', nameNormalized: 'vibraciones mecanicas', cg: 6, hs: 96 },
        { name: 'Materiales II', nameNormalized: 'materiales ii', cg: 5, hs: 80 },
        { name: 'Dibujo B', nameNormalized: 'dibujo b', cg: 4, hs: 64 },
        { name: 'Física C-II', nameNormalized: 'fisica c-ii', cg: 4, hs: 64 },
        { name: 'Electrotecnia D', nameNormalized: 'electrotecnia d', cg: 4, hs: 64 },
        {
          name: 'Aplicaciones de la Hidráulica y Neumática',
          nameNormalized: 'aplicaciones de la hidraulica y neumatica',
          cg: 3,
          hs: 48,
          optional: false,
        },
        { name: 'Introducción al Modelado Computacional', nameNormalized: 'introduccion al modelado computacional', cg: 4, hs: 64 },
        { name: 'Seminario de Energías Renovables', nameNormalized: 'seminario de energias renovables', cg: 2, hs: 32 },
        { name: 'Materiales I', nameNormalized: 'materiales i', cg: 5, hs: 80 },
        {
          name: 'Conversión Electromecánica de la Energía',
          nameNormalized: 'conversion electromecanica de la energia',
          cg: 4,
          hs: 64,
          optional: false,
        },
        {
          name: 'Tribología, Fricción, Desgaste y Lubricación',
          nameNormalized: 'tribologia friccion desgaste y lubricacion',
          cg: 3,
          hs: 48,
          optional: false,
        },
        { name: 'Sistemas Propulsivos I', nameNormalized: 'sistemas propulsivos i', cg: 5, hs: 80 },
        { name: 'Procesos de Fabricación I', nameNormalized: 'procesos de fabricacion i', cg: 5, hs: 80 },
        { name: 'Electrónica de Control y Automatización', nameNormalized: 'electronica de control y automatizacion', cg: 6, hs: 96 },
        { name: 'Mecánica del Sólido', nameNormalized: 'mecanica del solido', cg: 4, hs: 64 },
        { name: 'Proyecto de Ingeniería Industrial I', nameNormalized: 'proyecto de ingenieria industrial i', cg: 4, hs: 64 },
        { name: 'Administración de Operaciones', nameNormalized: 'administracion de operaciones', cg: 4, hs: 64 },
        { name: 'Investigación Operativa A', nameNormalized: 'investigacion operativa a', cg: 4, hs: 64 },
        {
          name: 'Gestión de la Tecnología y la Innovación',
          nameNormalized: 'gestion de la tecnologia y la innovacion',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Termodinámica Industrial', nameNormalized: 'termodinamica industrial', cg: 4, hs: 64 },
        { name: 'Conceptos de Economía Industrial', nameNormalized: 'conceptos de economia industrial', cg: 4, hs: 64 },
        { name: 'Máquinas y Equipos Industriales I', nameNormalized: 'maquinas y equipos industriales i', cg: 5, hs: 80 },
        {
          name: 'Planificación y Control de la Producción',
          nameNormalized: 'planificacion y control de la produccion',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Investigación Operativa B', nameNormalized: 'investigacion operativa b', cg: 4, hs: 64 },
        { name: 'Mecánica de Fluidos', nameNormalized: 'mecanica de fluidos', cg: 3, hs: 48 },
        {
          name: 'Gestión de la Logística Integral y Cadena de Suministros',
          nameNormalized: 'gestion de la logistica integral y cadena de suministros',
          cg: 4,
          hs: 64,
          optional: false,
        },
        {
          name: 'Formulación y Evaluación de Proyectos Productivos',
          nameNormalized: 'formulacion y evaluacion de proyectos productivos',
          cg: 5,
          hs: 80,
          optional: false,
        },
        { name: 'Gestión Comercial de las Organizaciones', nameNormalized: 'gestion comercial de las organizaciones', cg: 4, hs: 64 },
        { name: 'Tecnología de Control', nameNormalized: 'tecnologia de control', cg: 4, hs: 64 },
        {
          name: 'Introducción a los Procesos de Fabricación',
          nameNormalized: 'introduccion a los procesos de fabricacion',
          cg: 3,
          hs: 48,
          optional: false,
        },
        { name: 'Control de la Producción', nameNormalized: 'control de la produccion', cg: 4, hs: 64 },
        { name: 'Inglés Profesional A', nameNormalized: 'ingles profesional a', cg: 4, hs: 64 },
        { name: 'Sustentabilidad, Higiene y Seguridad', nameNormalized: 'sustentabilidad higiene y seguridad', cg: 5, hs: 80 },
        {
          name: 'Desarrollo Económico y Comercio Internacional',
          nameNormalized: 'desarrollo economico y comercio internacional',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Sistemas Informáticos de Gestión', nameNormalized: 'sistemas informaticos de gestion', cg: 4, hs: 64 },
        { name: 'Proyecto de Ingeniería Industrial IV', nameNormalized: 'proyecto de ingenieria industrial iv', cg: 10, hs: 160 },
        { name: 'Proyecto de Ingeniería Industrial II', nameNormalized: 'proyecto de ingenieria industrial ii', cg: 4, hs: 64 },
        { name: 'Diseño de Instalaciones y Procesos', nameNormalized: 'diseno de instalaciones y procesos', cg: 4, hs: 64 },
        { name: 'Sistemas de Gestión y Mejora Continua', nameNormalized: 'sistemas de gestion y mejora continua', cg: 5, hs: 80 },
        { name: 'Álgebra II-B', nameNormalized: 'algebra ii-b', cg: 5, hs: 75 },
        { name: 'Termodinámica de Alimentos I', nameNormalized: 'termodinamica de alimentos i', cg: 4, hs: 60 },
        { name: 'Química Biológica', nameNormalized: 'quimica biologica', cg: 4, hs: 60 },
        { name: 'Bromatología y Calidad de Alimentos', nameNormalized: 'bromatologia y calidad de alimentos', cg: 7, hs: 105 },
        { name: 'Bioquímica de Alimentos', nameNormalized: 'bioquimica de alimentos', cg: 4, hs: 60 },
        {
          name: 'Transformación y Preservación de Alimentos',
          nameNormalized: 'transformacion y preservacion de alimentos',
          cg: 7,
          hs: 105,
          optional: false,
        },
        { name: 'Industrialización de Alimentos I', nameNormalized: 'industrializacion de alimentos i', cg: 4, hs: 60 },
        { name: 'Control de Procesos en Alimentos', nameNormalized: 'control de procesos en alimentos', cg: 5, hs: 75 },
        { name: 'Industrialización de Alimentos II', nameNormalized: 'industrializacion de alimentos ii', cg: 4, hs: 60 },
        { name: 'Gestión en la Industria Alimentaria', nameNormalized: 'gestion en la industria alimentaria', cg: 4, hs: 60 },
        { name: 'Operaciones unitarias III', nameNormalized: 'operaciones unitarias iii', cg: 8, hs: 128 },
        { name: 'Programación II', nameNormalized: 'programacion ii', cg: 5, hs: 80 },
        { name: 'Introducción a la Ingenieria Mecánica', nameNormalized: 'introduccion a la ingenieria mecanica', cg: 4, hs: 64 },
        { name: 'Administración estratégica', nameNormalized: 'administracion estrategica', cg: 4, hs: 64 },
        { name: 'Inglés profesional B', nameNormalized: 'ingles profesional b', cg: 4, hs: 64 },
        { name: 'Proyecto de Ingeniería Industrial III', nameNormalized: 'proyecto de ingenieria industrial iii', cg: 4, hs: 64 },
        { name: 'Gestión integral del mantenimiento', nameNormalized: 'gestion integral del mantenimiento', cg: 4, hs: 64 },
        {
          name: 'Empresas y servicios basadas en el conocimiento',
          nameNormalized: 'empresas y servicios basadas en el conocimiento',
          cg: 4,
          hs: 64,
          optional: false,
        },
        {
          name: 'Sistemas de representación en plantas de procesos',
          nameNormalized: 'sistemas de representación en plantas de procesos',
          cg: 2,
          hs: 32,
          optional: false,
        },
        { name: 'Termodinámica de alimentos II', nameNormalized: 'termodinamica de alimentos ii', cg: 4, hs: 64 },
        { name: 'Microbiología', nameNormalized: 'microbiologia', cg: 6, hs: 96 },
        { name: 'Sistemas de comunicaciones', nameNormalized: 'sistemas de comunicaciones', cg: 7, hs: 112 },
        {
          name: 'Instrumentación y mediciones electrónicas I',
          nameNormalized: 'instrumentacion y mediciones electronicas i',
          cg: 6,
          hs: 96,
          optional: false,
        },
        { name: 'Máquinas eléctricas A', nameNormalized: 'maquinas electricas a', cg: 6, hs: 96 },
        { name: 'Control I', nameNormalized: 'control i', cg: 4, hs: 64 },
        { name: 'Generación de energía eléctrica A', nameNormalized: 'generacion de energia electrica a', cg: 4, hs: 64 },
        {
          name: 'Sistemas de distribución de energía eléctrica',
          nameNormalized: 'sistemas de distribucion de energia electrica',
          cg: 4,
          hs: 64,
          optional: false,
        },
        { name: 'Accionamientos con Motor eléctrico', nameNormalized: 'accionamientos con motor electrico', cg: 5, hs: 80 },
        { name: 'Ingeniería de Procesos Biotecnológicos', nameNormalized: 'ingenieria de procesos biotecnologicos', cg: 4, hs: 64 },
      ],
    })
}
