import { PrismaClient } from '../prismaClient/client'

export const degreeSeed = async (db: PrismaClient) => {
  const degrees = await db.degree.findMany()
  if (!degrees.length) {
    await db.degree.create({
      data: {
        name: 'Ingeniería Eléctrica',
        courses_degrees: {
          create: [
            { courses: { connect: { name: 'Análisis Matemático I' } } },
            { courses: { connect: { name: 'Física A' } } },
            { courses: { connect: { name: 'Probabilidad y Estadística' } } },
            { courses: { connect: { name: 'Inglés I' } } },
            { courses: { connect: { name: 'Teoría de Modelos y Simulación' } } },
            { courses: { connect: { name: 'Análisis Matemático II' } } },
            { courses: { connect: { name: 'Álgebra II' } } },
            { courses: { connect: { name: 'Inglés II' } } },
            { courses: { connect: { name: 'Análisis Matemático III' } } },
            { courses: { connect: { name: 'Organización Empresarial e Industrial' } } },
            { courses: { connect: { name: 'Fundamentos de la Programación' } } },
            { courses: { connect: { name: 'Álgebra I-A' } } },
            { courses: { connect: { name: 'Sistemas de Representación para Ingeniería' } } },
            { courses: { connect: { name: 'Fundamentos de Química' } } },
            { courses: { connect: { name: 'Fundamentos de la Estática y Resistencia de Materiales' } } },
            { courses: { connect: { name: 'Electrotecnia B' } } },
            { courses: { connect: { name: 'Mediciones Eléctricas A' } } },
            { courses: { connect: { name: 'Automatización A' } } },
            { courses: { connect: { name: 'Introducción a la Mecánica de los Fluidos' } } },
            { courses: { connect: { name: 'Máquinas eléctricas B' } } },
            { courses: { connect: { name: 'Materiales Electrotécnicos' } } },
            { courses: { connect: { name: 'Formulación y Evaluación de Proyectos de Inversión' } } },
            { courses: { connect: { name: 'Instalaciones Eléctricas A' } } },
            { courses: { connect: { name: 'Física C-I' } } },
            { courses: { connect: { name: 'Electrotecnia A' } } },
            { courses: { connect: { name: 'Introducción a la Termodinámica y Máquinas Térmicas' } } },
            { courses: { connect: { name: 'Mediciones Eléctricas B' } } },
            { courses: { connect: { name: 'Tecnología CAD Aplicada' } } },
            { courses: { connect: { name: 'Principios de Electrónica' } } },
            { courses: { connect: { name: 'Electrotecnia C' } } },
            { courses: { connect: { name: 'Sistemas de Transmisión de Energía Eléctrica' } } },
            { courses: { connect: { name: 'Instalaciones Eléctricas B' } } },
            { courses: { connect: { name: 'Automatización B' } } },
            { courses: { connect: { name: 'Electrónica de Potencia I' } } },
            { courses: { connect: { name: 'Generación de Energía Eléctrica B' } } },
            { courses: { connect: { name: 'Protección y Análisis de Sistemas de Potencia' } } },
            { courses: { connect: { name: 'Redes Eléctricas Inteligentes' } } },
            { courses: { connect: { name: 'Física B-I' } } },
            { courses: { connect: { name: 'Máquinas eléctricas A' } } },
            { courses: { connect: { name: 'Control I' } } },
            { courses: { connect: { name: 'Generación de energía eléctrica A' } } },
            { courses: { connect: { name: 'Sistemas de distribución de energía eléctrica' } } },
            { courses: { connect: { name: 'Accionamientos con Motor eléctrico' } } },
          ],
        },
      },
    })
    await db.degree.create({
      data: {
        name: 'Ingeniería Informática',
        courses_degrees: {
          create: [
            { courses: { connect: { name: 'Análisis Matemático I' } } },
            { courses: { connect: { name: 'Álgebra I-B' } } },
            { courses: { connect: { name: 'Informática Básica' } } },
            { courses: { connect: { name: 'Tecnologías Informáticas A' } } },
            { courses: { connect: { name: 'Física A' } } },
            { courses: { connect: { name: 'Probabilidad y Estadística' } } },
            { courses: { connect: { name: 'Programación B' } } },
            { courses: { connect: { name: 'Tecnologías Informáticas B' } } },
            { courses: { connect: { name: 'Inglés I' } } },
            { courses: { connect: { name: 'Investigación de Operaciones' } } },
            { courses: { connect: { name: 'Estructura y Organización de Datos' } } },
            { courses: { connect: { name: 'Fundamentos de Sistemas Operativos' } } },
            { courses: { connect: { name: 'Fundamentos de Lenguajes Formales' } } },
            { courses: { connect: { name: 'Sistemas de Bases de Datos' } } },
            { courses: { connect: { name: 'Introducción a la Inteligencia Artificial' } } },
            { courses: { connect: { name: 'Redes y Comunicación de Datos B' } } },
            { courses: { connect: { name: 'Análisis y Diseño de Sistemas B' } } },
            { courses: { connect: { name: 'Comportamiento Organizacional y Relaciones del Trabajo' } } },
            { courses: { connect: { name: 'Ética, Legislación y Propiedad Intelectual en el Ejercicio Profesional' } } },
            { courses: { connect: { name: 'Auditoría y homologación' } } },
            { courses: { connect: { name: 'Análisis Matemático II' } } },
            { courses: { connect: { name: 'Álgebra II' } } },
            { courses: { connect: { name: 'Programación A' } } },
            { courses: { connect: { name: 'Introducción a la Matemática Discreta' } } },
            { courses: { connect: { name: 'Física B-II' } } },
            { courses: { connect: { name: 'Teorías de la Información y la Computación' } } },
            { courses: { connect: { name: 'Fundamentos de la Arquitectura de Computadoras' } } },
            { courses: { connect: { name: 'Programación C' } } },
            { courses: { connect: { name: 'Inglés II' } } },
            { courses: { connect: { name: 'Calidad de Software A' } } },
            { courses: { connect: { name: 'Administración Empresarial en la Economía del Conocimiento' } } },
            { courses: { connect: { name: 'Redes y Computación de Datos A' } } },
            { courses: { connect: { name: 'Análisis y Diseño de Sistemas A' } } },
            { courses: { connect: { name: 'Calidad de Software B' } } },
            { courses: { connect: { name: 'Gestión de Proyectos Informáticos' } } },
            { courses: { connect: { name: 'Gestión de la Seguridad Informática' } } },
            { courses: { connect: { name: 'Diseño e Implementación de Sistemas Distribuidos' } } },
            { courses: { connect: { name: 'Seguridad y Salud Ocupacional' } } },
            { courses: { connect: { name: 'Arquitectura de Computadoras' } } },
          ],
        },
      },
    })
    await db.degree.create({
      data: {
        name: 'Ingeniería Electromecánica',
        courses_degrees: {
          create: [
            { courses: { connect: { name: 'Análisis Matemático I' } } },
            { courses: { connect: { name: 'Física A' } } },
            { courses: { connect: { name: 'Probabilidad y Estadística' } } },
            { courses: { connect: { name: 'Inglés I' } } },
            { courses: { connect: { name: 'Ética, Legislación y Propiedad Intelectual en el Ejercicio Profesional' } } },
            { courses: { connect: { name: 'Análisis Matemático II' } } },
            { courses: { connect: { name: 'Álgebra II' } } },
            { courses: { connect: { name: 'Inglés II' } } },
            { courses: { connect: { name: 'Análisis Matemático III' } } },
            { courses: { connect: { name: 'Organización Empresarial e Industrial' } } },
            { courses: { connect: { name: 'Fundamentos de la Programación' } } },
            { courses: { connect: { name: 'Sistemas de Gestión Integrados' } } },
            { courses: { connect: { name: 'Álgebra I-A' } } },
            { courses: { connect: { name: 'Sistemas de Representación para Ingeniería' } } },
            { courses: { connect: { name: 'Fundamentos de Química' } } },
            { courses: { connect: { name: 'Electrotecnia B' } } },
            { courses: { connect: { name: 'Mediciones Eléctricas A' } } },
            { courses: { connect: { name: 'Automatización A' } } },
            { courses: { connect: { name: 'Máquinas eléctricas B' } } },
            { courses: { connect: { name: 'Materiales Electrotécnicos' } } },
            { courses: { connect: { name: 'Formulación y Evaluación de Proyectos de Inversión' } } },
            { courses: { connect: { name: 'Instalaciones Eléctricas A' } } },
            { courses: { connect: { name: 'Física C-I' } } },
            { courses: { connect: { name: 'Electrotecnia A' } } },
            { courses: { connect: { name: 'Introducción a la Termodinámica y Máquinas Térmicas' } } },
            { courses: { connect: { name: 'Mediciones Eléctricas B' } } },
            { courses: { connect: { name: 'Tecnología CAD Aplicada' } } },
            { courses: { connect: { name: 'Principios de Electrónica' } } },
            { courses: { connect: { name: 'Instalaciones Eléctricas B' } } },
            { courses: { connect: { name: 'Electrónica de Potencia I' } } },
            { courses: { connect: { name: 'Estática I' } } },
            { courses: { connect: { name: 'Introducción a la Mecánica del Continuo' } } },
            { courses: { connect: { name: 'Materiales Estructurales' } } },
            { courses: { connect: { name: 'Mecánica de la Partícula y Cuerpo Rígido' } } },
            { courses: { connect: { name: 'Introducción a la Metrología y Fabricación' } } },
            { courses: { connect: { name: 'Mantenimiento Industrial' } } },
            { courses: { connect: { name: 'Elementos de máquinas' } } },
            { courses: { connect: { name: 'Estática II' } } },
            { courses: { connect: { name: 'Componentes de los Sistemas Eléctricos de Potencia' } } },
            { courses: { connect: { name: 'Transferencia y Tecnología del Calor' } } },
            { courses: { connect: { name: 'Fluidos y Máquinas Fluidodinámicas' } } },
            { courses: { connect: { name: 'Física B-I' } } },
            { courses: { connect: { name: 'Procesos de Fabricación I' } } },
            { courses: { connect: { name: 'Máquinas eléctricas A' } } },
            { courses: { connect: { name: 'Control I' } } },
          ],
        },
      },
    })
    await db.degree.create({
      data: {
        name: 'Ingeniería Electrónica',
        courses_degrees: {
          create: [
            { courses: { connect: { name: 'Análisis Matemático I' } } },
            { courses: { connect: { name: 'Informática Básica' } } },
            { courses: { connect: { name: 'Física A' } } },
            { courses: { connect: { name: 'Inglés I' } } },
            { courses: { connect: { name: 'Ética, Legislación y Propiedad Intelectual en el Ejercicio Profesional' } } },
            { courses: { connect: { name: 'Análisis Matemático II' } } },
            { courses: { connect: { name: 'Álgebra II' } } },
            { courses: { connect: { name: 'Inglés II' } } },
            { courses: { connect: { name: 'Seguridad y Salud Ocupacional' } } },
            { courses: { connect: { name: 'Análisis Matemático III' } } },
            { courses: { connect: { name: 'Organización Empresarial e Industrial' } } },
            { courses: { connect: { name: 'Economía para Ingeniería' } } },
            { courses: { connect: { name: 'Ética, Legislación y Ejercicio Profesional' } } },
            { courses: { connect: { name: 'Álgebra I-A' } } },
            { courses: { connect: { name: 'Fundamentos de Química' } } },
            { courses: { connect: { name: 'Física C-I' } } },
            { courses: { connect: { name: 'Proyecto Transversal I' } } },
            { courses: { connect: { name: 'Proyecto Transversal II' } } },
            { courses: { connect: { name: 'Física B-I' } } },
            { courses: { connect: { name: 'Proyecto Transversal III' } } },
            { courses: { connect: { name: 'Programación I' } } },
            { courses: { connect: { name: 'Teoría de Señales y Sistemas' } } },
            { courses: { connect: { name: 'Análisis de Circuitos' } } },
            { courses: { connect: { name: 'Proyecto Transversal IV' } } },
            { courses: { connect: { name: 'Filtros Analógicos' } } },
            { courses: { connect: { name: 'Probabilidad, Estadística y Procesos Estocásticos' } } },
            { courses: { connect: { name: 'Dispositivos Semiconductores' } } },
            { courses: { connect: { name: 'Tecnología Electrónica' } } },
            { courses: { connect: { name: 'Proyecto Transversal V' } } },
            { courses: { connect: { name: 'Técnicas y Dispositivos Digitales' } } },
            { courses: { connect: { name: 'Sistemas y Circuitos Electrónicos' } } },
            { courses: { connect: { name: 'Introducción al Tratamiento Digital de Señales' } } },
            { courses: { connect: { name: 'Líneas de Transmisión y Antenas' } } },
            { courses: { connect: { name: 'Electrónica Digital' } } },
            { courses: { connect: { name: 'Electrónica Aplicada' } } },
            { courses: { connect: { name: 'Proyecto Transversal VI' } } },
            { courses: { connect: { name: 'Instrumentación y Mediciones Electrónicas II' } } },
            { courses: { connect: { name: 'Redes de Datos' } } },
            { courses: { connect: { name: 'Introducción a la Arquitectura de Computadoras' } } },
            { courses: { connect: { name: 'Control Automático' } } },
            { courses: { connect: { name: 'Sistemas de comunicaciones' } } },
            { courses: { connect: { name: 'Instrumentación y mediciones electrónicas I' } } },
          ],
        },
      },
    })
    await db.degree.create({
      data: {
        name: 'Ingeniería en Alimentos',
        courses_degrees: {
          create: [
            { courses: { connect: { name: 'Análisis Matemático I' } } },
            { courses: { connect: { name: 'Álgebra I-B' } } },
            { courses: { connect: { name: 'Física A' } } },
            { courses: { connect: { name: 'Probabilidad y Estadística' } } },
            { courses: { connect: { name: 'Inglés I' } } },
            { courses: { connect: { name: 'Ética, Legislación y Propiedad Intelectual en el Ejercicio Profesional' } } },
            { courses: { connect: { name: 'Análisis Matemático II' } } },
            { courses: { connect: { name: 'Física B-II' } } },
            { courses: { connect: { name: 'Inglés II' } } },
            { courses: { connect: { name: 'Seguridad y Salud Ocupacional' } } },
            { courses: { connect: { name: 'Análisis Matemático III' } } },
            { courses: { connect: { name: 'Organización Empresarial e Industrial' } } },
            { courses: { connect: { name: 'Fisica C-II' } } },
            { courses: { connect: { name: 'Química General e Inorgánica' } } },
            { courses: { connect: { name: 'Taller de Ingeniería I' } } },
            { courses: { connect: { name: 'Balance de Masa y Energía' } } },
            { courses: { connect: { name: 'Fundamentos de la Programación' } } },
            { courses: { connect: { name: 'Taller de Ingeniería II' } } },
            { courses: { connect: { name: 'Métodos Numéricos para Ingeniería' } } },
            { courses: { connect: { name: 'Operaciones Unitarias I' } } },
            { courses: { connect: { name: 'Taller de Ingeniería III' } } },
            { courses: { connect: { name: 'Fisicoquímica I' } } },
            { courses: { connect: { name: 'Química del Carbono' } } },
            { courses: { connect: { name: 'Fisicoquímica II' } } },
            { courses: { connect: { name: 'Operación de Plantas de Procesos' } } },
            { courses: { connect: { name: 'Operaciones Unitarias II' } } },
            { courses: { connect: { name: 'Sistemas de Gestión Integrados' } } },
            { courses: { connect: { name: 'Técnicas de Análisis Fisicoquímicos' } } },
            { courses: { connect: { name: 'Formulación y Evaluación de Proyectos de Inversión' } } },
            { courses: { connect: { name: 'Álgebra II-B' } } },
            { courses: { connect: { name: 'Termodinámica de Alimentos I' } } },
            { courses: { connect: { name: 'Química Biológica' } } },
            { courses: { connect: { name: 'Bromatología y Calidad de Alimentos' } } },
            { courses: { connect: { name: 'Bioquímica de Alimentos' } } },
            { courses: { connect: { name: 'Transformación y Preservación de Alimentos' } } },
            { courses: { connect: { name: 'Industrialización de Alimentos I' } } },
            { courses: { connect: { name: 'Control de Procesos en Alimentos' } } },
            { courses: { connect: { name: 'Industrialización de Alimentos II' } } },
            { courses: { connect: { name: 'Gestión en la Industria Alimentaria' } } },
            { courses: { connect: { name: 'Operaciones unitarias III' } } },
            { courses: { connect: { name: 'Sistemas de representación en plantas de procesos' } } },
            { courses: { connect: { name: 'Termodinámica de alimentos II' } } },
            { courses: { connect: { name: 'Microbiología' } } },
            { courses: { connect: { name: 'Ingeniería de Procesos Biotecnológicos' } } },
          ],
        },
      },
    })
    await db.degree.create({
      data: {
        name: 'Ingeniería Química',
        courses_degrees: {
          create: [
            { courses: { connect: { name: 'Análisis Matemático I' } } },
            { courses: { connect: { name: 'Álgebra I-B' } } },
            { courses: { connect: { name: 'Física A' } } },
            { courses: { connect: { name: 'Probabilidad y Estadística' } } },
            { courses: { connect: { name: 'Inglés I' } } },
            { courses: { connect: { name: 'Ética, Legislación y Propiedad Intelectual en el Ejercicio Profesional' } } },
            { courses: { connect: { name: 'Análisis Matemático II' } } },
            { courses: { connect: { name: 'Álgebra II' } } },
            { courses: { connect: { name: 'Física B-II' } } },
            { courses: { connect: { name: 'Inglés II' } } },
            { courses: { connect: { name: 'Seguridad y Salud Ocupacional' } } },
            { courses: { connect: { name: 'Análisis Matemático III' } } },
            { courses: { connect: { name: 'Organización Empresarial e Industrial' } } },
            { courses: { connect: { name: 'Fisica C-II' } } },
            { courses: { connect: { name: 'Química General e Inorgánica' } } },
            { courses: { connect: { name: 'Taller de Ingeniería I' } } },
            { courses: { connect: { name: 'Balance de Masa y Energía' } } },
            { courses: { connect: { name: 'Fundamentos de la Programación' } } },
            { courses: { connect: { name: 'Taller de Ingeniería II' } } },
            { courses: { connect: { name: 'Métodos Numéricos para Ingeniería' } } },
            { courses: { connect: { name: 'Operaciones Unitarias I' } } },
            { courses: { connect: { name: 'Termodinámica II' } } },
            { courses: { connect: { name: 'Taller de Ingeniería III' } } },
            { courses: { connect: { name: 'Ingeniería de Reacciones Químicas I' } } },
            { courses: { connect: { name: 'Fisicoquímica I' } } },
            { courses: { connect: { name: 'Termodinámica I' } } },
            { courses: { connect: { name: 'Química del Carbono' } } },
            { courses: { connect: { name: 'Fisicoquímica II' } } },
            { courses: { connect: { name: 'Operación de Plantas de Procesos' } } },
            { courses: { connect: { name: 'Operaciones Unitarias II' } } },
            { courses: { connect: { name: 'Ingeniería de Sistemas de Procesos' } } },
            { courses: { connect: { name: 'Ingeniería de Reacciones Químicas II' } } },
            { courses: { connect: { name: 'Química Biológica y Microbiología' } } },
            { courses: { connect: { name: 'Sistemas de Gestión Integrados' } } },
            { courses: { connect: { name: 'Técnicas de Análisis Fisicoquímicos' } } },
            { courses: { connect: { name: 'Dinámica, Instrumentación y Control de Procesos' } } },
            { courses: { connect: { name: 'Tecnología de los Materiales' } } },
            { courses: { connect: { name: 'Ingeniería de los Procesos Biotecnológicos' } } },
            { courses: { connect: { name: 'Formulación y Evaluación de Proyectos de Inversión' } } },
            { courses: { connect: { name: 'Operaciones unitarias III' } } },
          ],
        },
      },
    })
    await db.degree.create({
      data: {
        name: 'Ingeniería en Computación',
        courses_degrees: {
          create: [
            { courses: { connect: { name: 'Análisis Matemático I' } } },
            { courses: { connect: { name: 'Informática Básica' } } },
            { courses: { connect: { name: 'Física A' } } },
            { courses: { connect: { name: 'Probabilidad y Estadística' } } },
            { courses: { connect: { name: 'Inglés I' } } },
            { courses: { connect: { name: 'Sistemas de Bases de Datos' } } },
            { courses: { connect: { name: 'Ética, Legislación y Propiedad Intelectual en el Ejercicio Profesional' } } },
            { courses: { connect: { name: 'Análisis Matemático II' } } },
            { courses: { connect: { name: 'Álgebra II' } } },
            { courses: { connect: { name: 'Introducción a la Matemática Discreta' } } },
            { courses: { connect: { name: 'Inglés II' } } },
            { courses: { connect: { name: 'Seguridad y Salud Ocupacional' } } },
            { courses: { connect: { name: 'Análisis Matemático III' } } },
            { courses: { connect: { name: 'Proyecto Transversal C II' } } },
            { courses: { connect: { name: 'Teoría de Circuitos' } } },
            { courses: { connect: { name: 'Dispositivos y Circuitos Electrónicos' } } },
            { courses: { connect: { name: 'Señales y Sistemas de Tiempo Discreto' } } },
            { courses: { connect: { name: 'Programación III' } } },
            { courses: { connect: { name: 'Circuitos Digitales' } } },
            { courses: { connect: { name: 'Sistemas Operativos' } } },
            { courses: { connect: { name: 'Sistemas Embebidos' } } },
            { courses: { connect: { name: 'Ingeniería de Soluciones' } } },
            { courses: { connect: { name: 'Organización Empresarial e Industrial' } } },
            { courses: { connect: { name: 'Sistemas de Computación Distribuidos I' } } },
            { courses: { connect: { name: 'Mecanismos de Seguridad en Redes' } } },
            { courses: { connect: { name: 'Economía para Ingeniería' } } },
            { courses: { connect: { name: 'Diseño Digital Avanzado' } } },
            { courses: { connect: { name: 'Proyecto Transversal C I' } } },
            { courses: { connect: { name: 'Fisica C-II' } } },
            { courses: { connect: { name: 'Señales y Sistemas de Tiempo Continuo' } } },
            { courses: { connect: { name: 'Proyecto Transversal C III' } } },
            { courses: { connect: { name: 'Arquitectura de Computadoras' } } },
            { courses: { connect: { name: 'Control Discreto' } } },
            { courses: { connect: { name: 'Principios de la Seguridad Informática' } } },
            { courses: { connect: { name: 'Fundamentos de Comunicaciones Digitales' } } },
            { courses: { connect: { name: 'Redes de Transmisión de Datos' } } },
            { courses: { connect: { name: 'Ética, Legislación y Ejercicio Profesional' } } },
            { courses: { connect: { name: 'Inteligencia Computacional' } } },
            { courses: { connect: { name: 'Sistemas de Computación Distribuidos II' } } },
            { courses: { connect: { name: 'Álgebra I-A' } } },
            { courses: { connect: { name: 'Física B-I' } } },
            { courses: { connect: { name: 'Programación I' } } },
            { courses: { connect: { name: 'Programación II' } } },
          ],
        },
      },
    })
    await db.degree.create({
      data: {
        name: 'Ingeniería en Materiales',
        courses_degrees: {
          create: [
            { courses: { connect: { name: 'Análisis Matemático I' } } },
            { courses: { connect: { name: 'Física A' } } },
            { courses: { connect: { name: 'Inglés I' } } },
            { courses: { connect: { name: 'Ética, Legislación y Propiedad Intelectual en el Ejercicio Profesional' } } },
            { courses: { connect: { name: 'Análisis Matemático II' } } },
            { courses: { connect: { name: 'Álgebra II' } } },
            { courses: { connect: { name: 'Inglés II' } } },
            { courses: { connect: { name: 'Seguridad y Salud Ocupacional' } } },
            { courses: { connect: { name: 'Análisis Matemático III' } } },
            { courses: { connect: { name: 'Organización Empresarial e Industrial' } } },
            { courses: { connect: { name: 'Métodos Numéricos para Ingeniería' } } },
            { courses: { connect: { name: 'Sistemas de Gestión Integrados' } } },
            { courses: { connect: { name: 'Álgebra I-A' } } },
            { courses: { connect: { name: 'Fundamentos de Química' } } },
            { courses: { connect: { name: 'Formulación y Evaluación de Proyectos de Inversión' } } },
            { courses: { connect: { name: 'Física C-I' } } },
            { courses: { connect: { name: 'Estática I' } } },
            { courses: { connect: { name: 'Estática II' } } },
            { courses: { connect: { name: 'Física B-I' } } },
            { courses: { connect: { name: 'Introducción a la Ciencia de Materiales' } } },
            { courses: { connect: { name: 'Física Experimental A' } } },
            { courses: { connect: { name: 'Mecánica de Materiales y Componentes' } } },
            { courses: { connect: { name: 'Química del Estado Sólido' } } },
            { courses: { connect: { name: 'Cerámica de Aplicación Industrial' } } },
            { courses: { connect: { name: 'Transporte de Calor y Materia' } } },
            { courses: { connect: { name: 'Modelado y Simulación de Materiales I' } } },
            { courses: { connect: { name: 'Introducción a la Física del Estado Sólido' } } },
            { courses: { connect: { name: 'Introducción al Diseño 3D' } } },
            { courses: { connect: { name: 'Termodinámica de Materiales' } } },
            { courses: { connect: { name: 'Fluidodinámica' } } },
            { courses: { connect: { name: 'Introducción a Polímeros' } } },
            { courses: { connect: { name: 'Propiedades Funcionales de Materiales' } } },
            { courses: { connect: { name: 'Fundamentos de Metalurgia Física' } } },
            { courses: { connect: { name: 'Comportamiento Mecánico de Polímeros y Cerámicos' } } },
            { courses: { connect: { name: 'Modelado y Simulación de Materiales II' } } },
            { courses: { connect: { name: 'Procesamiento de Plásticos' } } },
            { courses: { connect: { name: 'Corrosión de Metales y Aleaciones' } } },
            { courses: { connect: { name: 'Procesamiento de Compuestos' } } },
            { courses: { connect: { name: 'Laboratorio de Transformación de Materiales' } } },
            { courses: { connect: { name: 'Selección de Materiales' } } },
            { courses: { connect: { name: 'Adquisición y Análisis de la Información Experimental' } } },
            { courses: { connect: { name: 'Procesamiento de Metales' } } },
            { courses: { connect: { name: 'Propiedades Estructurales de Metales' } } },
          ],
        },
      },
    })
    await db.degree.create({
      data: {
        name: 'Ingeniería Industrial',
        courses_degrees: {
          create: [
            { courses: { connect: { name: 'Análisis Matemático I' } } },
            { courses: { connect: { name: 'Álgebra I-B' } } },
            { courses: { connect: { name: 'Física A' } } },
            { courses: { connect: { name: 'Probabilidad y Estadística' } } },
            { courses: { connect: { name: 'Inglés I' } } },
            { courses: { connect: { name: 'Comportamiento Organizacional y Relaciones del Trabajo' } } },
            { courses: { connect: { name: 'Ética, Legislación y Propiedad Intelectual en el Ejercicio Profesional' } } },
            { courses: { connect: { name: 'Análisis Matemático II' } } },
            { courses: { connect: { name: 'Álgebra II' } } },
            { courses: { connect: { name: 'Física B-II' } } },
            { courses: { connect: { name: 'Inglés II' } } },
            { courses: { connect: { name: 'Análisis Matemático III' } } },
            { courses: { connect: { name: 'Tecnología de los Materiales' } } },
            { courses: { connect: { name: 'Fundamentos de Química' } } },
            { courses: { connect: { name: 'Física Experimental A' } } },
            { courses: { connect: { name: 'Mecánica del Sólido' } } },
            { courses: { connect: { name: 'Proyecto de Ingeniería Industrial I' } } },
            { courses: { connect: { name: 'Administración de Operaciones' } } },
            { courses: { connect: { name: 'Investigación Operativa A' } } },
            { courses: { connect: { name: 'Gestión de la Tecnología y la Innovación' } } },
            { courses: { connect: { name: 'Termodinámica Industrial' } } },
            { courses: { connect: { name: 'Conceptos de Economía Industrial' } } },
            { courses: { connect: { name: 'Máquinas y Equipos Industriales I' } } },
            { courses: { connect: { name: 'Planificación y Control de la Producción' } } },
            { courses: { connect: { name: 'Investigación Operativa B' } } },
            { courses: { connect: { name: 'Mecánica de Fluidos' } } },
            { courses: { connect: { name: 'Gestión de la Logística Integral y Cadena de Suministros' } } },
            { courses: { connect: { name: 'Formulación y Evaluación de Proyectos Productivos' } } },
            { courses: { connect: { name: 'Gestión Comercial de las Organizaciones' } } },
            { courses: { connect: { name: 'Tecnología de Control' } } },
            { courses: { connect: { name: 'Introducción a los Procesos de Fabricación' } } },
            { courses: { connect: { name: 'Control de la Producción' } } },
            { courses: { connect: { name: 'Inglés Profesional A' } } },
            { courses: { connect: { name: 'Sustentabilidad, Higiene y Seguridad' } } },
            { courses: { connect: { name: 'Desarrollo Económico y Comercio Internacional' } } },
            { courses: { connect: { name: 'Sistemas Informáticos de Gestión' } } },
            { courses: { connect: { name: 'Proyecto de Ingeniería Industrial IV' } } },
            { courses: { connect: { name: 'Proyecto de Ingeniería Industrial II' } } },
            { courses: { connect: { name: 'Diseño de Instalaciones y Procesos' } } },
            { courses: { connect: { name: 'Sistemas de Gestión y Mejora Continua' } } },
            { courses: { connect: { name: 'Administración estratégica' } } },
            { courses: { connect: { name: 'Inglés profesional B' } } },
            { courses: { connect: { name: 'Proyecto de Ingeniería Industrial III' } } },
            { courses: { connect: { name: 'Gestión integral del mantenimiento' } } },
            { courses: { connect: { name: 'Empresas y servicios basadas en el conocimiento' } } },
          ],
        },
      },
    })
    await db.degree.create({
      data: {
        name: 'Ingeniería Mecánica',
        courses_degrees: {
          create: [
            { courses: { connect: { name: 'Análisis Matemático I' } } },
            { courses: { connect: { name: 'Física A' } } },
            { courses: { connect: { name: 'Inglés I' } } },
            { courses: { connect: { name: 'Ética, Legislación y Propiedad Intelectual en el Ejercicio Profesional' } } },
            { courses: { connect: { name: 'Análisis Matemático II' } } },
            { courses: { connect: { name: 'Álgebra II' } } },
            { courses: { connect: { name: 'Física B-II' } } },
            { courses: { connect: { name: 'Inglés II' } } },
            { courses: { connect: { name: 'Seguridad y Salud Ocupacional' } } },
            { courses: { connect: { name: 'Análisis Matemático III' } } },
            { courses: { connect: { name: 'Organización Empresarial e Industrial' } } },
            { courses: { connect: { name: 'Economía para Ingeniería' } } },
            { courses: { connect: { name: 'Fisica C-II' } } },
            { courses: { connect: { name: 'Fundamentos de la Programación' } } },
            { courses: { connect: { name: 'Álgebra I-A' } } },
            { courses: { connect: { name: 'Fundamentos de Química' } } },
            { courses: { connect: { name: 'Estática I' } } },
            { courses: { connect: { name: 'Introducción a la Mecánica del Continuo' } } },
            { courses: { connect: { name: 'Mantenimiento Industrial' } } },
            { courses: { connect: { name: 'Elementos de máquinas' } } },
            { courses: { connect: { name: 'Estática II' } } },
            { courses: { connect: { name: 'Transferencia y Tecnología del Calor' } } },
            { courses: { connect: { name: 'Fluidos y Máquinas Fluidodinámicas' } } },
            { courses: { connect: { name: 'Física Experimental A' } } },
            { courses: { connect: { name: 'Dibujo A' } } },
            { courses: { connect: { name: 'Mecanismos y Elementos de la Mecánica' } } },
            { courses: { connect: { name: 'Termodinámica para Ingeniería Mecánica' } } },
            { courses: { connect: { name: 'Mecánica de la Partícula y del Cuerpo Rígido' } } },
            { courses: { connect: { name: 'Metrología e Introducción a la Fabricación' } } },
            { courses: { connect: { name: 'Vibraciones Mecánicas' } } },
            { courses: { connect: { name: 'Materiales II' } } },
            { courses: { connect: { name: 'Dibujo B' } } },
            { courses: { connect: { name: 'Física C-II' } } },
            { courses: { connect: { name: 'Electrotecnia D' } } },
            { courses: { connect: { name: 'Aplicaciones de la Hidráulica y Neumática' } } },
            { courses: { connect: { name: 'Introducción al Modelado Computacional' } } },
            { courses: { connect: { name: 'Seminario de Energías Renovables' } } },
            { courses: { connect: { name: 'Materiales I' } } },
            { courses: { connect: { name: 'Conversión Electromecánica de la Energía' } } },
            { courses: { connect: { name: 'Tribología, Fricción, Desgaste y Lubricación' } } },
            { courses: { connect: { name: 'Sistemas Propulsivos I' } } },
            { courses: { connect: { name: 'Procesos de Fabricación I' } } },
            { courses: { connect: { name: 'Electrónica de Control y Automatización' } } },
            { courses: { connect: { name: 'Introducción a la Ingenieria Mecánica' } } },
          ],
        },
      },
    })
  }
}
